### ISSUE TITLE
Parser support for deferrable foreign key constraints in column def

### ISSUE THREAD

**Issue by andrewdoss-bit** [tobymao/sqlglot#1007]
The parser does not expect an optional "deferrable" clause for foreign key constraints inside column definitions.

Example:

```python
sql = "CREATE TABLE foo (baz_id INTEGER REFERENCES baz (id) DEFERRABLE);"
sqlglot.parse_one(sql)
```

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/foo/product/sqlglot/sqlglot/__init__.py", line 84, in parse_one
    result = dialect.parse(sql, **opts)
  File "/Users/foo/product/sqlglot/sqlglot/dialects/dialect.py", line 151, in parse
    return self.parser(**opts).parse(self.tokenizer.tokenize(sql), sql)
  File "/Users/foo/product/sqlglot/sqlglot/parser.py", line 672, in parse
    return self._parse(
  File "/Users/foo/product/sqlglot/sqlglot/parser.py", line 734, in _parse
    expressions.append(parse_method(self))
  File "/Users/foo/product/sqlglot/sqlglot/parser.py", line 874, in _parse_statement
    return self.STATEMENT_PARSERS[self._prev.token_type](self)
  File "/Users/foo/product/sqlglot/sqlglot/parser.py", line 433, in <lambda>
    TokenType.CREATE: lambda self: self._parse_create(),
  File "/Users/foo/product/sqlglot/sqlglot/parser.py", line 955, in _parse_create
    this = self._parse_table(schema=True)
  File "/Users/foo/product/sqlglot/sqlglot/parser.py", line 1603, in _parse_table
    return self._parse_schema(this=this)
  File "/Users/foo/product/sqlglot/sqlglot/parser.py", line 2366, in _parse_schema
    self._match_r_paren()
  File "/Users/foo/product/sqlglot/sqlglot/parser.py", line 3173, in _match_r_paren
    self.raise_error("Expecting )")
  File "/Users/foo/product/sqlglot/sqlglot/parser.py", line 780, in raise_error
    raise error
sqlglot.errors.ParseError: Expecting ). Line 1, Col: 54.
  CREATE TABLE foo (baz_id INTEGER REFERENCES baz (id) DEFERRABLE);
```

Variations: `DEFERRABLE`, `DEFERRABLE INITIALLY DEFERRED`, `DEFERRABLE IMMEDIATELY DEFERRED`

Refs:
[sqlite syntax](https://www.sqlite.org/syntax/foreign-key-clause.html)
[postgres syntax](https://www.postgresql.org/docs/current/sql-createtable.html)

**Comment by andrewdoss-bit** [comment]
Thanks!
