### ISSUE TITLE
Support create table <identifier> if not exists (snowflake)

### ISSUE THREAD

**Issue by tekumara** [tobymao/sqlglot#1037]
```
❯ python -c 'import sqlglot; sqlglot.parse_one("create table foo if not exists (id int)",read="snowflake")'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/oliver.mannion/code/fakesnow/.venv/lib/python3.9/site-packages/sqlglot/__init__.py", line 87, in parse_one
    result = dialect.parse(sql, **opts)
  File "/Users/oliver.mannion/code/fakesnow/.venv/lib/python3.9/site-packages/sqlglot/dialects/dialect.py", line 151, in parse
    return self.parser(**opts).parse(self.tokenizer.tokenize(sql), sql)
  File "/Users/oliver.mannion/code/fakesnow/.venv/lib/python3.9/site-packages/sqlglot/parser.py", line 684, in parse
    return self._parse(
  File "/Users/oliver.mannion/code/fakesnow/.venv/lib/python3.9/site-packages/sqlglot/parser.py", line 749, in _parse
    self.raise_error("Invalid expression / Unexpected token")
  File "/Users/oliver.mannion/code/fakesnow/.venv/lib/python3.9/site-packages/sqlglot/parser.py", line 792, in raise_error
    raise error
sqlglot.errors.ParseError: Invalid expression / Unexpected token. Line 1, Col: 18.
  create table foo if not exists (id int)
```

Snowflake will accept a table identifier before "if not exists", eg:

<img width="428" alt="CleanShot 2023-01-29 at 12 41 18@2x" src="https://user-images.githubusercontent.com/125105/215299454-c6171733-b4bf-4cdf-965d-3a63a737b8f8.png">

sqlglot 10.5.10

**Comment by tobymao** [comment]
this may work, but according to snowflake's documentation, this is not valid

https://docs.snowflake.com/en/sql-reference/sql/create-table.html#syntax

going to close this as won't fix since it seems like a bug or undefined behavior in snowflake
