### ISSUE TITLE
WITHIN GROUP and Filter Not Supported

### ISSUE THREAD

**Issue by fmoreira1966** [tobymao/sqlglot#105]
Hi Toby Mao,

In the **sqlglot** latest release (2.1.1)  the Oracle SQL Analytic Function [**LISTAGG**](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/LISTAGG.html#GUID-B6E50D8E-F467-425B-9436-F7F8BF38D466) **is not supported**.

For example with the following SQL Query that works perfectly when executed in ORACLE SQL Developer :

SQL_Query_ = "SELECT CLUSTERNAME, DATETYPE, MIN(CLUSTERDATE) CLUSTERDATE, LISTAGG(APPLICATION, '|') WITHIN GROUP (ORDER BY CLUSTERDATE) AS APPLICATION FROM TYPOLOGY_CLUSTERDATE_T_L WHERE DATETYPE = 'ACCEPTANCE DATE' GROUP BY CLUSTERNAME, DATETYPE"

The result of sqlglot parsing is:

**sqlglot.parse_one(SQL_Query_)**

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\femoreira\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlglot\__init__.py", line 44, in parse_one
    return parse(sql, read=read, **opts)[0]
  File "C:\Users\femoreira\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlglot\__init__.py", line 27, in parse
    return dialect.parse(sql, **opts)
  File "C:\Users\femoreira\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlglot\dialects.py", line 60, in parse
    return self.parser(**opts).parse(self.tokenizer().tokenize(sql), sql)
  File "C:\Users\femoreira\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlglot\parser.py", line 258, in parse
    return self._parse(
  File "C:\Users\femoreira\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlglot\parser.py", line 309, in _parse
    self.check_errors()
  File "C:\Users\femoreira\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlglot\parser.py", line 316, in check_errors
    raise error
sqlglot.errors.ParseError: Expecting BY. Line 1, Col: 100.
  SELECT CLUSTERNAME, DATETYPE, MIN(CLUSTERDATE) CLUSTERDATE, LISTAGG(APPLICATION, '|') WITHIN GROUP ←[4m(←[0mORDER BY CLUSTERDATE) AS APPLICATION FROM TYPOLOGY_CLUSTERDATE_T_L WHERE DATETYPE = 'ACCEPTANCE DATE

It seems that after the keywords WITHIN GROUP sqlglot is expecting the keyword BY, but that is not applicable in this case
 
![image](https://user-images.githubusercontent.com/100311355/165535560-bb843a4c-1ea2-40f0-b9d6-4f706e7cda00.png)

Could you solve this in the earliest possible release?

Thanks in advance.

Best Regards,
F. Moreira

**Comment by tobymao** [comment]
the issue is not the listagg, it’s withingroup. Is that equivalent to a window function?

**Comment by tobymao** [comment]
@fmoreira1966 this is done now

**Comment by fmoreira1966** [comment]
Hi Toby,

Thanks a lot.
I confirm that is working perfectly.

Thanks one again.

Best Regards,
F. Moreira
