### ISSUE TITLE
Parser support for `ON` clause in column def foreign key constraint

### ISSUE THREAD

**Issue by andrewdoss-bit** [tobymao/sqlglot#1106]
It appears that the parser does not support the `ON` clause of a column def foreign key constraint.

```python
sql = "CREATE TABLE foo (bar INT REFERENCES baz (baz_id) ON DELETE CASCADE);"
sqlglot.parse_one(sql)
```

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/anon/sqlglot/sqlglot/__init__.py", line 139, in parse_one
    result = dialect.parse(sql, **opts)
  File "/Users/anon/sqlglot/sqlglot/dialects/dialect.py", line 157, in parse
    return self.parser(**opts).parse(self.tokenizer.tokenize(sql), sql)
  File "/Users/anon/sqlglot/sqlglot/parser.py", line 702, in parse
    return self._parse(
  File "/Users/anon/sqlglot/sqlglot/parser.py", line 765, in _parse
    expressions.append(parse_method(self))
  File "/Users/anon/sqlglot/sqlglot/parser.py", line 895, in _parse_statement
    return self.STATEMENT_PARSERS[self._prev.token_type](self)
  File "/Users/anon/sqlglot/sqlglot/parser.py", line 427, in <lambda>
    TokenType.CREATE: lambda self: self._parse_create(),
  File "/Users/anon/sqlglot/sqlglot/parser.py", line 992, in _parse_create
    this = self._parse_schema(this=table_parts)
  File "/Users/anon/sqlglot/sqlglot/parser.py", line 2705, in _parse_schema
    self._match_r_paren()
  File "/Users/anon/sqlglot/sqlglot/parser.py", line 3608, in _match_r_paren
    self.raise_error("Expecting )")
  File "/Users/anon/sqlglot/sqlglot/parser.py", line 811, in raise_error
    raise error
sqlglot.errors.ParseError: Expecting ). Line 1, Col: 51.
  CREATE TABLE foo (bar INT REFERENCES baz (baz_id) ON DELETE CASCADE);
```

**Comment by andrewdoss-bit** [comment]
Thanks @GeorgeSittas!
