### ISSUE TITLE
Unpivot with a table alias leads to error

### ISSUE THREAD

**Issue by sh0oki** [tobymao/sqlglot#1216]
Hey there, and thanks for a great project!

I noticed there's a syntax error when using a PIVOT / UNPIVOT keyword (this example uses BigQuery syntax): 

```sql
   select 1 from a.b.table1 as t
    unpivot (
        (c3)
        for c4
        in (a,b)
    )
```

Leads to the following parsing error:
```bash
$ python3 -m sqlglot --read bigquery ./unpivot.sql
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/e/.local/lib/python3.8/site-packages/sqlglot/__main__.py", line 69, in <module>
    sqls = sqlglot.transpile(
  File "/home/e/.local/lib/python3.8/site-packages/sqlglot/__init__.py", line 177, in transpile
    for expression in parse(sql, read, error_level=error_level)
  File "/home/e/.local/lib/python3.8/site-packages/sqlglot/__init__.py", line 65, in parse
    return dialect.parse(sql, **opts)
  File "/home/e/.local/lib/python3.8/site-packages/sqlglot/dialects/dialect.py", line 163, in parse
    return self.parser(**opts).parse(self.tokenizer.tokenize(sql), sql)
  File "/home/e/.local/lib/python3.8/site-packages/sqlglot/parser.py", line 745, in parse
    return self._parse(
  File "/home/e/.local/lib/python3.8/site-packages/sqlglot/parser.py", line 811, in _parse
    self.raise_error("Invalid expression / Unexpected token")
  File "/home/e/.local/lib/python3.8/site-packages/sqlglot/parser.py", line 854, in raise_error
    raise error
sqlglot.errors.ParseError: Invalid expression / Unexpected token. Line 1, Col: 1.
  ./unpivot.sql
```

I would love to hear your thoughts about this, or possibly help implementing it, if you could point me in the right direction.

Thanks!

**Comment by GeorgeSittas** [comment]
@sh0oki this issue was a bit tricky. You can take a look at my PR if you're interested to contribute in the future.

**Comment by sh0oki** [comment]
Thanks a bunch!
________________________________
