### ISSUE TITLE
Support COMMENT ON (snowflake)

### ISSUE THREAD

**Issue by tekumara** [tobymao/sqlglot#1239]
```python
>>> sqlglot.parse_one("COMMENT ON TABLE foo IS 'bar'", read="snowflake")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/oliver.mannion/code3/sqlglot/sqlglot/__init__.py", line 147, in parse_one
    result = dialect.parse(sql, **opts)
  File "/Users/oliver.mannion/code3/sqlglot/sqlglot/dialects/dialect.py", line 163, in parse
    return self.parser(**opts).parse(self.tokenizer.tokenize(sql), sql)
  File "/Users/oliver.mannion/code3/sqlglot/sqlglot/parser.py", line 765, in parse
    return self._parse(
  File "/Users/oliver.mannion/code3/sqlglot/sqlglot/parser.py", line 831, in _parse
    self.raise_error("Invalid expression / Unexpected token")
  File "/Users/oliver.mannion/code3/sqlglot/sqlglot/parser.py", line 874, in raise_error
    raise error
sqlglot.errors.ParseError: Invalid expression / Unexpected token. Line 1, Col: 9.
  COMMENT ON TABLE foo IS 'bar'
```

see https://docs.snowflake.com/en/sql-reference/sql/comment

**Comment by tobymao** [comment]
wanna make a PR to add this as a command?

**Comment by tekumara** [comment]
👍 i need the table name and comment value, so I could attempt a PR that does a full parse into a new `exp.Comment` expression?

**Comment by GeorgeSittas** [comment]
Sounds good, just check if there are other dialects that support this statement so that the implementation can be extended to handle them too. For example, I think postgres [supports](https://www.postgresql.org/docs/current/sql-comment.html) it too.

**Comment by tobymao** [comment]
i'm going to add generic support for this as a command for now to close this issue, but happy to help you through your PR
