### ISSUE TITLE
Alter table modify column set tag fails (snowflake)

### ISSUE THREAD

**Issue by tekumara** [tobymao/sqlglot#1251]
```
❯ python -c 'import sqlglot; e = sqlglot.parse_one("ALTER TABLE table1 MODIFY COLUMN name1 SET TAG foo='bar'", read="snowflake"); print(repr(e))'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/tekumara/code3/sqlglot/sqlglot/__init__.py", line 147, in parse_one
    result = dialect.parse(sql, **opts)
  File "/Users/tekumara/code3/sqlglot/sqlglot/dialects/dialect.py", line 163, in parse
    return self.parser(**opts).parse(self.tokenizer.tokenize(sql), sql)
  File "/Users/tekumara/code3/sqlglot/sqlglot/parser.py", line 773, in parse
    return self._parse(
  File "/Users/tekumara/code3/sqlglot/sqlglot/parser.py", line 836, in _parse
    expressions.append(parse_method(self))
  File "/Users/tekumara/code3/sqlglot/sqlglot/parser.py", line 992, in _parse_statement
    return self.STATEMENT_PARSERS[self._prev.token_type](self)
  File "/Users/tekumara/code3/sqlglot/sqlglot/parser.py", line 441, in <lambda>
    TokenType.ALTER: lambda self: self._parse_alter(),
  File "/Users/tekumara/code3/sqlglot/sqlglot/parser.py", line 3754, in _parse_alter
    return self.expression(exp.AlterTable, this=this, exists=exists, actions=actions)
  File "/Users/tekumara/code3/sqlglot/sqlglot/parser.py", line 906, in expression
    self.validate_expression(instance)
  File "/Users/tekumara/code3/sqlglot/sqlglot/parser.py", line 924, in validate_expression
    self.raise_error(error_message)
  File "/Users/tekumara/code3/sqlglot/sqlglot/parser.py", line 882, in raise_error
    raise error
sqlglot.errors.ParseError: Required keyword: 'actions' missing for <class 'sqlglot.expressions.AlterTable'>. Line 1, Col: 20.
  ALTER TABLE table1 MODIFY COLUMN name1 SET TAG foo=bar
```

**Comment by tobymao** [comment]
this example will be easier to implement once #1225 is added because you can just use that parser
