### ISSUE TITLE
Fail to parse Snowflake query

### ISSUE THREAD

**Issue by krzysztof-kwitt** [tobymao/sqlglot#1257]
The following query fails to parse
```sql
SELECT upper("A") FROM ( SELECT "_1" AS "A" FROM ( SELECT $1 AS "_1" FROM  VALUES ('a' :: STRING), ('b' :: STRING)))
```
Error:
```
Traceback (most recent call last):
  File "..../snowflake.py", line 33, in <module>
    pretty_sql_query = sqlglot.transpile(
  File "..../site-packages/sqlglot/__init__.py", line 182, in transpile
    return [
  File "..../site-packages/sqlglot/__init__.py", line 183, in <listcomp>
    Dialect.get_or_raise(write)().generate(expression, **opts)
  File "..../site-packages/sqlglot/dialects/dialect.py", line 171, in generate
    return self.generator(**opts).generate(expression)
  File "..../site-packages/sqlglot/generator.py", line 282, in generate
    sql = self.sql(expression).strip()
  File "..../site-packages/sqlglot/generator.py", line 402, in sql
    sql = getattr(self, exp_handler_name)(expression)
  File "..../site-packages/sqlglot/dialects/snowflake.py", line 347, in select_sql
    values_identifiers = set(
  File "..../site-packages/sqlglot/helper.py", line 352, in flatten
    for value in values:
  File "..../site-packages/sqlglot/dialects/snowflake.py", line 349, in <genexpr>
    v.args.get("alias", exp.Alias()).args.get("columns", [])
AttributeError: 'NoneType' object has no attribute 'args'
```

**Comment by krzysztof-kwitt** [comment]
@tobymao Does your change also support the query below?
```
SELECT column1 FROM (VALUES (1, 'one'), (2, 'two'), (3, 'three'));
```

**Comment by tobymao** [comment]
yes
