### ISSUE TITLE
UNPIVOT expression with subquery alias fails

### ISSUE THREAD

**Issue by ShayYaari** [tobymao/sqlglot#1281]
Hi!

We encounter an issue with trying to parse a BigQuery query that contains an UNPIVOT statement with an aliased sub query.
An example query that fails:

```
SELECT *
FROM (SELECT * FROM db.`my-table`) AS a
 UNPIVOT (
   (column) FOR column_name IN (value1, value2)
)
```

The stack trace we receive is:
```
Traceback (most recent call last):
  File "/Users/shay/Work/sql-lineage/query_analyzer.py", line 22, in __init__
    expressions = sqlglot.parse(self.query, self.dialect)
  File "/Users/shay/.local/share/virtualenvs/sql-lineage-XcD5rJZj/lib/python3.8/site-packages/sqlglot/__init__.py", line 72, in parse
    return dialect.parse(sql, **opts)
  File "/Users/shay/.local/share/virtualenvs/sql-lineage-XcD5rJZj/lib/python3.8/site-packages/sqlglot/dialects/dialect.py", line 163, in parse
    return self.parser(**opts).parse(self.tokenizer.tokenize(sql), sql)
  File "/Users/shay/.local/share/virtualenvs/sql-lineage-XcD5rJZj/lib/python3.8/site-packages/sqlglot/parser.py", line 775, in parse
    return self._parse(
  File "/Users/shay/.local/share/virtualenvs/sql-lineage-XcD5rJZj/lib/python3.8/site-packages/sqlglot/parser.py", line 841, in _parse
    self.raise_error("Invalid expression / Unexpected token")
  File "/Users/shay/.local/share/virtualenvs/sql-lineage-XcD5rJZj/lib/python3.8/site-packages/sqlglot/parser.py", line 884, in raise_error
    raise error
sqlglot.errors.ParseError: Invalid expression / Unexpected token. Line 4, Col: 2.
```

Thank you for your help and your great project!!!

**Comment by tobymao** [comment]
@ShayYaari accordin to the spec the alias has to go after the pivot, is your query correct?

**Comment by ShayYaari** [comment]
@tobymao Yes, I tried to run in a BigQuery playground and it seems to be valid.
