### ISSUE TITLE
ParseError with Oracle SQL containing hint USE_NL with more than 2 tables (version 11.4.1)

### ISSUE THREAD

**Issue by Hal-H2Apps** [tobymao/sqlglot#1327]
`parse_one(sql='SELECT  /*+ USE_NL(A B C) */ A.COL_TEST FROM TABLE_A A, TABLE_B B, TABLE_C C', read='oracle')
`
is returning: 
Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()
           ^^^^^^
  File "<input>", line 1, in <module>
  File "/usr/local/lib/python3.11/site-packages/sqlglot/__init__.py", line 147, in parse_one
    result = dialect.parse(sql, **opts)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlglot/dialects/dialect.py", line 163, in parse
    return self.parser(**opts).parse(self.tokenizer.tokenize(sql), sql)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlglot/parser.py", line 767, in parse
    return self._parse(
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlglot/parser.py", line 830, in _parse
    expressions.append(parse_method(self))
                       ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlglot/parser.py", line 993, in _parse_statement
    expression = self._parse_set_operations(expression) if expression else self._parse_select()
                                                                           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlglot/parser.py", line 1689, in _parse_select
    hint = self._parse_hint()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlglot/parser.py", line 1831, in _parse_hint
    hints = self._parse_csv(self._parse_function)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlglot/parser.py", line 3585, in _parse_csv
    parse_result = parse_method()
                   ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlglot/parser.py", line 2842, in _parse_function
    self._match_r_paren(this)
  File "/usr/local/lib/python3.11/site-packages/sqlglot/parser.py", line 3935, in _match_r_paren
    self.raise_error("Expecting )")
  File "/usr/local/lib/python3.11/site-packages/sqlglot/parser.py", line 876, in raise_error
    raise error
sqlglot.errors.ParseError: Expecting ). Line 1, Col: 24.
  SELECT  /*+ USE_NL(A B C) */ A.COL_TEST FROM TABLE_A A, TABLE_B B, TABLE_C C

Or
`parse_one(sql='SELECT  /*+ USE_NL(A B) */ A.COL_TEST FROM TABLE_A A, TABLE_B B, TABLE_C C', read='oracle')`

works and returns:

(SELECT hint: 
  (HINT expressions: 
    (ANONYMOUS this: USE_NL, expressions: 
      (ALIAS this: 
        (COLUMN this: 
          (IDENTIFIER this: A, quoted: False)), alias: 
        (IDENTIFIER this: B, quoted: False)))), expressions: 
  (COLUMN this: 
    (IDENTIFIER this: COL_TEST, quoted: False), table: 
    (IDENTIFIER this: A, quoted: False)), from: 
  (FROM expressions: 
    (TABLE this: 
      (IDENTIFIER this: TABLE_A, quoted: False), alias: 
      (TABLEALIAS this: 
        (IDENTIFIER this: A, quoted: False))), 
    (TABLE this: 
      (IDENTIFIER this: TABLE_B, quoted: False), alias: 
      (TABLEALIAS this: 
        (IDENTIFIER this: B, quoted: False))), 
    (TABLE this: 
      (IDENTIFIER this: TABLE_C, quoted: False), alias: 
      (TABLEALIAS this: 
        (IDENTIFIER this: C, quoted: False)))))

**Comment by GeorgeSittas** [comment]
Do all hint functions in Oracle contain spaces as separators instead of commas? I'm not familiar with this syntax, can you provide some more information?

**Comment by Hal-H2Apps** [comment]
I'm a beginner with Oracle, but the documentation seems to show that all hint with multiple values are using space to separate values:
https://docs.oracle.com/cd/B12037_01/server.101/b10752/hintsref.htm#29911
```
SELECT /*+ NO_INDEX(employees emp_empid) */ employee_id 
  FROM employees 
  WHERE employee_id > 200; 
```
```
SELECT /*+ NO_INDEX_FFS(items item_order_ix) */ order_id
  FROM order_items items;
```
```
SELECT /*+ LEADING(e j) */ *
    FROM employees e, departments d, job_history j
    WHERE e.department_id = d.department_id
      AND e.hire_date = j.start_date;
```

And you can find more in the link.

**Comment by Hal-H2Apps** [comment]
Also,
You can notice that:
`parse_one(sql='SELECT  /*+ USE_NL(A B) */ A.COL_TEST FROM TABLE_A A, TABLE_B B, TABLE_C C', read='oracle')`
is working even if A and B are separate by space and not comma in the USE_NL hint.

**Comment by Hal-H2Apps** [comment]
Oh gosh. Should I write an issue on that too ? Or will it be fixed when we will be able to use multiple tables inside an hint?
