### ISSUE TITLE
Issue qualifying columns when default table alias is not explicitly specified

### ISSUE THREAD

**Issue by homebase3** [tobymao/sqlglot#1344]
For some sql dialects (e.g. snowflake), it is ok to explicitly specify the table alias for some columns and not others. The unspecified column are assumed to come from the default table. Sqlglot is returning an error for these situations.

Repro result below

### Request
```
optimize(maybe_parse("""   SELECT 
      d.value as data_by_row, 
      uploaded_at
    FROM source,
    LATERAL FLATTEN(INPUT => parse_json(jsontext), outer => true) d""", dialect = 'snowflake')).sql()
```

### Actual result

```
OptimizeError: Unknown table: '' for column 'uploaded_at'
```

### Expected result
```
'SELECT "d"."value" AS "data_by_row", "source"."uploaded_at" AS "uploaded_at" FROM "source" AS "source" CROSS JOIN LATERAL FLATTEN(INPUT => PARSE_JSON("source"."jsontext"), outer => TRUE) AS "d"'
```

**Comment by tobymao** [comment]
are you on the latest sqlglot?

**Comment by GeorgeSittas** [comment]
I can reproduce this with latest:

```python
>>> from sqlglot.optimizer import optimize
>>>
>>> optimize("""SELECT d.value as data_by_row, uploaded_at FROM source""", dialect = 'snowflake').sql()
'SELECT "source"."d"."value" AS "data_by_row", "source"."uploaded_at" AS "uploaded_at" FROM "source" AS "source"'
>>>
>>> optimize("""SELECT d.value as data_by_row, uploaded_at FROM source, LATERAL FLATTEN(INPUT => parse_json(jsontext), outer => true) d""", dialect = 'snowflake').sql()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sqlglot/optimizer/optimizer.py", line 92, in optimize
    expression = rule(expression, **rule_kwargs)
  File "sqlglot/optimizer/qualify_columns.py", line 52, in validate_qualify_columns
    raise OptimizeError(f"Unknown table: '{column.table}' for column '{column}'")
sqlglot.errors.OptimizeError: Unknown table: '' for column 'uploaded_at'
```

Something to do with `LATERAL`, maybe?

**Comment by tobymao** [comment]
it’s impossible for the optimizer to figure this out without a schema. because json could produce anything. so this is working as intended. pass in a schema or qualify your columns.

**Comment by turntable-justin** [comment]
Ok make sense. Will try passing the schema and report back!

**Comment by homebase3** [comment]
So passing the schema helped, but didn't fully resolve the issue. It seems like the issue may be handling a chain of CTEs where the columns are extracted from json and explicitly specified upstream. Here's the full optimize (rather than just the fragment I sent for the representative sample) with the updated error:

```{python}
query = "WITH source AS (SELECT * FROM raw_____bamboohr_____compensation ORDER BY uploaded_at DESC NULLS FIRST LIMIT 1), intermediate AS (SELECT d.value AS data_by_row, uploaded_at FROM source, LATERAL FLATTEN(input => PARSE_JSON(jsontext), outer => TRUE) AS d), renamed AS (SELECT CAST(data_by_row['id'] AS DECIMAL) AS compensation_update_id, CAST(data_by_row['employeeid'] AS DECIMAL) AS employee_id, CAST(data_by_row['startdate'] AS DATE) AS effective_date, CAST(data_by_row['type'] AS VARCHAR) AS compensation_type, CAST(data_by_row['reason'] AS VARCHAR) AS compensation_change_reason, CAST(data_by_row['paidper'] AS VARCHAR) AS pay_rate, TRY_TO_NUMBER(CAST(data_by_row['rate']['value'] AS VARCHAR)) AS compensation_value, CAST(data_by_row['rate']['currency'] AS VARCHAR) AS compensation_currency, uploaded_at FROM intermediate /* filter out specific team member that was brought in as a contractor without a compensation value. */ WHERE (employee_id <> 43749 OR NOT compensation_value IS NULL)) SELECT compensation_update_id, employee_id, effective_date, compensation_type, compensation_change_reason, pay_rate, CASE WHEN compensation_type = 'hourly' THEN compensation_value * 80 ELSE compensation_value END AS compensation_value, compensation_currency, uploaded_at FROM renamed"
schema = {'raw_____bamboohr_____compensation': {'jsontext': 'VARIANT',
  'uploaded_at': 'TIMESTAMP_NTZ'}}

optimize(maybe_parse(query,dialect='snowflake'),dialect='snowflake',schema=schema)
```

And the error returned:
```{text}
n validate_qualify_columns(expression)
     49         if scope.external_columns and not scope.is_correlated_subquery:
     50             column = scope.external_columns[0]
---> 51             raise OptimizeError(f"Unknown table: '{column.table}' for column '{column}'")
     53 if unqualified_columns:
     54     raise OptimizeError(f"Ambiguous columns: {unqualified_columns}")

OptimizeError: Unknown table: '' for column 'employee_id'
`````
