### ISSUE TITLE
Parse errors in Oracle dialect

### ISSUE THREAD

**Issue by deliciouslytyped** [tobymao/sqlglot#1355]
With sqlglot 11.4.4 I get the following two parse errors with their respective expressions:
```
>>> sqlglot.parse('\n\nALTER TABLE s_ut ADD CONSTRAINT s_ut_uq UNIQUE hajo;', sqlglot.dialects.oracle.Oracle)
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2032.0_x64__qbz5n2kfra8p0\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "C:\Users\MyUser\PycharmProjects\flaskProject1\venv\lib\site-packages\sqlglot\__init__.py", line 72, in parse
    return dialect.parse(sql, **opts)
  File "C:\Users\MyUser\PycharmProjects\flaskProject1\venv\lib\site-packages\sqlglot\dialects\dialect.py", line 163, in parse
    return self.parser(**opts).parse(self.tokenize(sql), sql)
  File "C:\Users\MyUser\PycharmProjects\flaskProject1\venv\lib\site-packages\sqlglot\parser.py", line 799, in parse
    return self._parse(
  File "C:\Users\MyUser\PycharmProjects\flaskProject1\venv\lib\site-packages\sqlglot\parser.py", line 862, in _parse
    expressions.append(parse_method(self))
  File "C:\Users\MyUser\PycharmProjects\flaskProject1\venv\lib\site-packages\sqlglot\parser.py", line 1019, in _parse_statement
    return self.STATEMENT_PARSERS[self._prev.token_type](self)
  File "C:\Users\MyUser\PycharmProjects\flaskProject1\venv\lib\site-packages\sqlglot\parser.py", line 462, in <lambda>
    TokenType.ALTER: lambda self: self._parse_alter(),
  File "C:\Users\MyUser\PycharmProjects\flaskProject1\venv\lib\site-packages\sqlglot\parser.py", line 3868, in _parse_alter
    actions=ensure_list(parser(self)),
  File "C:\Users\MyUser\PycharmProjects\flaskProject1\venv\lib\site-packages\sqlglot\parser.py", line 659, in <lambda>
    "ADD": lambda self: self._parse_alter_table_add(),
  File "C:\Users\MyUser\PycharmProjects\flaskProject1\venv\lib\site-packages\sqlglot\parser.py", line 3813, in _parse_alter_table_add
    return self._parse_csv(self._parse_add_constraint)
  File "C:\Users\MyUser\PycharmProjects\flaskProject1\venv\lib\site-packages\sqlglot\parser.py", line 3676, in _parse_csv
    parse_result = parse_method()
  File "C:\Users\MyUser\PycharmProjects\flaskProject1\venv\lib\site-packages\sqlglot\parser.py", line 3807, in _parse_add_constraint
    return self.expression(exp.AddConstraint, this=this, expression=expression)
UnboundLocalError: local variable 'expression' referenced before assignment
```

```
sqlglot.parse('DROP TABLE s_hajo CASCADE CONSTRAINTS;', sqlglot.dialects.oracle.Oracle)
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2032.0_x64__qbz5n2kfra8p0\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "C:\Users\MyUser\PycharmProjects\flaskProject1\venv\lib\site-packages\sqlglot\__init__.py", line 72, in parse
    return dialect.parse(sql, **opts)
  File "C:\Users\MyUser\PycharmProjects\flaskProject1\venv\lib\site-packages\sqlglot\dialects\dialect.py", line 163, in parse
    return self.parser(**opts).parse(self.tokenize(sql), sql)
  File "C:\Users\MyUser\PycharmProjects\flaskProject1\venv\lib\site-packages\sqlglot\parser.py", line 799, in parse
    return self._parse(
  File "C:\Users\MyUser\PycharmProjects\flaskProject1\venv\lib\site-packages\sqlglot\parser.py", line 865, in _parse
    self.raise_error("Invalid expression / Unexpected token")
  File "C:\Users\MyUser\PycharmProjects\flaskProject1\venv\lib\site-packages\sqlglot\parser.py", line 908, in raise_error
    raise error
sqlglot.errors.ParseError: Invalid expression / Unexpected token. Line 1, Col: 27.
  DROP TABLE s_hajo CASCADE CONSTRAINTS;
```

**Comment by tobymao** [comment]
alter table unique constraints will get parsed as a command, not planning to add full parsing for it

**Comment by deliciouslytyped** [comment]
I also started trying to fix this myself, with some success.
How do you decide if you put something in the tokenizer or not? (And where? / how?)
Do you base if off the SQL standards?

Is there a way to extend the TokenType solely in a Dialect? That seems like the most logical way to handle something like this, but since it's an Enum it can't be extended.

**Comment by tobymao** [comment]
you should only put things in the tokenizer when they are very commonly used tokens / reserved keywords.

sqlglot parser and generator is a super dialect, it's very flexible and so it handles many different dialects.

there is no way to extend tokentype that i'm aware of. this is annoying. so we do a lot of text matching these days in the parser with match_text_seq etc.

**Comment by deliciouslytyped** [comment]
That sounds like things would get tangled and it's hard to match up against a reference, but OK, thanks.

So things generally end up in dialect specific code if they somehow end up incompatible with the god-parser?
