### ISSUE TITLE
Parsing Intervals Inside of Case Statements Fails

### ISSUE THREAD

**Issue by srilman** [tobymao/sqlglot#1399]
When parsing the following query:
```
SELECT case when true then interval '15 days' end as wanted_date
```
I see the following error
```
Traceback (most recent call last):
  ...
  File ".../sqlglot/parser.py", line 669, in <lambda>
    TokenType.CASE: lambda self: self._parse_case(),
                                 ^^^^^^^^^^^^^^^^^^
  File ".../sqlglot/parser.py", line 3253, in _parse_case
    self.raise_error("Expected END after CASE", self._prev)
  File ".../sqlglot/parser.py", line 912, in raise_error
    raise error
sqlglot.errors.ParseError: Expected END after CASE. Line ....
```

Debugging the parser, I see that the result of line 3245 returns the following:
```
(INTERVAL this: 
    (LITERAL this: 15 days, is_string: True), unit: 
    (IDENTIFIER this: end, quoted: False))
```
It looks like the parser is including the end keyword in the interval value

**Comment by tobymao** [comment]
thanks for the report
