### ISSUE TITLE
Unsupported expression type for Postgres e-strings

### ISSUE THREAD

**Issue by anyweez** [tobymao/sqlglot#1448]
Hello - thanks for all the work on this wonderful library.

I'm getting an unexpected expression from sqlglot when I attempt to parse a postgres query including [e-strings](https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-CONSTANTS) (Section 4.1.2.2).

```py
sqlglot.transpile("select E'foo' from t1", read='postgres', write='mysql')
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/me/.local/share/virtualenvs/env-VUnKBOhb/lib/python3.10/site-packages/sqlglot/__init__.py", line 182, in transpile
    return [
  File "/Users/me/.local/share/virtualenvs/env-VUnKBOhb/lib/python3.10/site-packages/sqlglot/__init__.py", line 183, in <listcomp>
    Dialect.get_or_raise(write)().generate(expression, **opts)
  File "/Users/me/.local/share/virtualenvs/env-VUnKBOhb/lib/python3.10/site-packages/sqlglot/dialects/dialect.py", line 171, in generate
    return self.generator(**opts).generate(expression)
  File "/Users/me/.local/share/virtualenvs/env-VUnKBOhb/lib/python3.10/site-packages/sqlglot/generator.py", line 319, in generate
    sql = self.sql(expression).strip()
  File "/Users/me/.local/share/virtualenvs/env-VUnKBOhb/lib/python3.10/site-packages/sqlglot/generator.py", line 451, in sql
    sql = getattr(self, exp_handler_name)(expression)
  File "/Users/me/.local/share/virtualenvs/env-VUnKBOhb/lib/python3.10/site-packages/sqlglot/generator.py", line 1423, in select_sql
    expressions = self.expressions(expression)
  File "/Users/me/.local/share/virtualenvs/env-VUnKBOhb/lib/python3.10/site-packages/sqlglot/generator.py", line 2052, in expressions
    sql = self.sql(e, comment=False)
  File "/Users/me/.local/share/virtualenvs/env-VUnKBOhb/lib/python3.10/site-packages/sqlglot/generator.py", line 457, in sql
    raise ValueError(f"Unsupported expression type {expression.__class__.__name__}")
ValueError: Unsupported expression type ByteString
```

In the ideal case since e-strings only apply to string constants, sqlglot would convert the string to an escaped version of the string (according to the write dialect).

**Comment by GeorgeSittas** [comment]
Hey @anyweez, thanks for the issue. Can you show some examples where e-strings are transpiled e.g. to MySQL? Note that they're already supported for postgres in SQLGlot:

```python
>>> import sqlglot
>>> sqlglot.parse_one("E'foo'", "postgres")
(BYTESTRING this: foo)
>>> sqlglot.transpile("E'foo'", "postgres")
["e'foo'"]
```

**Comment by tobymao** [comment]
sqlglot shouldn't crash when this happens. i've fixed that. in terms of the translation, i'm not really sure what to do, i'll accept a PR, if you explain to me what the translation to do, i'll consider implementing it.

**Comment by anyweez** [comment]
Thank you for the quick response! I'll follow up on a separate issue if I'm able to develop a clearer proposal for handling them.
