### ISSUE TITLE
sqlglot 11.5.7 failing to parse `RANK() OVER`

### ISSUE THREAD

**Issue by wmaiouiru** [tobymao/sqlglot#1479]
I am running `sqlglot 11.5.7`

I am trying out sqlglot for unit test on complex queries using python as the executer.  
However, using rank() over, I am getting the following error:

```
Traceback (most recent call last):
  File "/Users/x/sql_sandbox_venv/lib/python3.9/site-packages/sqlglot/executor/python.py", line 46, in execute
    contexts[node] = self.sort(node, context)
  File "/Users/x/sql_sandbox_venv/lib/python3.9/site-packages/sqlglot/executor/python.py", line 312, in sort
    projections = self.generate_tuple(step.projections)
  File "/Users/x/sql_sandbox_venv/lib/python3.9/site-packages/sqlglot/executor/python.py", line 80, in generate_tuple
    return tuple(self.generate(expression) for expression in expressions)
  File "/Users/x/sql_sandbox_venv/lib/python3.9/site-packages/sqlglot/executor/python.py", line 80, in <genexpr>
    return tuple(self.generate(expression) for expression in expressions)
  File "/Users/x/sql_sandbox_venv/lib/python3.9/site-packages/sqlglot/executor/python.py", line 74, in generate
    return compile(sql, sql, "eval", optimize=2)
  File "RANK() OVER (PARTITION BY scope["c"]["customer_id"] ORDER BY ORDERED(scope["o"]["order_date"], True, False))", line 1
    RANK() OVER (PARTITION BY scope["c"]["customer_id"] ORDER BY ORDERED(scope["o"]["order_date"], True, False))
```

Full code:
```
from sqlglot.executor import execute
sql_str = """
SELECT
    o.order_id,
    o.order_date,
    c.customer_name,
    RANK() OVER (PARTITION BY c.customer_id 
        ORDER BY o.order_date DESC) as rank
FROM orders o
JOIN customers c ON o.customer_id = c.customer_id
ORDER BY c.customer_name, o.order_date DESC;
"""

tables = {
    "orders": [
        {"order_id": 1, "order_date": "2022-01-01", "customer_id": 1},
        {"order_id": 2, "order_date": "2022-02-01", "customer_id": 2},
        {"order_id": 3, "order_date": "2022-03-01", "customer_id": 1},
    ],
    "customers": [
        {"customer_name": "name 1", "customer_id": 1},
        {"customer_name": "name 2", "customer_id": 2},
    ],
}
output = execute(sql_str,tables=tables)
print(output)
```

For sanity check, the following works:
```
create table orders (
	order_id varchar( 255 ),
	order_date varchar( 255 ),
	customer_id varchar( 255 )
);
create table customers (
	customer_name varchar( 255 ),
	customer_id varchar( 255 )
);

INSERT INTO orders (order_id, order_date, customer_id)
VALUES ('1', '2020-01-01', 'customer_1');
INSERT INTO orders (order_id, order_date, customer_id)
VALUES ('2', '2021-01-01', 'customer_1');
INSERT INTO customers (customer_name, customer_id)
VALUES ('will', 'customer_1');
```
https://www.db-fiddle.com/f/5DjvwTtaY3HwHiiLRivmZL/0
<img width="1164" alt="Screen Shot 2023-04-25 at 7 28 26 AM" src="https://user-images.githubusercontent.com/517293/234309142-a15b1947-5f11-472e-8a1b-5b428b522731.png">

And my code runs with simple queries:
```
from sqlglot.executor import execute
sql_str = """
SELECT
    o.order_id,
    o.order_date
FROM orders o
"""

tables = {
    "orders": [
        {"order_id": 1, "order_date": "2022-01-01", "customer_id": 1},
        {"order_id": 2, "order_date": "2022-02-01", "customer_id": 2},
        {"order_id": 3, "order_date": "2022-03-01", "customer_id": 1},
    ]
}
output = execute(sql_str,tables=tables)
print(output)
```

Thank you for the help!

**Comment by tobymao** [comment]
window functions are not supported in the executor now. we don’t have immediate plans for this but welcome prs
