### ISSUE TITLE
Uncaught error in parse_one due to parsing of * in object_construct 

### ISSUE THREAD

**Issue by wesleyhamburger-okta** [tobymao/sqlglot#1498]
In v11.60:

The following sql is valid in snowflake SQL:

```
with cte as (
      select 1
 ) 
select
    OBJECT_CONSTRUCT(
        *
    ) as DATA
from cte;
```

However, when passing this input to `parse_one` we receive an error message as follows: 

`list index out of range` 

```
Traceback (most recent call last):
  File "/Users/whamburger/.pyenv/versions/snowflake-pipeline/lib/python3.9/site-packages/sqlglot/__init__.py", line 147, in parse_one
    result = dialect.parse(sql, **opts)
  File "/Users/whamburger/.pyenv/versions/snowflake-pipeline/lib/python3.9/site-packages/sqlglot/dialects/dialect.py", line 163, in parse
    return self.parser(**opts).parse(self.tokenize(sql), sql)
  File "/Users/whamburger/.pyenv/versions/snowflake-pipeline/lib/python3.9/site-packages/sqlglot/parser.py", line 826, in parse
    return self._parse(
  File "/Users/whamburger/.pyenv/versions/snowflake-pipeline/lib/python3.9/site-packages/sqlglot/parser.py", line 889, in _parse
    expressions.append(parse_method(self))
  File "/Users/whamburger/.pyenv/versions/snowflake-pipeline/lib/python3.9/site-packages/sqlglot/parser.py", line 1037, in _parse_statement
    expression = self._parse_set_operations(expression) if expression else self._parse_select()
  File "/Users/whamburger/.pyenv/versions/snowflake-pipeline/lib/python3.9/site-packages/sqlglot/parser.py", line 1746, in _parse_select
    this = self._parse_statement()
  File "/Users/whamburger/.pyenv/versions/snowflake-pipeline/lib/python3.9/site-packages/sqlglot/parser.py", line 1037, in _parse_statement
    expression = self._parse_set_operations(expression) if expression else self._parse_select()
  File "/Users/whamburger/.pyenv/versions/snowflake-pipeline/lib/python3.9/site-packages/sqlglot/parser.py", line 1779, in _parse_select
    expressions = self._parse_csv(self._parse_expression)
  File "/Users/whamburger/.pyenv/versions/snowflake-pipeline/lib/python3.9/site-packages/sqlglot/parser.py", line 3911, in _parse_csv
    parse_result = parse_method()
  File "/Users/whamburger/.pyenv/versions/snowflake-pipeline/lib/python3.9/site-packages/sqlglot/parser.py", line 2577, in _parse_expression
    return self._parse_alias(self._parse_conjunction())
  File "/Users/whamburger/.pyenv/versions/snowflake-pipeline/lib/python3.9/site-packages/sqlglot/parser.py", line 2580, in _parse_conjunction
    return self._parse_tokens(self._parse_equality, self.CONJUNCTION)
  File "/Users/whamburger/.pyenv/versions/snowflake-pipeline/lib/python3.9/site-packages/sqlglot/parser.py", line 3927, in _parse_tokens
    this = parse_method()
  File "/Users/whamburger/.pyenv/versions/snowflake-pipeline/lib/python3.9/site-packages/sqlglot/parser.py", line 2583, in _parse_equality
    return self._parse_tokens(self._parse_comparison, self.EQUALITY)
  File "/Users/whamburger/.pyenv/versions/snowflake-pipeline/lib/python3.9/site-packages/sqlglot/parser.py", line 3927, in _parse_tokens
    this = parse_method()
  File "/Users/whamburger/.pyenv/versions/snowflake-pipeline/lib/python3.9/site-packages/sqlglot/parser.py", line 2586, in _parse_comparison
    return self._parse_tokens(self._parse_range, self.COMPARISON)
  File "/Users/whamburger/.pyenv/versions/snowflake-pipeline/lib/python3.9/site-packages/sqlglot/parser.py", line 3927, in _parse_tokens
    this = parse_method()
  File "/Users/whamburger/.pyenv/versions/snowflake-pipeline/lib/python3.9/site-packages/sqlglot/parser.py", line 2589, in _parse_range
    this = self._parse_bitwise()
  File "/Users/whamburger/.pyenv/versions/snowflake-pipeline/lib/python3.9/site-packages/sqlglot/parser.py", line 2681, in _parse_bitwise
    this = self._parse_term()
  File "/Users/whamburger/.pyenv/versions/snowflake-pipeline/lib/python3.9/site-packages/sqlglot/parser.py", line 2704, in _parse_term
    return self._parse_tokens(self._parse_factor, self.TERM)
  File "/Users/whamburger/.pyenv/versions/snowflake-pipeline/lib/python3.9/site-packages/sqlglot/parser.py", line 3927, in _parse_tokens
    this = parse_method()
  File "/Users/whamburger/.pyenv/versions/snowflake-pipeline/lib/python3.9/site-packages/sqlglot/parser.py", line 2707, in _parse_factor
    return self._parse_tokens(self._parse_unary, self.FACTOR)
  File "/Users/whamburger/.pyenv/versions/snowflake-pipeline/lib/python3.9/site-packages/sqlglot/parser.py", line 3927, in _parse_tokens
    this = parse_method()
  File "/Users/whamburger/.pyenv/versions/snowflake-pipeline/lib/python3.9/site-packages/sqlglot/parser.py", line 2712, in _parse_unary
    return self._parse_at_time_zone(self._parse_type())
  File "/Users/whamburger/.pyenv/versions/snowflake-pipeline/lib/python3.9/site-packages/sqlglot/parser.py", line 2721, in _parse_type
    this = self._parse_column()
  File "/Users/whamburger/.pyenv/versions/snowflake-pipeline/lib/python3.9/site-packages/sqlglot/parser.py", line 2867, in _parse_column
    this = self._parse_field()
  File "/Users/whamburger/.pyenv/versions/snowflake-pipeline/lib/python3.9/site-packages/sqlglot/parser.py", line 2970, in _parse_field
    or self._parse_function()
  File "/Users/whamburger/.pyenv/versions/snowflake-pipeline/lib/python3.9/site-packages/sqlglot/parser.py", line 3027, in _parse_function
    this = function(args)
  File "/Users/whamburger/.pyenv/versions/snowflake-pipeline/lib/python3.9/site-packages/sqlglot/parser.py", line 29, in parse_var_map
    values.append(args[i + 1])
IndexError: list index out of range
```

If I modify this sql to be

```
with cte as (
      select 1
 ) 
select
    OBJECT_CONSTRUCT(
        'test','test'
    ) as DATA
from cte;
```

The error no longer surfaces. It seems like its because of the way the parse_var_map is implemented and how it handles `*` in object_construct. 

https://github.com/tobymao/sqlglot/blob/6d09c813742aa47abeee03277ffcae1a03c1afca/sqlglot/parser.py#L24

AND 

https://github.com/tobymao/sqlglot/blob/6d09c813742aa47abeee03277ffcae1a03c1afca/sqlglot/dialects/snowflake.py#LL205C40-L205C53

**Comment by wesleyhamburger-okta** [comment]
The most recent version 11.60

```
Traceback (most recent call last):
  File "/Users/whamburger/.pyenv/versions/snowflake-pipeline/lib/python3.9/site-packages/sqlglot/__init__.py", line 147, in parse_one
    result = dialect.parse(sql, **opts)
  File "/Users/whamburger/.pyenv/versions/snowflake-pipeline/lib/python3.9/site-packages/sqlglot/dialects/dialect.py", line 163, in parse
    return self.parser(**opts).parse(self.tokenize(sql), sql)
  File "/Users/whamburger/.pyenv/versions/snowflake-pipeline/lib/python3.9/site-packages/sqlglot/parser.py", line 826, in parse
    return self._parse(
  File "/Users/whamburger/.pyenv/versions/snowflake-pipeline/lib/python3.9/site-packages/sqlglot/parser.py", line 889, in _parse
    expressions.append(parse_method(self))
  File "/Users/whamburger/.pyenv/versions/snowflake-pipeline/lib/python3.9/site-packages/sqlglot/parser.py", line 1037, in _parse_statement
    expression = self._parse_set_operations(expression) if expression else self._parse_select()
  File "/Users/whamburger/.pyenv/versions/snowflake-pipeline/lib/python3.9/site-packages/sqlglot/parser.py", line 1746, in _parse_select
    this = self._parse_statement()
  File "/Users/whamburger/.pyenv/versions/snowflake-pipeline/lib/python3.9/site-packages/sqlglot/parser.py", line 1037, in _parse_statement
    expression = self._parse_set_operations(expression) if expression else self._parse_select()
  File "/Users/whamburger/.pyenv/versions/snowflake-pipeline/lib/python3.9/site-packages/sqlglot/parser.py", line 1779, in _parse_select
    expressions = self._parse_csv(self._parse_expression)
  File "/Users/whamburger/.pyenv/versions/snowflake-pipeline/lib/python3.9/site-packages/sqlglot/parser.py", line 3911, in _parse_csv
    parse_result = parse_method()
  File "/Users/whamburger/.pyenv/versions/snowflake-pipeline/lib/python3.9/site-packages/sqlglot/parser.py", line 2577, in _parse_expression
    return self._parse_alias(self._parse_conjunction())
  File "/Users/whamburger/.pyenv/versions/snowflake-pipeline/lib/python3.9/site-packages/sqlglot/parser.py", line 2580, in _parse_conjunction
    return self._parse_tokens(self._parse_equality, self.CONJUNCTION)
  File "/Users/whamburger/.pyenv/versions/snowflake-pipeline/lib/python3.9/site-packages/sqlglot/parser.py", line 3927, in _parse_tokens
    this = parse_method()
  File "/Users/whamburger/.pyenv/versions/snowflake-pipeline/lib/python3.9/site-packages/sqlglot/parser.py", line 2583, in _parse_equality
    return self._parse_tokens(self._parse_comparison, self.EQUALITY)
  File "/Users/whamburger/.pyenv/versions/snowflake-pipeline/lib/python3.9/site-packages/sqlglot/parser.py", line 3927, in _parse_tokens
    this = parse_method()
  File "/Users/whamburger/.pyenv/versions/snowflake-pipeline/lib/python3.9/site-packages/sqlglot/parser.py", line 2586, in _parse_comparison
    return self._parse_tokens(self._parse_range, self.COMPARISON)
  File "/Users/whamburger/.pyenv/versions/snowflake-pipeline/lib/python3.9/site-packages/sqlglot/parser.py", line 3927, in _parse_tokens
    this = parse_method()
  File "/Users/whamburger/.pyenv/versions/snowflake-pipeline/lib/python3.9/site-packages/sqlglot/parser.py", line 2589, in _parse_range
    this = self._parse_bitwise()
  File "/Users/whamburger/.pyenv/versions/snowflake-pipeline/lib/python3.9/site-packages/sqlglot/parser.py", line 2681, in _parse_bitwise
    this = self._parse_term()
  File "/Users/whamburger/.pyenv/versions/snowflake-pipeline/lib/python3.9/site-packages/sqlglot/parser.py", line 2704, in _parse_term
    return self._parse_tokens(self._parse_factor, self.TERM)
  File "/Users/whamburger/.pyenv/versions/snowflake-pipeline/lib/python3.9/site-packages/sqlglot/parser.py", line 3927, in _parse_tokens
    this = parse_method()
  File "/Users/whamburger/.pyenv/versions/snowflake-pipeline/lib/python3.9/site-packages/sqlglot/parser.py", line 2707, in _parse_factor
    return self._parse_tokens(self._parse_unary, self.FACTOR)
  File "/Users/whamburger/.pyenv/versions/snowflake-pipeline/lib/python3.9/site-packages/sqlglot/parser.py", line 3927, in _parse_tokens
    this = parse_method()
  File "/Users/whamburger/.pyenv/versions/snowflake-pipeline/lib/python3.9/site-packages/sqlglot/parser.py", line 2712, in _parse_unary
    return self._parse_at_time_zone(self._parse_type())
  File "/Users/whamburger/.pyenv/versions/snowflake-pipeline/lib/python3.9/site-packages/sqlglot/parser.py", line 2721, in _parse_type
    this = self._parse_column()
  File "/Users/whamburger/.pyenv/versions/snowflake-pipeline/lib/python3.9/site-packages/sqlglot/parser.py", line 2867, in _parse_column
    this = self._parse_field()
  File "/Users/whamburger/.pyenv/versions/snowflake-pipeline/lib/python3.9/site-packages/sqlglot/parser.py", line 2970, in _parse_field
    or self._parse_function()
  File "/Users/whamburger/.pyenv/versions/snowflake-pipeline/lib/python3.9/site-packages/sqlglot/parser.py", line 3027, in _parse_function
    this = function(args)
  File "/Users/whamburger/.pyenv/versions/snowflake-pipeline/lib/python3.9/site-packages/sqlglot/parser.py", line 29, in parse_var_map
    values.append(args[i + 1])
IndexError: list index out of range
```

It seems related to this line here : 

https://github.com/tobymao/sqlglot/blob/6d09c813742aa47abeee03277ffcae1a03c1afca/sqlglot/parser.py#L24 

```
 values.append(args[i + 1])
```

I can't understand what values/keys is exactly but if the arguments expects at least 2 args, then when the argument is a single `*` - we receive this error

**Comment by wesleyhamburger-okta** [comment]
To be honest our use case is currently lazy. We want to take the results of a query and wrap it up into an object along with some other static properties which then get sent somewhere for processing:

```
with cte as (
    select
        event_name,
        count(*)
    from CLOUDTRAIL_LOGS  where 
        event_time >= dateadd('minute', -10, current_timestamp())
    group by 1
)
select
    'STATIC_PROPERTY_INJECTED',
    object_construct(*) as DATA_TO_SEND
from cte;
```

We end up with something like this:

<img width="758" alt="Screenshot 2023-04-28 at 5 12 29 pm" src="https://user-images.githubusercontent.com/110571890/235079687-c4625111-3983-48e3-9b0d-9e4b4654ee16.png">

In the end my hope is that I might wrap any arbitrary sql in a cte and call 

```
select
    'STATIC_PROPERTY_INJECTED',
    object_construct(*) as DATA_TO_SEND
from cte;
```

**Comment by wesleyhamburger-okta** [comment]
Thanks @tobymao and @GeorgeSittas, really excited to see what we are going to build using this library!
