### ISSUE TITLE
SYSDATE is not being handled 

### ISSUE THREAD

**Issue by caiolauro** [tobymao/sqlglot#164]
**Issue Description**
While translating Oracle DDL to Snowflake DDL, the engine was not able to handle SYSDATE oracle function, which should be translated to CURRENT_TIMESTAMP in Snowflake.

**Error Meesage**:
````
$ python3 -i utils/snowflake/schema_change/ddl_translator.py 
Traceback (most recent call last):
  File "utils/snowflake/schema_change/ddl_translator.py", line 6, in <module>
    outputSql = sqlglot.transpile(sqlString, read='oracle', write='snowflake',  pretty=True)
  File "/home/caiolauro/git_engine/adp/adp-utilities/env/lib/python3.8/site-packages/sqlglot/__init__.py", line 90, in transpile
    for expression in parse(sql, read, error_level=error_level)
  File "/home/caiolauro/git_engine/adp/adp-utilities/env/lib/python3.8/site-packages/sqlglot/__init__.py", line 38, in parse
    return dialect.parse(sql, **opts)
  File "/home/caiolauro/git_engine/adp/adp-utilities/env/lib/python3.8/site-packages/sqlglot/dialects.py", line 60, in parse
    return self.parser(**opts).parse(self.tokenizer().tokenize(sql), sql)
  File "/home/caiolauro/git_engine/adp/adp-utilities/env/lib/python3.8/site-packages/sqlglot/parser.py", line 270, in parse
    return self._parse(
  File "/home/caiolauro/git_engine/adp/adp-utilities/env/lib/python3.8/site-packages/sqlglot/parser.py", line 322, in _parse
    self.check_errors()
  File "/home/caiolauro/git_engine/adp/adp-utilities/env/lib/python3.8/site-packages/sqlglot/parser.py", line 329, in check_errors
    raise error
sqlglot.errors.ParseError: Expecting ). Line 20, Col: 27.
  T_DATE" DATE,
        "END_DATE" DATE,
        "AMT" NUMBER(14,2),
        "CNT" NUMBER(18,0),
        "CHANGE_TS" DATE DEFAULT SYSDATE,
        "CHANGE_TYPE" CHAR(1),
        "USER_NAME" VARCHAR2(30)
   ) ;`
```

**Comment by tobymao** [comment]
low priority issue as i don't really support oracle, especially not create table transpilations

**Comment by tobymao** [comment]
closing as wont fix for now
