### ISSUE TITLE
lineage of joins with a using clause fails with an OptimizeError

### ISSUE THREAD

**Issue by hsheth2** [tobymao/sqlglot#1711]
It looks like the `using` clause is not being expanded properly when the list of columns in `my-calendar-ref` is listed out.

```python
import sqlglot.lineage

sqlglot.lineage.lineage(
    "account_code",
    sql="""
with cal as (
    select cal_month_start,	cal_month_end
    from `my-calendar-ref`
)
select cal.cal_month_start,
    a.account_code, a.account_name,
    s.subscription_id
from `accounts` a
cross join cal
join `subscriptions` s using (account_code)
""",
    dialect="bigquery",
)
```

Yields the following error:
```
Traceback (most recent call last):
  File "/Users/hsheth/projects/experimental/hsheth/sql-parsing/join-optimize.py", line 3, in <module>
    sqlglot.lineage.lineage(
  File "/Users/hsheth/projects/experimental/hsheth/sql-parsing/venv/lib/python3.10/site-packages/sqlglot/lineage.py", line 72, in lineage
    optimized = optimize(expression, schema=schema, rules=rules)
  File "/Users/hsheth/projects/experimental/hsheth/sql-parsing/venv/lib/python3.10/site-packages/sqlglot/optimizer/optimizer.py", line 89, in optimize
    expression = rule(expression, **rule_kwargs)
  File "/Users/hsheth/projects/experimental/hsheth/sql-parsing/venv/lib/python3.10/site-packages/sqlglot/optimizer/qualify_columns.py", line 49, in qualify_columns
    _qualify_columns(scope, resolver)
  File "/Users/hsheth/projects/experimental/hsheth/sql-parsing/venv/lib/python3.10/site-packages/sqlglot/optimizer/qualify_columns.py", line 251, in _qualify_columns
    raise OptimizeError(f"Unknown column: {column_name}")
sqlglot.errors.OptimizeError: Unknown column: account_code
```

**Comment by tobymao** [comment]
you need to pass in the schema.

the optimizer only works if all columns are unambiguous

```python
from sqlglot.optimizer import optimize

q = optimize(
    """
    with cal as (
    select cal_month_start,	cal_month_end
    from `my-calendar-ref`
)
select cal.cal_month_start,
    a.account_code, 
    a.account_name,
    s.subscription_id
from `accounts` a
cross join cal
join `subscriptions` s using (account_code)
""",
    schema={
        "accounts": {
            "account_code": "int",
            "account_name": "int",
        },
        "subscriptions": {
            "account_code": "int",
            "subscription_id": "int",
        },
        "my-calendar-ref": {
            "cal_month_start": "int",
            "cal_month_end": "int",
        },
    },
    dialect="bigquery",
    
)

print(q.sql(pretty=True))```

**Comment by hsheth2** [comment]
@tobymao in this case, the SQL isn't really ambiguous. We know exactly what columns are available in `cal`, and hence should be able to determine that `account_code` does not come from the cross join on `cal` and therefore must come from `accounts`.

**Comment by tobymao** [comment]
that maybe true, but it's not in scope and i don't plan to implement that when you can provide an explicit schema
