### ISSUE TITLE
Decimal numbers ending with a `.` and a closing parenthesis throw a ParseError in Snowflake ❄️ 

### ISSUE THREAD

**Issue by florian-ernst-alan** [tobymao/sqlglot#1764]
The following query works in Snowflake:
```sql
SELECT (5.)
```

But throws a ParseError when parsed:
```py
parse_one("SELECT (5.)", read=dialects.Snowflake)
```

<details><summary>Here is the traceback</summary>
<p>

```py
Traceback (most recent call last):
  File "/Users/florian.ernst/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/231.9011.38/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 1, in <module>
  File "/Users/florian.ernst/Alan/alan-jobs/env/lib/python3.10/site-packages/sqlglot/__init__.py", line 158, in parse_one
    result = dialect.parse(sql, **opts)
  File "/Users/florian.ernst/Alan/alan-jobs/env/lib/python3.10/site-packages/sqlglot/dialects/dialect.py", line 217, in parse
    return self.parser(**opts).parse(self.tokenize(sql), sql)
  File "/Users/florian.ernst/Alan/alan-jobs/env/lib/python3.10/site-packages/sqlglot/parser.py", line 856, in parse
    return self._parse(
  File "/Users/florian.ernst/Alan/alan-jobs/env/lib/python3.10/site-packages/sqlglot/parser.py", line 922, in _parse
    expressions.append(parse_method(self))
  File "/Users/florian.ernst/Alan/alan-jobs/env/lib/python3.10/site-packages/sqlglot/parser.py", line 1112, in _parse_statement
    expression = self._parse_set_operations(expression) if expression else self._parse_select()
  File "/Users/florian.ernst/Alan/alan-jobs/env/lib/python3.10/site-packages/sqlglot/parser.py", line 1877, in _parse_select
    expressions = self._parse_csv(self._parse_expression)
  File "/Users/florian.ernst/Alan/alan-jobs/env/lib/python3.10/site-packages/sqlglot/parser.py", line 4135, in _parse_csv
    parse_result = parse_method()
  File "/Users/florian.ernst/Alan/alan-jobs/env/lib/python3.10/site-packages/sqlglot/parser.py", line 2722, in _parse_expression
    return self._parse_alias(self._parse_conjunction())
  File "/Users/florian.ernst/Alan/alan-jobs/env/lib/python3.10/site-packages/sqlglot/parser.py", line 2725, in _parse_conjunction
    return self._parse_tokens(self._parse_equality, self.CONJUNCTION)
  File "/Users/florian.ernst/Alan/alan-jobs/env/lib/python3.10/site-packages/sqlglot/parser.py", line 4149, in _parse_tokens
    this = parse_method()
  File "/Users/florian.ernst/Alan/alan-jobs/env/lib/python3.10/site-packages/sqlglot/parser.py", line 2728, in _parse_equality
    return self._parse_tokens(self._parse_comparison, self.EQUALITY)
  File "/Users/florian.ernst/Alan/alan-jobs/env/lib/python3.10/site-packages/sqlglot/parser.py", line 4149, in _parse_tokens
    this = parse_method()
  File "/Users/florian.ernst/Alan/alan-jobs/env/lib/python3.10/site-packages/sqlglot/parser.py", line 2731, in _parse_comparison
    return self._parse_tokens(self._parse_range, self.COMPARISON)
  File "/Users/florian.ernst/Alan/alan-jobs/env/lib/python3.10/site-packages/sqlglot/parser.py", line 4149, in _parse_tokens
    this = parse_method()
  File "/Users/florian.ernst/Alan/alan-jobs/env/lib/python3.10/site-packages/sqlglot/parser.py", line 2734, in _parse_range
    this = self._parse_bitwise()
  File "/Users/florian.ernst/Alan/alan-jobs/env/lib/python3.10/site-packages/sqlglot/parser.py", line 2831, in _parse_bitwise
    this = self._parse_term()
  File "/Users/florian.ernst/Alan/alan-jobs/env/lib/python3.10/site-packages/sqlglot/parser.py", line 2852, in _parse_term
    return self._parse_tokens(self._parse_factor, self.TERM)
  File "/Users/florian.ernst/Alan/alan-jobs/env/lib/python3.10/site-packages/sqlglot/parser.py", line 4149, in _parse_tokens
    this = parse_method()
  File "/Users/florian.ernst/Alan/alan-jobs/env/lib/python3.10/site-packages/sqlglot/parser.py", line 2855, in _parse_factor
    return self._parse_tokens(self._parse_unary, self.FACTOR)
  File "/Users/florian.ernst/Alan/alan-jobs/env/lib/python3.10/site-packages/sqlglot/parser.py", line 4149, in _parse_tokens
    this = parse_method()
  File "/Users/florian.ernst/Alan/alan-jobs/env/lib/python3.10/site-packages/sqlglot/parser.py", line 2860, in _parse_unary
    return self._parse_at_time_zone(self._parse_type())
  File "/Users/florian.ernst/Alan/alan-jobs/env/lib/python3.10/site-packages/sqlglot/parser.py", line 2869, in _parse_type
    this = self._parse_column()
  File "/Users/florian.ernst/Alan/alan-jobs/env/lib/python3.10/site-packages/sqlglot/parser.py", line 3020, in _parse_column
    this = self._parse_field()
  File "/Users/florian.ernst/Alan/alan-jobs/env/lib/python3.10/site-packages/sqlglot/parser.py", line 3123, in _parse_field
    self._parse_primary()
  File "/Users/florian.ernst/Alan/alan-jobs/env/lib/python3.10/site-packages/sqlglot/parser.py", line 3095, in _parse_primary
    expressions = self._parse_csv(self._parse_expression)
  File "/Users/florian.ernst/Alan/alan-jobs/env/lib/python3.10/site-packages/sqlglot/parser.py", line 4135, in _parse_csv
    parse_result = parse_method()
  File "/Users/florian.ernst/Alan/alan-jobs/env/lib/python3.10/site-packages/sqlglot/parser.py", line 2722, in _parse_expression
    return self._parse_alias(self._parse_conjunction())
  File "/Users/florian.ernst/Alan/alan-jobs/env/lib/python3.10/site-packages/sqlglot/parser.py", line 2725, in _parse_conjunction
    return self._parse_tokens(self._parse_equality, self.CONJUNCTION)
  File "/Users/florian.ernst/Alan/alan-jobs/env/lib/python3.10/site-packages/sqlglot/parser.py", line 4149, in _parse_tokens
    this = parse_method()
  File "/Users/florian.ernst/Alan/alan-jobs/env/lib/python3.10/site-packages/sqlglot/parser.py", line 2728, in _parse_equality
    return self._parse_tokens(self._parse_comparison, self.EQUALITY)
  File "/Users/florian.ernst/Alan/alan-jobs/env/lib/python3.10/site-packages/sqlglot/parser.py", line 4149, in _parse_tokens
    this = parse_method()
  File "/Users/florian.ernst/Alan/alan-jobs/env/lib/python3.10/site-packages/sqlglot/parser.py", line 2731, in _parse_comparison
    return self._parse_tokens(self._parse_range, self.COMPARISON)
  File "/Users/florian.ernst/Alan/alan-jobs/env/lib/python3.10/site-packages/sqlglot/parser.py", line 4149, in _parse_tokens
    this = parse_method()
  File "/Users/florian.ernst/Alan/alan-jobs/env/lib/python3.10/site-packages/sqlglot/parser.py", line 2734, in _parse_range
    this = self._parse_bitwise()
  File "/Users/florian.ernst/Alan/alan-jobs/env/lib/python3.10/site-packages/sqlglot/parser.py", line 2831, in _parse_bitwise
    this = self._parse_term()
  File "/Users/florian.ernst/Alan/alan-jobs/env/lib/python3.10/site-packages/sqlglot/parser.py", line 2852, in _parse_term
    return self._parse_tokens(self._parse_factor, self.TERM)
  File "/Users/florian.ernst/Alan/alan-jobs/env/lib/python3.10/site-packages/sqlglot/parser.py", line 4149, in _parse_tokens
    this = parse_method()
  File "/Users/florian.ernst/Alan/alan-jobs/env/lib/python3.10/site-packages/sqlglot/parser.py", line 2855, in _parse_factor
    return self._parse_tokens(self._parse_unary, self.FACTOR)
  File "/Users/florian.ernst/Alan/alan-jobs/env/lib/python3.10/site-packages/sqlglot/parser.py", line 4149, in _parse_tokens
    this = parse_method()
  File "/Users/florian.ernst/Alan/alan-jobs/env/lib/python3.10/site-packages/sqlglot/parser.py", line 2860, in _parse_unary
    return self._parse_at_time_zone(self._parse_type())
  File "/Users/florian.ernst/Alan/alan-jobs/env/lib/python3.10/site-packages/sqlglot/parser.py", line 2869, in _parse_type
    this = self._parse_column()
  File "/Users/florian.ernst/Alan/alan-jobs/env/lib/python3.10/site-packages/sqlglot/parser.py", line 3025, in _parse_column
    return self._parse_column_ops(this)
  File "/Users/florian.ernst/Alan/alan-jobs/env/lib/python3.10/site-packages/sqlglot/parser.py", line 3058, in _parse_column_ops
    this = self.expression(
  File "/Users/florian.ernst/Alan/alan-jobs/env/lib/python3.10/site-packages/sqlglot/parser.py", line 986, in expression
    return self.validate_expression(instance)
  File "/Users/florian.ernst/Alan/alan-jobs/env/lib/python3.10/site-packages/sqlglot/parser.py", line 1006, in validate_expression
    self.raise_error(error_message)
  File "/Users/florian.ernst/Alan/alan-jobs/env/lib/python3.10/site-packages/sqlglot/parser.py", line 966, in raise_error
    raise error
sqlglot.errors.ParseError: Required keyword: 'this' missing for <class 'sqlglot.expressions.Column'>. Line 1, Col: 11.
  SELECT (5.)
```

</p>
</details>

**Comment by GeorgeSittas** [comment]
Thanks for the reports, I'll have a look.

**Comment by florian-ernst-alan** [comment]
Thanks 🙂 I'm thinking of switching my team's SQL parser to SQL Glot (way faster & user-friendly than `sqlfluff` / `sql_metadata`), so I ran it on all our SQL queries to see if there was some blockers. No rush needed of course.

Btw you didn't put `sql_metadata` in your benchmark (understandable, as they have only ~500 github stars) - just know it's an order of magnitude slower than `sqlglob`! 😄

**Comment by tobymao** [comment]
sql_metadata just uses sqlparse doesn't it?
