### ISSUE TITLE
Optimizer doesn't recognized original table name when use alias.

### ISSUE THREAD

**Issue by stonyw** [tobymao/sqlglot#1823]
I got error : sqlglot.errors.OptimizeError: Column 'x.c' could not be resolved for table: 'x' when execute sql: 'select T1.a , T2.a , T1.b , T2.d from x as T1 join y as T2 on x.c == y.id;'

Here notice the difference between  'on x.c == y.id' and 'T1.c == T2.id.

```python
import unittest

from sqlglot.executor import execute


class TestExecutor(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        pass

    @classmethod
    def tearDownClass(cls):
        pass

    def test_execute_callable(self):
        tables = {
            "x": [
                {"a": "a1", "b": "b1", "c": "c1"},
                {"a": "a2", "b": "b2", "c": "c2"},
                {"a": "a3", "b": "b3", "c": "c3"},
            ],
            "y": [
                {"id": "c1", "a": "aa1", "d": "d1"},
                {"id": "c3", "a": "aa2", "d": "d2"},
                {"id": "c5", "a": "aa3", "d": "d3"},
            ]
        }
        schema = {
            "x": {
                "a": "VARCHAR",
                "b": "VARCHAR",
                "c": "VARCHAR",
            },
            "y": {
                "id": "VARCHAR",
                "a": "VARCHAR",
                "d": "VARCHAR",
            },
        }

        for sql, cols, rows in [
            ('select x.a , y.a , b , d from x join y on c == id;', ["a", "a", "b", "d"], [('a1', 'aa1', 'b1', 'd1'), ('a3', 'aa2', 'b3', 'd2')]),  # PASS
            ('select x.a , y.a , x.b , y.d from x join y on x.c == y.id;', ["a", "a", "b", "d"], [('a1', 'aa1', 'b1', 'd1'), ('a3', 'aa2', 'b3', 'd2')]),  # PASS
            ('select T1.a , T2.a , T1.b , T2.d from x as T1 join y as T2 on T1.c == T2.id;', ["a", "a", "b", "d"], [('a1', 'aa1', 'b1', 'd1'), ('a3', 'aa2', 'b3', 'd2')]),  # PASS
            ('select T1.a , T2.a , T1.b , T2.d from x as T1 join y as T2 on x.c == y.id;', ["a", "a", "b", "d"], [('a1', 'aa1', 'b1', 'd1'), ('a3', 'aa2', 'b3', 'd2')]),  # FAILED
        ]:
            with self.subTest(sql):
                result = execute(sql, schema=schema, tables=tables)
                self.assertEqual(result.columns, tuple(cols))
                self.assertEqual(result.rows, rows)
```

Error logs:
```
SubTest error: Traceback (most recent call last):
  File "/usr/.../python3.11/unittest/case.py", line 57, in testPartExecutor
    yield
  File "/usr/.../python3.11/unittest/case.py", line 538, in subTest
    yield
  File "/Users/..app../src/tr/dbtool/test_executor.py", line 51, in test_execute_callable
    result = execute(sql, schema=schema, tables=tables)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/.../python3.11/site-packages/sqlglot/executor/__init__.py", line 72, in execute
    expression = optimize(sql, schema, leave_tables_isolated=True, dialect=read)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/.../python3.11/site-packages/sqlglot/optimizer/optimizer.py", line 92, in optimize
    expression = rule(expression, **rule_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/.../python3.11/site-packages/sqlglot/optimizer/qualify.py", line 78, in qualify
    validate_qualify_columns_func(expression)
  File "/Users/.../python3.11/site-packages/sqlglot/optimizer/qualify_columns.py", line 73, in validate_qualify_columns
    raise OptimizeError(
sqlglot.errors.OptimizeError: Column 'x.c' could not be resolved for table: 'x'
```

Possible cause:
Optimizer searches alias only when a table has an alias.

**Comment by GeorgeSittas** [comment]
What dialect is this? The example seems non-standard; postgres will reject a similar query:

```
georgesittas=# with x as (select 1 as a), y as (select 1 as b) select * from x as t1 join y as t2 on x.a = y.a;
ERROR:  invalid reference to FROM-clause entry for table "x"
LINE 1: ...ect 1 as b) select * from x as t1 join y as t2 on x.a = y.a;
                                                             ^
HINT:  Perhaps you meant to reference the table alias "t1".
```

**Comment by tobymao** [comment]
tried this on postgres and it doesn't work

```sql
select games.id
from games g
```

closing
