### ISSUE TITLE
sqlglot.errors.ExecuteError: Step 'Scan: y (4461268368)' failed: 'NoneType' object has no attribute 'range_reader'

### ISSUE THREAD

**Issue by stonyw** [tobymao/sqlglot#1827]
When table's name has capital letters, the executor fails to find the table in Scan step. Even the reference in SQL query is in capital.

```python
import unittest

from sqlglot.executor import execute

class TestExecutor(unittest.TestCase):
    def test_range(self):
        tables = {
            "x": [
                {"a": "1"},
            ],
            "Y": [     # Capital Y
                {"b": "2"},
            ],
        }
        schema = {
            "x": {"a": "text"},
            "Y": {"b": "text"}
        }

        for sql, cols, rows in [
            ('SELECT a FROM x', ['a'], [('1',)]),  # PASSED
            ('SELECT b FROM Y', ['b'], [('2',)]),  # FAILED
        ]:
            with self.subTest(sql):
                result = execute(sql, schema=schema, tables=tables)
                self.assertEqual(result.columns, tuple(cols))
                self.assertEqual(result.rows, rows)
```

```
SubTest error: Traceback (most recent call last):
  File "/Users/stony/.local/share/virtualenvs/langchain-app-iCktjJ6b/lib/python3.11/site-packages/sqlglot/executor/python.py", line 40, in execute
    contexts[node] = self.scan(node, context)
                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stony/.local/share/virtualenvs/langchain-app-iCktjJ6b/lib/python3.11/site-packages/sqlglot/executor/python.py", line 107, in scan
    context, table_iter = self.scan_table(step)
                          ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stony/.local/share/virtualenvs/langchain-app-iCktjJ6b/lib/python3.11/site-packages/sqlglot/executor/python.py", line 135, in scan_table
    context = self.context({step.source.alias_or_name: table})
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stony/.local/share/virtualenvs/langchain-app-iCktjJ6b/lib/python3.11/site-packages/sqlglot/executor/python.py", line 83, in context
    return Context(tables, env=self.env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stony/.local/share/virtualenvs/langchain-app-iCktjJ6b/lib/python3.11/site-packages/sqlglot/executor/context.py", line 30, in __init__
    self.range_readers = {name: table.range_reader for name, table in self.tables.items()}
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stony/.local/share/virtualenvs/langchain-app-iCktjJ6b/lib/python3.11/site-packages/sqlglot/executor/context.py", line 30, in <dictcomp>
    self.range_readers = {name: table.range_reader for name, table in self.tables.items()}
                                ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'range_reader'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 57, in testPartExecutor
    yield
  File "/usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 538, in subTest
    yield
  File "/Users/stony/git/gpt/langchain-app/src/tr/dbtool/test_executor.py", line 279, in test_range
    result = execute(sql, schema=schema, tables=tables)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stony/.local/share/virtualenvs/langchain-app-iCktjJ6b/lib/python3.11/site-packages/sqlglot/executor/__init__.py", line 82, in execute
    result = PythonExecutor(tables=tables_).execute(plan)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stony/.local/share/virtualenvs/langchain-app-iCktjJ6b/lib/python3.11/site-packages/sqlglot/executor/python.py", line 63, in execute
    raise ExecuteError(f"Step '{node.id}' failed: {e}") from e
sqlglot.errors.ExecuteError: Step 'Scan: y (4461268368)' failed: 'NoneType' object has no attribute 'range_reader'

```

Walkaround: keep table name in lower case when use as tables/schema.

**Comment by tobymao** [comment]
The tables need to be lower cased because everything is case insensitive, so change the input table to be "y". If you want it to be upper case for some reason, you need to quote  the upper case names in the schema.
