### ISSUE TITLE
Incorrect parsing of identifiers when double quotes used in query in snowflake

### ISSUE THREAD

**Issue by wezham** [tobymao/sqlglot#1852]
In the snowflake documentation you can see that snowflake supports using double quotes in identifiers in SQL statements. 

https://docs.snowflake.com/en/sql-reference/identifiers-syntax#label-identifier-casing

However, when trying to qualify a statement that includes double quoted columns, the quoted identifier fails to resolve. 

```python
from sqlglot import parse_one
from sqlglot.optimizer.qualify import qualify


table_schema = {"sample_table": {"created_at": "timestamp_tz"}}
sql_query = "SELECT \"created_at\" from sample_table;"
expression_ = qualify(
    parse_one(sql_query),
    dialect="snowflake",
    qualify_columns=True,
    validate_qualify_columns=True,
    schema=table_schema,
)
```

Raises

```
Traceback (most recent call last):
  File "/Users/wesley.hamburger/Library/Application Support/JetBrains/PyCharmCE2023.1/scratches/scratch_68.py", line 7, in <module>
    expression_ = qualify(
  File "/Users/wesley.hamburger/.pyenv/versions/snowflake-pipe/lib/python3.10/site-packages/sqlglot/optimizer/qualify.py", line 78, in qualify
    validate_qualify_columns_func(expression)
  File "/Users/wesley.hamburger/.pyenv/versions/snowflake-pipe/lib/python3.10/site-packages/sqlglot/optimizer/qualify_columns.py", line 73, in validate_qualify_columns
    raise OptimizeError(
sqlglot.errors.OptimizeError: Column '"created_at"' could not be resolved
```

**Comment by tobymao** [comment]
you have the incorrect schema. in snowflake everything is upper case unless it's quoted. since you quoted created_at it is now case sensitive lower, so you must also lower case quote in your schema

```python
from sqlglot import parse_one
from sqlglot.optimizer.qualify import qualify


table_schema = {"sample_table": {'"created_at"': "timestamp_tz"}}
sql_query = """SELECT "created_at" from sample_table;"""
expression_ = qualify(
    parse_one(sql_query, read="snowflake"),
    dialect="snowflake",
    qualify_columns=True,
    validate_qualify_columns=True,
    schema=table_schema,
)
```

**Comment by wezham** [comment]
Okay I can see in the docs 

https://docs.snowflake.com/en/sql-reference/identifiers-syntax#label-identifier-casing

> When an identifier is double-quoted, it is stored and resolved exactly as entered, including case.

Which makes me wonder how this has not been breaking in my environment .. thanks anyhow
