### ISSUE TITLE
Unable to parse spark sql refresh statement

### ISSUE THREAD

**Issue by zjffdu** [tobymao/sqlglot#1922]
**Before you file an issue**
- Make sure you specify the "read" dialect eg. parse_one(sql, read="spark")
- Check if the issue still exists on main 

**Fully reproducible code snippet**
```
    parse_one("""
    refresh table prs_t.mh_app_dwnld_txn_attr;
    """, dialect = Dialects.SPARK)
```

Error message:
```
Traceback (most recent call last):
  File "/Users/jianfezhang/github/sqlglot/tests/my_test.py", line 130, in <module>
    parse_one("""
  File "/Users/jianfezhang/github/sqlglot/sqlglot/__init__.py", line 122, in parse_one
    result = dialect.parse(sql, **opts)
  File "/Users/jianfezhang/github/sqlglot/sqlglot/dialects/dialect.py", line 278, in parse
    return self.parser(**opts).parse(self.tokenize(sql), sql)
  File "/Users/jianfezhang/github/sqlglot/sqlglot/parser.py", line 877, in parse
    return self._parse(
  File "/Users/jianfezhang/github/sqlglot/sqlglot/parser.py", line 946, in _parse
    self.raise_error("Invalid expression / Unexpected token")
  File "/Users/jianfezhang/github/sqlglot/sqlglot/parser.py", line 987, in raise_error
    raise error
sqlglot.errors.ParseError: Invalid expression / Unexpected token. Line 2, Col: 23.
  
    refresh table prs_t.mh_app_dwnld_txn_attr;
```
**Official Documentation**
Please include links to official SQL documentation related to your issue.

**Comment by tobymao** [comment]
https://github.com/tobymao/sqlglot/commit/048b9bcd023e6dd6a47fff1536d66e1ca94991f4
