### ISSUE TITLE
'@@' not supported when parsing with postgres dialect

### ISSUE THREAD

**Issue by cmilhaupt** [tobymao/sqlglot#2066]
I saw in https://github.com/tobymao/sqlglot/issues/1290 that transpiling of full-text search queries isn't in the scope of sqlglot, but is parsing queries with postgres-specific full-text search tokens? 

Observed bevhaior:
```
$ python3 --version
Python 3.11.3
$ python3 -c "import sqlglot; print(sqlglot.__version__)"
17.14.2
$ python3 -m sqlglot --read postgres --parse "SELECT title FROM pgweb WHERE to_tsvector('english', body) @@ to_tsquery('english', 'friend');"
...
sqlglot.errors.ParseError: Invalid expression / Unexpected token. Line 1, Col: 60.
  SELECT title FROM pgweb WHERE to_tsvector('english', body) @@ to_tsquery('english', 'friend');
```

Ideally I'd also expect to be able to 
```
sqlglot.parse_one("SELECT title FROM pgweb WHERE author LIKE '%Smith%';").where("to_tsvector('english', body) @@ to_tsquery('english', 'friend')").sql()
```
or 
```
sqlglot.parse_one("SELECT title FROM pgweb WHERE to_tsvector('english', body) @@ to_tsquery('english', 'friend')").find(exp.Where).sql(
```

If this isn't in scope for this project please feel free to close!

**Comment by cmilhaupt** [comment]
Thanks for the quick fix! Looks like the first examples works but the second example is throwing this error:
```
>>> sqlglot.parse_one("SELECT title FROM pgweb WHERE author LIKE '%Smith%';").where("to_tsvector('english', body
) @@ to_tsquery('english', 'friend')").sql()
Traceback (most recent call last):
  File "/tmp/env/lib/python3.11/site-packages/sqlglot/parser.py", line 930, in parse_into
    return self._parse(parser, raw_tokens, sql)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/env/lib/python3.11/site-packages/sqlglot/parser.py", line 969, in _parse
    self.raise_error("Invalid expression / Unexpected token")
  File "/tmp/env/lib/python3.11/site-packages/sqlglot/parser.py", line 1010, in raise_error
    raise error
sqlglot.errors.ParseError: Invalid expression / Unexpected token. Line 1, Col: 30.
  to_tsvector('english', body) @@ to_tsquery('english', 'friend')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/env/lib/python3.11/site-packages/sqlglot/expressions.py", line 3034, in where
    return _apply_conjunction_builder(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/env/lib/python3.11/site-packages/sqlglot/expressions.py", line 5055, in _apply_conjunction_builder
    node = and_(*expressions, dialect=dialect, copy=copy, **opts)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/env/lib/python3.11/site-packages/sqlglot/expressions.py", line 5421, in and_
    return t.cast(Condition, _combine(expressions, And, dialect, copy=copy, **opts))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/env/lib/python3.11/site-packages/sqlglot/expressions.py", line 5092, in _combine
    conditions = [
                 ^
  File "/tmp/env/lib/python3.11/site-packages/sqlglot/expressions.py", line 5093, in <listcomp>
    condition(expression, dialect=dialect, copy=copy, **opts)
  File "/tmp/env/lib/python3.11/site-packages/sqlglot/expressions.py", line 5392, in condition
    return maybe_parse(
           ^^^^^^^^^^^^
  File "/tmp/env/lib/python3.11/site-packages/sqlglot/expressions.py", line 4917, in maybe_parse
    return sqlglot.parse_one(sql, read=dialect, into=into, **opts)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/env/lib/python3.11/site-packages/sqlglot/__init__.py", line 123, in parse_one
    result = dialect.parse_into(into, sql, **opts)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/env/lib/python3.11/site-packages/sqlglot/dialects/dialect.py", line 294, in parse_into
    return self.parser(**opts).parse_into(expression_type, self.tokenize(sql), sql)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/env/lib/python3.11/site-packages/sqlglot/parser.py", line 935, in parse_into
    raise ParseError(
sqlglot.errors.ParseError: Failed to parse 'to_tsvector('english', body) @@ to_tsquery('english', 'friend')' int
o <class 'sqlglot.expressions.Condition'>
```
and the third example this:
```
sqlglot.parse_one("SELECT title FROM pgweb WHERE to_tsvector('english', body) @@ to_tsquery('english', 'friend')").find(exp.Where).sql()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/env/lib/python3.11/site-packages/sqlglot/__init__.py", line 125, in parse_one
    result = dialect.parse(sql, **opts)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/env/lib/python3.11/site-packages/sqlglot/dialects/dialect.py", line 289, in parse
    return self.parser(**opts).parse(self.tokenize(sql), sql)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/env/lib/python3.11/site-packages/sqlglot/parser.py", line 900, in parse
    return self._parse(
           ^^^^^^^^^^^^
  File "/tmp/env/lib/python3.11/site-packages/sqlglot/parser.py", line 969, in _parse
    self.raise_error("Invalid expression / Unexpected token")
  File "/tmp/env/lib/python3.11/site-packages/sqlglot/parser.py", line 1010, in raise_error
    raise error
sqlglot.errors.ParseError: Invalid expression / Unexpected token. Line 1, Col: 60.
  SELECT title FROM pgweb WHERE to_tsvector('english', body) @@ to_tsquery('english', 'friend')
```

**Comment by tobymao** [comment]
you need to specify the dialect, .where(..., dialect="postgres")
