### ISSUE TITLE
No response when SQL optimize with rule of pushdown_predicates

### ISSUE THREAD

**Issue by powerAmore** [tobymao/sqlglot#2068]
```python
from sqlglot.optimizer import optimize
from sqlglot.optimizer.qualify import qualify
from sqlglot.optimizer.pushdown_predicates import pushdown_predicates

sql = """
SELECT
*
FROM t0
LEFT JOIN t1 ON t0.device_id = t1.device_id AND t0.time < t1.time AND t0.time <= t1.time
"""

RULES = [
            qualify,
            pushdown_predicates,
        ]
sql = optimize(sql, dialect='trino', rules=RULES).sql(pretty=True)

print(sql)
```

There will be no response when running code above. After keyboard interrupt, it will show trackback as followed:
```
^CTraceback (most recent call last):
  File "/Users/powerlee/mobiuspace/SQLPredict/test.py", line 16, in <module>
    sql = optimize(sql, dialect='trino', rules=RULES).sql(pretty=True)
  File "/Users/powerlee/anaconda3/envs/sqlPredictEnv/lib/python3.8/site-packages/sqlglot/optimizer/optimizer.py", line 92, in optimize
    expression = rule(expression, **rule_kwargs)
  File "/Users/powerlee/anaconda3/envs/sqlPredictEnv/lib/python3.8/site-packages/sqlglot/optimizer/pushdown_predicates.py", line 45, in pushdown_predicates
    pushdown(join.args.get("on"), {name: scope.selected_sources[name]}, scope_ref_count)
  File "/Users/powerlee/anaconda3/envs/sqlPredictEnv/lib/python3.8/site-packages/sqlglot/optimizer/pushdown_predicates.py", line 54, in pushdown
    condition = condition.replace(simplify(condition))
  File "/Users/powerlee/anaconda3/envs/sqlPredictEnv/lib/python3.8/site-packages/sqlglot/optimizer/simplify.py", line 73, in simplify
    expression = while_changing(expression, _simplify)
  File "/Users/powerlee/anaconda3/envs/sqlPredictEnv/lib/python3.8/site-packages/sqlglot/helper.py", line 209, in while_changing
    for n, *_ in expression.walk():
  File "/Users/powerlee/anaconda3/envs/sqlPredictEnv/lib/python3.8/site-packages/sqlglot/expressions.py", line 399, in walk
    yield from self.bfs(prune=prune)
  File "/Users/powerlee/anaconda3/envs/sqlPredictEnv/lib/python3.8/site-packages/sqlglot/expressions.py", line 437, in bfs
    queue.append((v, item, k))
KeyboardInterrupt
```

**Comment by GeorgeSittas** [comment]
Thanks for the report @powerAmore! Will take a look soon.
