### ISSUE TITLE
Support for GCP BigQuery's `TRIM` native function.

### ISSUE THREAD

**Issue by skyserenaa** [tobymao/sqlglot#2341]
# Feature request

The SQL engine does not support the native function of BigQuery `TRIM`.

[Here](https://cloud.google.com/bigquery/docs/reference/standard-sql/string_functions#trim) is the official documentation for the function.

----

# Test performed

When executing the following query (with `sqlglot 18.8.0`)
```python
from sqlglot.dialects import BigQuery
from sqlglot.executor import execute

execute(sql='SELECT TRIM(" hello ") as field_1', read=BigQuery)
```
I would expect the result to be
```csv
field_1
hello
```
with the string `hello` not containing any leading or trailing whitespaces.

Instead I get the following `ExecuteError`
```
Traceback (most recent call last):
  File "[REDACTED]/.venv/lib/python3.9/site-packages/sqlglot/executor/python.py", line 38, in execute
    contexts[node] = self.scan(node, context)
  File "[REDACTED]/.venv/lib/python3.9/site-packages/sqlglot/executor/python.py", line 106, in scan
    return self.context({step.name: self._project_and_filter(context, step, table_iter)})
  File "[REDACTED]/.venv/lib/python3.9/site-packages/sqlglot/executor/python.py", line 121, in _project_and_filter
    sink.append(context.eval_tuple(projections))
  File "[REDACTED]/.venv/lib/python3.9/site-packages/sqlglot/executor/context.py", line 38, in eval_tuple
    return tuple(self.eval(code) for code in codes)
  File "[REDACTED]/.venv/lib/python3.9/site-packages/sqlglot/executor/context.py", line 38, in <genexpr>
    return tuple(self.eval(code) for code in codes)
  File "[REDACTED]/.venv/lib/python3.9/site-packages/sqlglot/executor/context.py", line 35, in eval
    return eval(code, self.env)
  File "TRIM(' hello ')", line 1, in <module>
NameError: name 'TRIM' is not defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "[REDACTED]/__sqlglot_trial.py", line 4, in <module>
    execute(sql='SELECT TRIM(" hello ") as field_1', read=BigQuery)
  File "[REDACTED]/.venv/lib/python3.9/site-packages/sqlglot/executor/__init__.py", line 88, in execute
    result = PythonExecutor(tables=tables_).execute(plan)
  File "[REDACTED]/.venv/lib/python3.9/site-packages/sqlglot/executor/python.py", line 60, in execute
    raise ExecuteError(f"Step '{node.id}' failed: {e}") from e
sqlglot.errors.ExecuteError: Step 'Scan: (4348114064)' failed: name 'TRIM' is not defined```

**Comment by skyserenaa** [comment]
Thanks @GeorgeSittas @tobymao ! 👏
