### ISSUE TITLE
Support for GCP BigQuery's `DATETIME` native function.

### ISSUE THREAD

**Issue by skyserenaa** [tobymao/sqlglot#2345]
# Feature request

The SQL engine does not support the native function of BigQuery `DATETIME`.

[Here](https://cloud.google.com/bigquery/docs/reference/standard-sql/datetime_functions#datetime) is the official documentation for the function.

----

# Test performed

When executing the following query (with `sqlglot 18.10.0`)
```python
from sqlglot.dialects import BigQuery
from sqlglot.executor import execute

execute(sql='SELECT DATETIME("2022-01-01", "Europe/Rome") as field_1', read=BigQuery)
```
I would expect the result to be
```csv
field_1
2022-01-01T01:00:00
```

Instead I get the following `ExecuteError`
```
Traceback (most recent call last):
  File "[REDACTED]/.venv/lib/python3.9/site-packages/sqlglot/executor/python.py", line 38, in execute
    contexts[node] = self.scan(node, context)
  File "[REDACTED]/.venv/lib/python3.9/site-packages/sqlglot/executor/python.py", line 106, in scan
    return self.context({step.name: self._project_and_filter(context, step, table_iter)})
  File "[REDACTED]/.venv/lib/python3.9/site-packages/sqlglot/executor/python.py", line 121, in _project_and_filter
    sink.append(context.eval_tuple(projections))
  File "[REDACTED]/.venv/lib/python3.9/site-packages/sqlglot/executor/context.py", line 38, in eval_tuple
    return tuple(self.eval(code) for code in codes)
  File "[REDACTED]/.venv/lib/python3.9/site-packages/sqlglot/executor/context.py", line 38, in <genexpr>
    return tuple(self.eval(code) for code in codes)
  File "[REDACTED]/.venv/lib/python3.9/site-packages/sqlglot/executor/context.py", line 35, in eval
    return eval(code, self.env)
  File "DATETIME('2022-01-01', 'Europe/Rome')", line 1, in <module>
NameError: name 'DATETIME' is not defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "[REDACTED]/__sqlglot_trial.py", line 4, in <module>
    execute(sql='SELECT DATETIME("2022-01-01", "Europe/Rome") as field_1', read=BigQuery)
  File "[REDACTED]/.venv/lib/python3.9/site-packages/sqlglot/executor/__init__.py", line 88, in execute
    result = PythonExecutor(tables=tables_).execute(plan)
  File "[REDACTED]/.venv/lib/python3.9/site-packages/sqlglot/executor/python.py", line 60, in execute
    raise ExecuteError(f"Step '{node.id}' failed: {e}") from e
sqlglot.errors.ExecuteError: Step 'Scan: (4312644912)' failed: name 'DATETIME' is not defined
```

**_Note_**: also running the `DATETIME` command without timezone conversion (e.g. `SELECT DATETIME("2022-01-01") as field_1`) fails with the same error.

**Comment by tobymao** [comment]
not planned, but happy to accept a PR for this
