### ISSUE TITLE
Error with QUALIFY + ROW_NUMBER

### ISSUE THREAD

**Issue by bobvanratingen** [tobymao/sqlglot#241]
This one is working.

```
        SELECT 
            i,p,o,
            ROW_NUMBER() OVER (
                PARTITION BY p
                ORDER BY
                o
            ) AS row_num
        FROM
            qt as qt
        QUALIFY
            row_num = 1
```

But I get an error when I remove the alias:

```
        SELECT 
            i,p,o,
            ROW_NUMBER() OVER (
                PARTITION BY p
                ORDER BY
                o
            ) AS row_num
        FROM
            qt
        QUALIFY
            row_num = 1
```

Also the optimizer sees row_num as Ambiguous column.

**Comment by tobymao** [comment]
@barakalon i could use help on this one, quality has a different scope than the rest of the select, not sure the best way to do that

**Comment by barakalon** [comment]
I think there are two different errors here.

The first is a parse error.

```
Python 3.9.13 (main, May 24 2022, 21:28:31)
[Clang 13.1.6 (clang-1316.0.21.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlglot
>>> stmt = """
... SELECT
...             i,p,o,
...             ROW_NUMBER() OVER (
...                 PARTITION BY p
...                 ORDER BY
...                 o
...             ) AS row_num
...         FROM
...             qt
...         QUALIFY
...             row_num = 1
... """
>>> sqlglot.parse_one(stmt, read="bigquery")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/barak_alon/Development/sqlglot/sqlglot/__init__.py", line 67, in parse_one
    result = dialect.parse(sql, **opts)
  File "/Users/barak_alon/Development/sqlglot/sqlglot/dialects/dialect.py", line 90, in parse
    return self.parser(**opts).parse(self.tokenizer.tokenize(sql), sql)
  File "/Users/barak_alon/Development/sqlglot/sqlglot/parser.py", line 275, in parse
    return self._parse(
  File "/Users/barak_alon/Development/sqlglot/sqlglot/parser.py", line 313, in _parse
    self.check_errors()
  File "/Users/barak_alon/Development/sqlglot/sqlglot/parser.py", line 320, in check_errors
    raise error
sqlglot.errors.ParseError: Invalid expression / Unexpected token. Line 12, Col: 13.

                o
            ) AS row_num
        FROM
            qt
        QUALIFY
            row_num = 1
```

That is, the second statement (without the table alias) fails.

The second is an optimizer error.

I'll start looking into the optimizer error. Maybe someone else can dig into the parser error?

**Comment by tobymao** [comment]
parser error fixed
