### ISSUE TITLE
Issue with shorthand reference to temporary table in redshift

### ISSUE THREAD

**Issue by Sorrop** [tobymao/sqlglot#2428]
Generating sql back from ast that contains a reference to a temporary table using the hashtag shorthand in its name triggers an error.

**sqlglot version: 18.15.0**

**Fully reproducible code snippet**
```python
import sqlglot
sql = "select * from some_table where y = dateadd('month', -1, date_trunc('month', (select x from #temp_table)-1))-1"
parsed = sqlglot.parse_one(sql, dialect="redshift")
parsed.sql(dialect="redshift")
#sqlglot.errors.ParseError: Expected table name but got <Token token_type: TokenType.HASH, text: #, line: 1, col: 36, start: 35, end: 35, comments: []>. Line 1, Col: 36.
```

Full stacktrace:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/lib/python3.11/site-packages/sqlglot/expressions.py", line 511, in sql
    return Dialect.get_or_raise(dialect)().generate(self, **opts)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/sqlglot/dialects/dialect.py", line 319, in generate
    return self.generator(**opts).generate(expression)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/sqlglot/generator.py", line 466, in generate
    sql = self.sql(expression).strip()
          ^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/sqlglot/generator.py", line 601, in sql
    sql = transform(self, expression)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/sqlglot/transforms.py", line 404, in _to_sql
    return _sql_handler(expression)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/sqlglot/generator.py", line 1895, in select_sql
    sql = self.query_modifiers(
          ^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/sqlglot/generator.py", line 1825, in query_modifiers
    self.sql(expression, "where"),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/sqlglot/generator.py", line 589, in sql
    return self.sql(value)
           ^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/sqlglot/generator.py", line 608, in sql
    sql = getattr(self, exp_handler_name)(expression)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/sqlglot/generator.py", line 1991, in where_sql
    this = self.indent(self.sql(expression, "this"))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/sqlglot/generator.py", line 589, in sql
    return self.sql(value)
           ^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/sqlglot/generator.py", line 608, in sql
    sql = getattr(self, exp_handler_name)(expression)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/sqlglot/generator.py", line 2532, in eq_sql
    return self.binary(expression, "=")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/sqlglot/generator.py", line 2616, in binary
    return f"{self.sql(expression, 'this')} {op} {self.sql(expression, 'expression')}"
                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/sqlglot/generator.py", line 589, in sql
    return self.sql(value)
           ^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/sqlglot/generator.py", line 608, in sql
    sql = getattr(self, exp_handler_name)(expression)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/sqlglot/generator.py", line 2596, in sub_sql
    return self.binary(expression, "-")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/sqlglot/generator.py", line 2616, in binary
    return f"{self.sql(expression, 'this')} {op} {self.sql(expression, 'expression')}"
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/sqlglot/generator.py", line 589, in sql
    return self.sql(value)
           ^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/sqlglot/generator.py", line 601, in sql
    sql = transform(self, expression)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/sqlglot/dialects/redshift.py", line 165, in <lambda>
    exp.DateAdd: lambda self, e: self.func(
                                 ^^^^^^^^^^
  File "/lib/python3.11/site-packages/sqlglot/generator.py", line 2644, in func
    return f"{self.normalize_func(name)}{prefix}{self.format_args(*args)}{suffix}"
                                                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/sqlglot/generator.py", line 2647, in format_args
    arg_sqls = tuple(self.sql(arg) for arg in args if arg is not None)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/sqlglot/generator.py", line 2647, in <genexpr>
    arg_sqls = tuple(self.sql(arg) for arg in args if arg is not None)
                     ^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/sqlglot/generator.py", line 601, in sql
    sql = transform(self, expression)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/sqlglot/dialects/dialect.py", line 696, in _ts_or_ds_to_date_sql
    return self.sql(exp.cast(self.sql(expression, "this"), "date"))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/sqlglot/expressions.py", line 6044, in cast
    expression = maybe_parse(expression, **opts)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/sqlglot/expressions.py", line 5220, in maybe_parse
    return sqlglot.parse_one(sql, read=dialect, into=into, **opts)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/sqlglot/__init__.py", line 125, in parse_one
    result = dialect.parse(sql, **opts)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/sqlglot/dialects/dialect.py", line 311, in parse
    return self.parser(**opts).parse(self.tokenize(sql), sql)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/sqlglot/parser.py", line 982, in parse
    return self._parse(
           ^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/sqlglot/parser.py", line 1048, in _parse
    expressions.append(parse_method(self))
                       ^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/sqlglot/parser.py", line 1237, in _parse_statement
    expression = self._parse_expression()
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/sqlglot/parser.py", line 3170, in _parse_expression
    return self._parse_alias(self._parse_conjunction())
                             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/sqlglot/parser.py", line 3173, in _parse_conjunction
    return self._parse_tokens(self._parse_equality, self.CONJUNCTION)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/sqlglot/parser.py", line 4805, in _parse_tokens
    this = parse_method()
           ^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/sqlglot/parser.py", line 3176, in _parse_equality
    return self._parse_tokens(self._parse_comparison, self.EQUALITY)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/sqlglot/parser.py", line 4805, in _parse_tokens
    this = parse_method()
           ^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/sqlglot/parser.py", line 3179, in _parse_comparison
    return self._parse_tokens(self._parse_range, self.COMPARISON)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/sqlglot/parser.py", line 4805, in _parse_tokens
    this = parse_method()
           ^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/sqlglot/parser.py", line 3182, in _parse_range
    this = self._parse_bitwise()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/sqlglot/parser.py", line 3289, in _parse_bitwise
    this = self._parse_term()
           ^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/sqlglot/parser.py", line 3314, in _parse_term
    return self._parse_tokens(self._parse_factor, self.TERM)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/sqlglot/parser.py", line 4805, in _parse_tokens
    this = parse_method()
           ^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/sqlglot/parser.py", line 3317, in _parse_factor
    return self._parse_tokens(self._parse_unary, self.FACTOR)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/sqlglot/parser.py", line 4805, in _parse_tokens
    this = parse_method()
           ^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/sqlglot/parser.py", line 3322, in _parse_unary
    return self._parse_at_time_zone(self._parse_type())
                                    ^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/sqlglot/parser.py", line 3331, in _parse_type
    this = self._parse_column()
           ^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/sqlglot/parser.py", line 3511, in _parse_column
    this = self._parse_field()
           ^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/sqlglot/parser.py", line 3615, in _parse_field
    or self._parse_function(anonymous=anonymous_func)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/sqlglot/parser.py", line 3666, in _parse_function
    args = self._parse_csv(lambda: self._parse_lambda(alias=alias))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/sqlglot/parser.py", line 4796, in _parse_csv
    parse_result = parse_method()
                   ^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/sqlglot/parser.py", line 3666, in <lambda>
    args = self._parse_csv(lambda: self._parse_lambda(alias=alias))
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/sqlglot/parser.py", line 3741, in _parse_lambda
    this = self._parse_select_or_expression(alias=alias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/sqlglot/parser.py", line 4841, in _parse_select_or_expression
    self._parse_expression() if alias else self._parse_conjunction()
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/sqlglot/parser.py", line 3173, in _parse_conjunction
    return self._parse_tokens(self._parse_equality, self.CONJUNCTION)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/sqlglot/parser.py", line 4805, in _parse_tokens
    this = parse_method()
           ^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/sqlglot/parser.py", line 3176, in _parse_equality
    return self._parse_tokens(self._parse_comparison, self.EQUALITY)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/sqlglot/parser.py", line 4805, in _parse_tokens
    this = parse_method()
           ^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/sqlglot/parser.py", line 3179, in _parse_comparison
    return self._parse_tokens(self._parse_range, self.COMPARISON)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/sqlglot/parser.py", line 4805, in _parse_tokens
    this = parse_method()
           ^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/sqlglot/parser.py", line 3182, in _parse_range
    this = self._parse_bitwise()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/sqlglot/parser.py", line 3289, in _parse_bitwise
    this = self._parse_term()
           ^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/sqlglot/parser.py", line 3314, in _parse_term
    return self._parse_tokens(self._parse_factor, self.TERM)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/sqlglot/parser.py", line 4805, in _parse_tokens
    this = parse_method()
           ^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/sqlglot/parser.py", line 3317, in _parse_factor
    return self._parse_tokens(self._parse_unary, self.FACTOR)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/sqlglot/parser.py", line 4805, in _parse_tokens
    this = parse_method()
           ^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/sqlglot/parser.py", line 3322, in _parse_unary
    return self._parse_at_time_zone(self._parse_type())
                                    ^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/sqlglot/parser.py", line 3331, in _parse_type
    this = self._parse_column()
           ^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/sqlglot/parser.py", line 3511, in _parse_column
    this = self._parse_field()
           ^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/sqlglot/parser.py", line 3614, in _parse_field
    self._parse_primary()
  File "/lib/python3.11/site-packages/sqlglot/parser.py", line 3581, in _parse_primary
    query = self._parse_select()
            ^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/sqlglot/parser.py", line 2148, in _parse_select
    from_ = self._parse_from()
            ^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/sqlglot/parser.py", line 2303, in _parse_from
    exp.From, comments=self._prev_comments, this=self._parse_table(joins=joins)
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/sqlglot/parser.py", line 2644, in _parse_table
    exp.Expression, bracket or self._parse_bracket(self._parse_table_parts(schema=schema))
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/sqlglot/parser.py", line 2610, in _parse_table_parts
    self.raise_error(f"Expected table name but got {self._curr}")
  File "/lib/python3.11/site-packages/sqlglot/parser.py", line 1092, in raise_error
    raise error
sqlglot.errors.ParseError: Expected table name but got <Token token_type: TokenType.HASH, text: #, line: 1, col: 36, start: 35, end: 35, comments: []>. Line 1, Col: 36.
  DATE_TRUNC('month', (SELECT x FROM #temp_table) - 1)
```

The same piece of sql without the hashtag in the table name works fine. Also, I think the date manipulation functions might be relevant here because a statement like
```sql
select * from some_table where y in (select x from #temp_table)
```
also works fine.

**Official Documentation**
[the "important" section specifies the shorthand notation for temporary tables]
https://docs.aws.amazon.com/redshift/latest/dg/r_CREATE_TABLE_NEW.html

**Comment by tobymao** [comment]
this works in later versions of sqlglot, please follow the template instructions next time and upgrade sqlglot.

**Comment by Sorrop** [comment]
I did use the latest version. You can check a failing test case here: https://github.com/Sorrop/sqlglot

**Comment by tobymao** [comment]
thanks, i'm not sure why i wasn't able to reproduce it, i can now in my notebook
