### ISSUE TITLE
feat(postgres): create partition tables

### ISSUE THREAD

**Issue by judahrand** [tobymao/sqlglot#2469]
**Is your feature request related to a problem? Please describe.**
Be able to parse statements like: `CREATE TABLE cust_part3 PARTITION OF customers FOR VALUES WITH (modulus 3, remainder 2)`

```python
>>> sqlglot.parse_one('CREATE TABLE cust_part3 PARTITION OF customers FOR VALUES WITH (modulus 3, remainder 2)', dialect='postgres')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".venv/lib/python3.11/site-packages/sqlglot/__init__.py", line 125, in parse_one
    result = dialect.parse(sql, **opts)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/sqlglot/dialects/dialect.py", line 311, in parse
    return self.parser(**opts).parse(self.tokenize(sql), sql)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/sqlglot/parser.py", line 986, in parse
    return self._parse(
           ^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/sqlglot/parser.py", line 1055, in _parse
    self.raise_error("Invalid expression / Unexpected token")
  File ".venv/lib/python3.11/site-packages/sqlglot/parser.py", line 1096, in raise_error
    raise error
sqlglot.errors.ParseError: Invalid expression / Unexpected token. Line 1, Col: 33.
  CREATE TABLE cust_part3 PARTITION OF customers FOR VALUES WITH (modulus 3, remainder 2)
```
**Describe the solution you'd like**
I'd like this syntax to be supported for the Postgres dialect.

**Describe alternatives you've considered**

**Additional context**

**Comment by GeorgeSittas** [comment]
I can take a look into this soon
