### ISSUE TITLE
Comments in SQL query result in parsing errors

### ISSUE THREAD

**Issue by AndreZWei** [tobymao/sqlglot#247]
```
>>> sql = "SELECT 1; # this is a comment"
>>> sqlglot.parse(sql)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.9/site-packages/sqlglot/__init__.py", line 38, in parse
    return dialect.parse(sql, **opts)
  File "/opt/homebrew/lib/python3.9/site-packages/sqlglot/dialects.py", line 60, in parse
    return self.parser(**opts).parse(self.tokenizer().tokenize(sql), sql)
  File "/opt/homebrew/lib/python3.9/site-packages/sqlglot/parser.py", line 270, in parse
    return self._parse(
  File "/opt/homebrew/lib/python3.9/site-packages/sqlglot/parser.py", line 322, in _parse
    self.check_errors()
  File "/opt/homebrew/lib/python3.9/site-packages/sqlglot/parser.py", line 329, in check_errors
    raise error
sqlglot.errors.ParseError: Invalid expression / Unexpected token. Line 1, Col: 12.
  SELECT 1; # this is a comment
```

**Comment by tobymao** [comment]
# is not valid comment syntax in any dialect i know, you need to use // or /* */

what dialect uses #? sqlglot overrides # and calls that an annotation

closing this for now, but if you want to support # we'll need to add a new dialect
