### ISSUE TITLE
Column '"col1"' could not be resolved

### ISSUE THREAD

**Issue by liujiwen-up** [tobymao/sqlglot#2600]
`import sqlglot
from sqlglot.optimizer.qualify import qualify

query = """
select col1,col2
	from table1 as t1
	left join table3 as t3
	on t1.col1=t3.col4
union all
select col3,col4
	from table2;
"""
print((qualify(sqlglot.parse_one(query, read='presto')).sql()))
`
error：
`Traceback (most recent call last):
  File "/Users/liujiwen/PycharmProjects/sqlglot-doris-1116/badcase.py", line 13, in <module>
    print((qualify(sqlglot.parse_one(query, read='presto')).sql()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/liujiwen/PycharmProjects/sqlglot-doris-1116/sqlglot/optimizer/qualify.py", line 78, in qualify
    validate_qualify_columns_func(expression)
  File "/Users/liujiwen/PycharmProjects/sqlglot-doris-1116/sqlglot/optimizer/qualify_columns.py", line 77, in validate_qualify_columns
    raise OptimizeError(
sqlglot.errors.OptimizeError: Column '"col1"' could not be resolved
`

**Comment by tobymao** [comment]
this is expected behavior, col1 is ambiguous. please put some effort into your issues and try communicating with us.
