### ISSUE TITLE
sqlglot [hive] fails on unnecessary parens when there is a join in target subquery

### ISSUE THREAD

**Issue by philipfweiss** [tobymao/sqlglot#268]
The following python code errors:

```
import sqlglot

sql = """
SELECT
    *
FROM (
  ( SELECT * FROM foo ) a
LEFT JOIN
  ( SELECT id, country FROM bar) b
ON a.id_listing = b.id
)
"""

sqlglot.parse(sql, read='hive')
```

Error:
```
Traceback (most recent call last):
  File "/Users/philip_weiss/foo.py", line 14, in <module>
    sqlglot.parse(sql, read='hive')
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/sqlglot/__init__.py", line 43, in parse
    return dialect.parse(sql, **opts)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/sqlglot/dialects/dialect.py", line 90, in parse
    return self.parser(**opts).parse(self.tokenizer.tokenize(sql), sql)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/sqlglot/parser.py", line 275, in parse
    return self._parse(
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/sqlglot/parser.py", line 313, in _parse
    self.check_errors()
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/sqlglot/parser.py", line 320, in check_errors
    raise error
sqlglot.errors.ParseError: Expecting ). Line 6, Col: 1.
  
SELECT
    *
FROM (
  ( SELECT * FROM foo ) a
LEFT JOIN
  ( SELECT id, country FROM bar) b
ON a.id_listing = b.id
)
```

Interestingly, removing the parens from the FROM prevents there error:

```
import sqlglot

sql = """
SELECT
    *
FROM 
  ( SELECT * FROM foo ) a
LEFT JOIN
  ( SELECT id, country FROM bar) b
ON a.id_listing = b.id

"""

sqlglot.parse(sql, read='hive')
```

**Comment by barakalon** [comment]
The first query is valid hive SQL?

**Comment by tobymao** [comment]
```SELECT
    *
FROM (
  ( SELECT 1 x ) a
LEFT JOIN
  ( SELECT 1 x) b
ON a.x = b.x
) y```

is not valid hive, but seems like it works in presto....

**Comment by barakalon** [comment]
yeesh.
