### ISSUE TITLE
Cycle error when optimizing a MySQL query with self joins

### ISSUE THREAD

**Issue by Konntroll** [tobymao/sqlglot#2797]
I have a query like this:

```
SELECT a.company,
       b.num
FROM route a
JOIN route b ON (a.num = b.num)
JOIN stops c ON (c.id = b.stop)
JOIN stops d ON (d.id = c.id)  
WHERE c.name = 'Craiglockhart'
   OR d.name = 'Tollcross'
```

I'm optimizing it like this:

`optimize(query, schema=schema).sql(dialect='mysql')`

I'm getting a `ValueError: Cycle Error` with the following traceback:

```
Traceback (most recent call last):
  File "C:\msc_project\test.py", line 119, in <module>
    optimize(query, schema=schema).sql(dialect='mysql')
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlglot\optimizer\optimizer.py", line 92, in optimize
    expression = rule(expression, **rule_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlglot\optimizer\optimize_joins.py", line 51, in optimize_joins
    expression = reorder_joins(expression)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlglot\optimizer\optimize_joins.py", line 66, in reorder_joins
    [joins[name] for name in tsort(dag) if name != from_.alias_or_name and name in joins],
                             ^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlglot\helper.py", line 246, in tsort
    raise ValueError("Cycle error")
ValueError: Cycle error
```

**Comment by tobymao** [comment]
can't reproduce, please follow instructions and update versions

```python
from sqlglot.optimizer.optimize_joins import optimize_joins
from sqlglot import parse_one

query = parse_one("""
SELECT a.company,
       b.num
FROM route a 
JOIN route b ON (a.num = b.num)
JOIN stops c ON (c.id = b.stop)
JOIN stops d ON (d.id = c.id)  
WHERE c.name = 'Craiglockhart'
   OR d.name = 'Tollcross'
""")

print(optimize_joins(query).sql(pretty=True, dialect="mysql"))
```

**Comment by Konntroll** [comment]
@tobymao, the code snippet you shared works fine, however, when trying to use the `optimize` method on the query instead of `optimize_joins` I get the error I mentioned originally. Here's the minimum reproducible snippet that produces the 'cycle error' in version 20.8.0:

```
from sqlglot.optimizer import optimize
from sqlglot import parse_one

schema = {
  'stops': {'id': 'INT', 'name': 'STRING'},
  'route': {'num': 'STRING', 'company': 'STRING', 'pos': 'INT', 'stop': 'INT'}
}

query = parse_one("""
  SELECT a.company,
        b.num
  FROM route a
  JOIN route b ON (a.num = b.num)
  JOIN stops c ON (c.id = b.stop)
  JOIN stops d ON (d.id = c.id)  
  WHERE c.name = 'Craiglockhart'
    OR d.name = 'Tollcross'
""")

optimize(query, schema=schema).sql(dialect='mysql')
```

If I understand the source code right, both `optimize` and `optimize_joins` should work on any supplied viable query but the `optimize` method should apply a broader range of adjustments to it. Perhaps I'm missing something?

**Comment by georgesittas** [comment]
Seems like the predicate pushdown rule indeed causes this issue, I can reproduce it. Taking a look now, thanks for clarifying @Konntroll!
