### ISSUE TITLE
Cannot import the library on a system without typing_extensions

### ISSUE THREAD

**Issue by fattybenji** [tobymao/sqlglot#2897]
In order to reproduce, get a clean environment (virtual env or docker image) and just install version `2.10.0`. Then try to import the lib, it breaks with the following error:

```
>>> import sqlglot
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.11/site-packages/sqlglot/__init__.py", line 12, in <module>
    from sqlglot import expressions as exp
  File "/usr/local/lib/python3.11/site-packages/sqlglot/expressions.py", line 26, in <module>
    from sqlglot._typing import E
  File "/usr/local/lib/python3.11/site-packages/sqlglot/_typing.py", line 5, in <module>
    from typing_extensions import Literal as Lit  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'typing_extensions'
```

I suggest adding `typing_extensions` to `install_requires`, I'll be making a PR.

**Comment by fattybenji** [comment]
Looks like it works on main, probably with https://github.com/tobymao/sqlglot/pull/2886. I thought it was part of release 2.10, it's just not released yet. Closing.
