### ISSUE TITLE
Unable to parse "AS" after a Cross Join

### ISSUE THREAD

**Issue by jelstongreen** [tobymao/sqlglot#3154]
**Before you file an issue**
- Make sure you specify the "read" dialect eg. `parse_one(sql, read="spark")`
Databricks
- Make sure you specify the "write" dialect eg. `ast.sql(dialect="duckdb")`
N/A - Parsing Only
- Check if the issue still exists on main
Using latest version

**Fully reproducible code snippet**
Please include a fully reproducible code snippet or the input sql, dialect, and expected output.
```python
    sql = """
    SELECT *
    FROM example_table
    CROSS JOIN (VALUES 'foo','bar' data(license)) AS col_name --noqa
    """
    sqlglot.parse_one(sql, read='databricks')
```
Returns:
```
Traceback (most recent call last):
  File "file.py", line 39, in <module>
    sqlglot.parse_one(sql, read='databricks')
  File "lib/python3.12/site-packages/sqlglot/__init__.py", line 124, in parse_one
    result = dialect.parse(sql, **opts)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "lib/python3.12/site-packages/sqlglot/dialects/dialect.py", line 490, in parse
    return self.parser(**opts).parse(self.tokenize(sql), sql)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "lib/python3.12/site-packages/sqlglot/parser.py", line 1151, in parse
    return self._parse(
           ^^^^^^^^^^^^
  File "lib/python3.12/site-packages/sqlglot/parser.py", line 1220, in _parse
    self.raise_error("Invalid expression / Unexpected token")
  File "lib/python3.12/site-packages/sqlglot/parser.py", line 1261, in raise_error
    raise error
sqlglot.errors.ParseError: Invalid expression / Unexpected token. Line 4, Col: 52.
  
    SELECT *
    FROM example_table
    CROSS JOIN (VALUES 'foo','bar' data(license)) AS col_name --noqa
```

**Official Documentation**
Please include links to official SQL documentation related to your issue.

**Comment by tobymao** [comment]
what does (VALUES 'foo','bar' data(license)) mean? is this valid in databricks?

**Comment by tobymao** [comment]
i see no syntax like that here so i'm closing for now until you can provide me more details

https://docs.databricks.com/en/sql/language-manual/sql-ref-syntax-qry-select-values.html

**Comment by jelstongreen** [comment]
Its not my query - I think that's user error from the original author, you're right in that it doesn't do anything. 

However both 
```
SELECT * 
FROM (VALUES 'a', 'b', 'c')
CROSS JOIN (VALUES 'x', 'y', 'z' data(temp_table))
```
and
```
SELECT * 
FROM (VALUES 'a', 'b', 'c')
CROSS JOIN (VALUES 'x', 'y', 'z' data(temp_table)) as another_alias
```
are valid sql queries. 
The former is parseable by SQLGlot, the latter is not:
```
sqlglot.errors.ParseError: Invalid expression / Unexpected token. Line 4, Col: 61.
  T * 
        FROM (VALUES 'a', 'b', 'c')
        CROSS JOIN (VALUES 'x', 'y', 'z' data(temp_table)) as temp
```
