### ISSUE TITLE
Error when parsing query with > = or < = operator with a space between < and =

### ISSUE THREAD

**Issue by Hal-H2Apps** [tobymao/sqlglot#3236]
**Version**
sqlglot 23.2.1.dev9

**Notes**
It's working fine with ! = 

**Fully reproducible code snippet**
import sqlglot

sqlglot.parse_one(sql="""SELECT T0.ID FROM T0 WHERE T0.ID > = 1""", read='oracle')

**Error message**

Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()
           ^^^^^^
  File "<input>", line 1, in <module>
  File "/usr/local/lib/python3.11/site-packages/sqlglot/__init__.py", line 124, in parse_one
    result = dialect.parse(sql, **opts)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlglot/dialects/dialect.py", line 490, in parse
    return self.parser(**opts).parse(self.tokenize(sql), sql)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlglot/parser.py", line 1163, in parse
    return self._parse(
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlglot/parser.py", line 1229, in _parse
    expressions.append(parse_method(self))
                       ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlglot/parser.py", line 1458, in _parse_statement
    expression = self._parse_set_operations(expression) if expression else self._parse_select()
                                                                           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlglot/parser.py", line 2521, in _parse_select
    this = self._parse_query_modifiers(this)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlglot/parser.py", line 2669, in _parse_query_modifiers
    key, expression = parser(self)
                      ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlglot/parser.py", line 946, in <lambda>
    TokenType.WHERE: lambda self: ("where", self._parse_where()),
                                            ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlglot/parser.py", line 3429, in _parse_where
    exp.Where, comments=self._prev_comments, this=self._parse_conjunction()
                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlglot/parser.py", line 3739, in _parse_conjunction
    return self._parse_tokens(self._parse_equality, self.CONJUNCTION)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlglot/parser.py", line 5579, in _parse_tokens
    this = parse_method()
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlglot/parser.py", line 3742, in _parse_equality
    return self._parse_tokens(self._parse_comparison, self.EQUALITY)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlglot/parser.py", line 5579, in _parse_tokens
    this = parse_method()
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlglot/parser.py", line 3745, in _parse_comparison
    return self._parse_tokens(self._parse_range, self.COMPARISON)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlglot/parser.py", line 5582, in _parse_tokens
    this = self.expression(
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlglot/parser.py", line 1293, in expression
    return self.validate_expression(instance)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlglot/parser.py", line 1313, in validate_expression
    self.raise_error(error_message)
  File "/usr/local/lib/python3.11/site-packages/sqlglot/parser.py", line 1273, in raise_error
    raise error
sqlglot.errors.ParseError: Required keyword: 'expression' missing for <class 'sqlglot.expressions.GT'>. Line 1, Col: 32.
  SELECT 1 FROM T0 WHERE T0.ID > = 1

**Official Documentation**
This query is working fine in oracle.

**Comment by georgesittas** [comment]
This is valid Oracle?!

**Comment by Hal-H2Apps** [comment]
Yes. As a Microsoft SQL Server DBA I'm really amazed by what Oracle permits.
Sadly this query is working really well in Oracle 19.0.0.0

<img width="473" alt="image" src="https://github.com/tobymao/sqlglot/assets/3640809/2e859660-2d2b-4c83-a031-7678c5a9c10e">
<img width="327" alt="image" src="https://github.com/tobymao/sqlglot/assets/3640809/fc36f7a8-5f9b-401c-8404-526d09fe2d7e">

**Comment by georgesittas** [comment]
> Yes. As a Microsoft SQL Server DBA I'm really amazed by what Oracle permits.

Seriously.. Btw, this is supported by T-SQL as well :D

```
1> select 1 where 2 > = 1
2> go
           
-----------
          1

(1 rows affected)
```

**Comment by georgesittas** [comment]
Hey @Hal-H2Apps, I looked into this and it doesn't seem simple to fix. Given that this is relatively low priority for us, I'm marking it as not planned for now.

I know you're not writing these queries yourself, but the ROI of fixing this is questionable because it would mean 1) either changing the tokenizer to handle arbitrary whitespace between multi-character operators (which isn't trivial) or 2) change the parser so it can understand and merge these tokens into a single one. This could be done either during the actual parsing (i.e. in `_parse_tokens`, somehow) or during the "chunkification" [stage](https://github.com/tobymao/sqlglot/blob/647611e16bdb5ecfc2eec30111cc6689200836b7/sqlglot/parser.py#L1215). My guess is that both would incur additional overhead.

**Comment by Hal-H2Apps** [comment]
I will try to catch the error and remove the space before resubmit the query to the parser. 
I don't know yet if your sqlglot.errors.ParseError is returning the position of the problem in the query provided. 
I will look into it.

Thanks anyway.

**Comment by Hal-H2Apps** [comment]
And if someone found this issue, my workaround was:
```
    sqlQuery: str = """SELECT 1 FROM T0 WHERE T0.ID < = 1"""
    proceed: bool = True
    while proceed:
        try:
            sql = sqlglot.parse_one(sql=sqlQuery, read='oracle')
            proceed = False
        except ParseError as pe:
            errDesc: str = pe.errors[0]['description']
            errHighlight: str = pe.errors[0]['highlight']
            errStartContext: str = pe.errors[0]['start_context']
            errEndContext: str = pe.errors[0]['end_context']
            if errDesc in ["Required keyword: 'expression' missing for <class 'sqlglot.expressions.GT'>", "Required keyword: 'expression' missing for <class 'sqlglot.expressions.LT'>"] and errHighlight == '=' and errStartContext.endswith(' '):
                sqlQuery = f'{errStartContext.rstrip()}{errHighlight}{errEndContext}'
            else:
                raise pe
```
