### ISSUE TITLE
In certain dialects, `schema` is not respected when supplied to `optimize`

### ISSUE THREAD

**Issue by rexledesma** [tobymao/sqlglot#3249]
`schema` is respected in `duckdb`, but not `snowflake` or `bigquery`? Let me know if I'm using the API incorrectly.

**Fully reproducible code snippet**

```
❯ pip freeze | grep sqlglot    
sqlglot==23.3.0
sqlglotrs==0.1.2
```

```python
import traceback

from sqlglot import MappingSchema, parse_one, to_table
from sqlglot.optimizer import optimize

sql = "select order_date, num_orders from DEMO.FORECASTING.predicted_orders"

for sql_dialect in ["duckdb", "bigquery", "snowflake"]:
    ast = parse_one(sql, dialect=sql_dialect)

    sqlglot_mapping_schema = MappingSchema()
    sqlglot_mapping_schema.add_table(
        to_table("DEMO.FORECASTING.predicted_orders", dialect=sql_dialect),
        column_mapping={"ORDER_DATE": "TIMESTAMP", "NUM_ORDERS": "FLOAT"},
        dialect=sql_dialect,
    )

    print(f"SQL Dialect: {sql_dialect}")

    try:
        print(
            optimize(ast, dialect=sql_dialect, schema=sqlglot_mapping_schema).sql(
                pretty=True
            )
            + "\n"
        )
    except:
        print(traceback.format_exc())
```

Results in the following behavior

```
SQL Dialect: duckdb
SELECT
  "predicted_orders"."order_date" AS "order_date",
  "predicted_orders"."num_orders" AS "num_orders"
FROM "demo"."forecasting"."predicted_orders" AS "predicted_orders"

SQL Dialect: bigquery
Traceback (most recent call last):
  File "/Users/rexledesma/Downloads/projects/replication.py", line 22, in <module>
    optimize(ast, dialect=sql_dialect, schema=sqlglot_mapping_schema).sql(
  File "/Users/rexledesma/.pyenv/versions/3.10.13/envs/dagster/lib/python3.10/site-packages/sqlglot/optimizer/optimizer.py", line 92, in optimize
    optimized = rule(optimized, **rule_kwargs)
  File "/Users/rexledesma/.pyenv/versions/3.10.13/envs/dagster/lib/python3.10/site-packages/sqlglot/optimizer/qualify.py", line 90, in qualify
    validate_qualify_columns_func(expression)
  File "/Users/rexledesma/.pyenv/versions/3.10.13/envs/dagster/lib/python3.10/site-packages/sqlglot/optimizer/qualify_columns.py", line 89, in validate_qualify_columns
    raise OptimizeError(f"Column '{column}' could not be resolved{for_table}")
sqlglot.errors.OptimizeError: Column 'order_date' could not be resolved

SQL Dialect: snowflake
Traceback (most recent call last):
  File "/Users/rexledesma/Downloads/projects/replication.py", line 22, in <module>
    optimize(ast, dialect=sql_dialect, schema=sqlglot_mapping_schema).sql(
  File "/Users/rexledesma/.pyenv/versions/3.10.13/envs/dagster/lib/python3.10/site-packages/sqlglot/optimizer/optimizer.py", line 92, in optimize
    optimized = rule(optimized, **rule_kwargs)
  File "/Users/rexledesma/.pyenv/versions/3.10.13/envs/dagster/lib/python3.10/site-packages/sqlglot/optimizer/qualify.py", line 90, in qualify
    validate_qualify_columns_func(expression)
  File "/Users/rexledesma/.pyenv/versions/3.10.13/envs/dagster/lib/python3.10/site-packages/sqlglot/optimizer/qualify_columns.py", line 89, in validate_qualify_columns
    raise OptimizeError(f"Column '{column}' could not be resolved{for_table}")
sqlglot.errors.OptimizeError: Column 'ORDER_DATE' could not be resolved
```

**Comment by georgesittas** [comment]
You need to pass in the dialect in the `MappingSchema` object as well:

```python
>>> import traceback
>>>
>>> from sqlglot import MappingSchema, parse_one, to_table
>>> from sqlglot.optimizer import optimize
>>>
>>> sql = 'select order_date, num_orders from "DEMO"."FORECASTING".predicted_orders'
>>>
>>> for sql_dialect in ["duckdb", "bigquery", "snowflake"]:
...     ast = parse_one(sql, dialect=sql_dialect)
...     sqlglot_mapping_schema = MappingSchema(dialect=sql_dialect)
...     sqlglot_mapping_schema.add_table(
...         to_table("DEMO.FORECASTING.predicted_orders", dialect=sql_dialect),
...         column_mapping={"ORDER_DATE": "TIMESTAMP", "NUM_ORDERS": "FLOAT"},
...         dialect=sql_dialect,
...     )
...     print(f"SQL Dialect: {sql_dialect}")
...     try:
...         print(
...             optimize(ast, dialect=sql_dialect, schema=sqlglot_mapping_schema).sql(
...                 pretty=True
...             )
...             + "\n"
...         )
...     except:
...         print(traceback.format_exc())
...
SQL Dialect: duckdb
SELECT
  "predicted_orders"."order_date" AS "order_date",
  "predicted_orders"."num_orders" AS "num_orders"
FROM "demo"."forecasting"."predicted_orders" AS "predicted_orders"

SQL Dialect: bigquery
SELECT
  "predicted_orders"."order_date" AS "order_date",
  "predicted_orders"."num_orders" AS "num_orders"
FROM "DEMO"."FORECASTING"."predicted_orders" AS "predicted_orders"

SQL Dialect: snowflake
SELECT
  "PREDICTED_ORDERS"."ORDER_DATE" AS "ORDER_DATE",
  "PREDICTED_ORDERS"."NUM_ORDERS" AS "NUM_ORDERS"
FROM "DEMO"."FORECASTING"."PREDICTED_ORDERS" AS "PREDICTED_ORDERS"
```
