### ISSUE TITLE
Misleading error message when keyword used as table name

### ISSUE THREAD

**Issue by plexilcrf** [tobymao/sqlglot#334]
In sqlglot 2.6.0:

I am using sqlglot to parse some badly written SQL not of my own creation.

A CREATE TABLE statement with an unquoted SQL keyword as the table name results in an error report that looks like an internal bug. E.g.:

```
>>> import sqlglot
>>> sqlglot.parse_one('CREATE TABLE Partition (name VARCHAR(255));')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gvsm/GVSM/vsm_ri_cfs/utilities/odm-checkers/sqlglot/sqlglot/__init__.py", line 67, in parse_one
    result = dialect.parse(sql, **opts)
  File "/home/gvsm/GVSM/vsm_ri_cfs/utilities/odm-checkers/sqlglot/sqlglot/dialects/dialect.py", line 114, in parse
    return self.parser(**opts).parse(self.tokenizer.tokenize(sql), sql)
  File "/home/gvsm/GVSM/vsm_ri_cfs/utilities/odm-checkers/sqlglot/sqlglot/parser.py", line 437, in parse
    parse_method=self._parse_statement, raw_tokens=raw_tokens, sql=sql
  File "/home/gvsm/GVSM/vsm_ri_cfs/utilities/odm-checkers/sqlglot/sqlglot/parser.py", line 474, in _parse
    self.check_errors()
  File "/home/gvsm/GVSM/vsm_ri_cfs/utilities/odm-checkers/sqlglot/sqlglot/parser.py", line 481, in check_errors
    raise error
sqlglot.errors.ParseError: Required keyword: 'this' missing for <class 'sqlglot.expressions.Table'>. Line 1, Col: 14.
  CREATE TABLE Partition (name VARCHAR(255));
>>> 
```

A quick fix that works for me and doesn't seem break the regression suite is to move the 'if not table:' statement at line 1055 in sqlglot/parser.py out of the containing while loop.

**Comment by tobymao** [comment]
thanks
