### ISSUE TITLE
Python Executor - ROW_NUMBER() function raises ExecuteError

### ISSUE THREAD

**Issue by rubytobi** [tobymao/sqlglot#3346]
Hi, I'm running into issues with the local execution/Python Executor. Using a `ROW_NUMBER()` function raises an `ExecuteError`.

**Fully reproducible code snippet**
```python
from sqlglot import parse_one
from sqlglot.executor import execute
from sqlglot.dialects import Athena

sql = "SELECT ROW_NUMBER() OVER (PARTITION BY col_a ORDER BY col_b ASC) FROM table_a"
parse_one(sql)
```
```
Select(
  expressions=[
    Window(
      this=RowNumber(),
      partition_by=[
        Column(
          this=Identifier(this=col_a, quoted=False))],
      order=Order(
        expressions=[
          Ordered(
            this=Column(
              this=Identifier(this=col_b, quoted=False)),
            desc=False,
            nulls_first=True)]),
      over=OVER)],
  from=From(
    this=Table(
      this=Identifier(this=table_a, quoted=False))))
```
```python
tables = {
    "table_a": [
        {"col_a": 1, "col_b": 1},
    ],
}

execute(sql, dialect=Athena, tables=tables)
```
```python
...
  File "ROWNUMBER() OVER (PARTITION BY scope["table_a"]["col_a"] ORDER BY ORDERED(scope["table_a"]["col_b"], False, False))", line 1
    ROWNUMBER() OVER (PARTITION BY scope["table_a"]["col_a"] ORDER BY ORDERED(scope["table_a"]["col_b"], False, False))
                ^^^^
SyntaxError: invalid syntax
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "[...]\pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 7, in <module>
  File "[...]\.venv\lib\site-packages\sqlglot\executor\__init__.py", line 87, in execute
    result = PythonExecutor(tables=tables_).execute(plan)
  File "[...]\.venv\lib\site-packages\sqlglot\executor\python.py", line 60, in execute
    raise ExecuteError(f"Step '{node.id}' failed: {e}") from e
sqlglot.errors.ExecuteError: Step 'Scan: table_a (2693844402816)' failed: invalid syntax (ROWNUMBER() OVER (PARTITION BY scope["table_a"]["col_a"] ORDER BY ORDERED(scope["table_a"]["col_b"], False, False)), line 1)

```

Please let me know if there's anything I can help with.

**Comment by georgesittas** [comment]
Hey, thanks for the report.

Window functions are currently not supported in the executor. It's in our roadmap to implement this, but not a high priority.
