### ISSUE TITLE
Version 23.12.2 fails to parse some COPY clauses

### ISSUE THREAD

**Issue by dangoldin** [tobymao/sqlglot#3388]
Looks as if in prior versions it didn't fully parse and fell back to the default Command but with 23.12.2 it's trying to parse and failing. Maybe we can have it fall back to Command as we work through various options COPY has?

**Fully reproducible code snippet**

```python
from sqlglot import parse_one

q = """
copy into temp FROM @random_stage/path/
FILE_FORMAT = (
    TYPE=CSV
    FIELD_DELIMITER='|'
    NULL_IF=()
    FIELD_OPTIONALLY_ENCLOSED_BY='"'
    TIMESTAMP_FORMAT='TZHTZM YYYY-MM-DD HH24:MI:SS.FF9'
    DATE_FORMAT='TZHTZM YYYY-MM-DD HH24:MI:SS.FF9'
    BINARY_FORMAT=BASE64
  )
"""

pq = parse_one(q, read="snowflake")
print("Parsed:", pq, "\n")
```

The above gives the following using 23.12.1:
```
✗ python test_sqlglot.py 
'copy into temp FROM @random_stage/path/
FILE_FORMAT = (
    TYPE=CSV
    FIELD_DELIMITER='|'
    NUL' contains unsupported syntax. Falling back to parsing as a 'Command'.
Parsed: COPY into temp FROM @random_stage/path/
FILE_FORMAT = (
    TYPE=CSV
    FIELD_DELIMITER='|'
    NULL_IF=()
    FIELD_OPTIONALLY_ENCLOSED_BY='"'
    TIMESTAMP_FORMAT='TZHTZM YYYY-MM-DD HH24:MI:SS.FF9'
    DATE_FORMAT='TZHTZM YYYY-MM-DD HH24:MI:SS.FF9'
    BINARY_FORMAT=BASE64
  ) 
```

And the following using 23.12.2:
```
✗ python test_sqlglot.py       
Traceback (most recent call last):
  File "/Users/dangoldin/code/analysis/test_sqlglot.py", line 494, in <module>
    pq = parse_one(q, read="snowflake")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dangoldin/.virtualenvs/lib/python3.11/site-packages/sqlglot/__init__.py", line 139, in parse_one
    result = dialect.parse(sql, **opts)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dangoldin/.virtualenvs/lib/python3.11/site-packages/sqlglot/dialects/dialect.py", line 506, in parse
    return self.parser(**opts).parse(self.tokenize(sql), sql)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dangoldin/.virtualenvs/lib/python3.11/site-packages/sqlglot/parser.py", line 1175, in parse
    return self._parse(
           ^^^^^^^^^^^^
  File "/Users/dangoldin/.virtualenvs/lib/python3.11/site-packages/sqlglot/parser.py", line 1241, in _parse
    expressions.append(parse_method(self))
                       ^^^^^^^^^^^^^^^^^^
  File "/Users/dangoldin/.virtualenvs/lib/python3.11/site-packages/sqlglot/parser.py", line 1470, in _parse_statement
    return self.STATEMENT_PARSERS[self._prev.token_type](self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dangoldin/.virtualenvs/lib/python3.11/site-packages/sqlglot/parser.py", line 631, in <lambda>
    TokenType.COPY: lambda self: self._parse_copy(),
                                 ^^^^^^^^^^^^^^^^^^
  File "/Users/dangoldin/.virtualenvs/lib/python3.11/site-packages/sqlglot/parser.py", line 6363, in _parse_copy
    files = self._parse_csv(self._parse_conjunction)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dangoldin/.virtualenvs/lib/python3.11/site-packages/sqlglot/parser.py", line 5649, in _parse_csv
    parse_result = parse_method()
                   ^^^^^^^^^^^^^^
  File "/Users/dangoldin/.virtualenvs/lib/python3.11/site-packages/sqlglot/parser.py", line 3808, in _parse_conjunction
    return self._parse_tokens(self._parse_equality, self.CONJUNCTION)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dangoldin/.virtualenvs/lib/python3.11/site-packages/sqlglot/parser.py", line 5663, in _parse_tokens
    this = parse_method()
           ^^^^^^^^^^^^^^
  File "/Users/dangoldin/.virtualenvs/lib/python3.11/site-packages/sqlglot/parser.py", line 3811, in _parse_equality
    return self._parse_tokens(self._parse_comparison, self.EQUALITY)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dangoldin/.virtualenvs/lib/python3.11/site-packages/sqlglot/parser.py", line 5670, in _parse_tokens
    expression=parse_method(),
               ^^^^^^^^^^^^^^
  File "/Users/dangoldin/.virtualenvs/lib/python3.11/site-packages/sqlglot/parser.py", line 3814, in _parse_comparison
    return self._parse_tokens(self._parse_range, self.COMPARISON)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dangoldin/.virtualenvs/lib/python3.11/site-packages/sqlglot/parser.py", line 5663, in _parse_tokens
    this = parse_method()
           ^^^^^^^^^^^^^^
  File "/Users/dangoldin/.virtualenvs/lib/python3.11/site-packages/sqlglot/parser.py", line 3817, in _parse_range
    this = this or self._parse_bitwise()
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dangoldin/.virtualenvs/lib/python3.11/site-packages/sqlglot/parser.py", line 3941, in _parse_bitwise
    this = self._parse_term()
           ^^^^^^^^^^^^^^^^^^
  File "/Users/dangoldin/.virtualenvs/lib/python3.11/site-packages/sqlglot/parser.py", line 3973, in _parse_term
    return self._parse_tokens(self._parse_factor, self.TERM)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dangoldin/.virtualenvs/lib/python3.11/site-packages/sqlglot/parser.py", line 5663, in _parse_tokens
    this = parse_method()
           ^^^^^^^^^^^^^^
  File "/Users/dangoldin/.virtualenvs/lib/python3.11/site-packages/sqlglot/parser.py", line 3977, in _parse_factor
    this = parse_method()
           ^^^^^^^^^^^^^^
  File "/Users/dangoldin/.virtualenvs/lib/python3.11/site-packages/sqlglot/parser.py", line 3998, in _parse_unary
    return self._parse_at_time_zone(self._parse_type())
                                    ^^^^^^^^^^^^^^^^^^
  File "/Users/dangoldin/.virtualenvs/lib/python3.11/site-packages/sqlglot/parser.py", line 4020, in _parse_type
    this = self._parse_column()
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/dangoldin/.virtualenvs/lib/python3.11/site-packages/sqlglot/parser.py", line 4220, in _parse_column
    this = self._parse_column_reference()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dangoldin/.virtualenvs/lib/python3.11/site-packages/sqlglot/parser.py", line 4224, in _parse_column_reference
    this = self._parse_field()
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/dangoldin/.virtualenvs/lib/python3.11/site-packages/sqlglot/parser.py", line 4347, in _parse_field
    field = self._parse_primary() or self._parse_function(
            ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dangoldin/.virtualenvs/lib/python3.11/site-packages/sqlglot/parser.py", line 4330, in _parse_primary
    self._match_r_paren(expression=this)
  File "/Users/dangoldin/.virtualenvs/lib/python3.11/site-packages/sqlglot/parser.py", line 6196, in _match_r_paren
    self.raise_error("Expecting )")
  File "/Users/dangoldin/.virtualenvs/lib/python3.11/site-packages/sqlglot/parser.py", line 1285, in raise_error
    raise error
sqlglot.errors.ParseError: Expecting ). Line 5, Col: 17.
  
copy into temp FROM @random_stage/path/
FILE_FORMAT = (
    TYPE=CSV
    FIELD_DELIMITER='|'
    NULL_IF=()
    FIELD_OPTIONALLY_ENCLOSED_BY='"'
    TIMESTAMP_FORMAT='TZHTZM YYYY-MM-DD HH24
```

**Official Documentation**
Please include links to official SQL documentation related to your issue.

**Comment by georgesittas** [comment]
Sorry for the trouble @dangoldin, this was an oversight on our end. Should have deployed a minor version. We'll fix this soon and look into deploying a patch.

**Comment by dangoldin** [comment]
All good and appreciate the responsiveness. I just fell back to 23.12.1 in my code and would attempt a fix here but haven't been keeping up with the changes here so it was quicker to quickly file this.

**Comment by georgesittas** [comment]
No worries. This is probably an edge case, because there _is_ some [logic](https://github.com/tobymao/sqlglot/commit/d2a6f16c35cbe355932d0e0eab2fc6ba096d8a97#diff-63eb8dd82d3561bc414e3e13cf59516bd6584c5766a10072157a8a5aee4ad85fR6370-R6372) that tries to parse this as a command, so it fails somewhere in between.

**Comment by georgesittas** [comment]
FYI @dangoldin just deployed v23.13.1

**Comment by dangoldin** [comment]
Awesome! Thanks for the quick turn around on this.

**Comment by marianysilva** [comment]
Hey @georgesittas I had the same message error but with REMOVE SQL clausula. 

`REMOVE @STAGE_NAME/path/path` contains unsupported syntax. Falling back to parsing as a 'Command'.

![Screenshot 2024-05-14 at 14 58 05](https://github.com/tobymao/sqlglot/assets/97555693/23481262-b744-47c7-a151-2ca00e5a3b7e)

**Comment by georgesittas** [comment]
This is expected, `REMOVE` is unsupported syntax.

**Comment by marianysilva** [comment]
[Snowflake examples](https://docs.snowflake.com/en/sql-reference/sql/remove#examples)

**Comment by georgesittas** [comment]
You're right, apologies for not clarifying. I meant that this statement is not supported by SQLGlot.

**Comment by marianysilva** [comment]
TY ❤️ 💻

**Comment by marianysilva** [comment]
Oh, okay. Do you know if SQLGlot has plans to support it? It seems we already have some support to REMOVE [here](https://github.com/tobymao/sqlglot/pull/2825/files)

**Comment by georgesittas** [comment]
We don't plan to do this, but well-crafted & tested PRs are welcome.
