### ISSUE TITLE
Unable to parse Trino WITH FUNCTION clause

### ISSUE THREAD

**Issue by john-bodley** [tobymao/sqlglot#3432]
**Before you file an issue**
- [x] Make sure you specify the "read" dialect eg. `parse_one(sql, read="spark")`
- [ ] Make sure you specify the "write" dialect eg. `ast.sql(dialect="duckdb")`
- [x] Check if the issue still exists on main

**Fully reproducible code snippet**

```python
>>> from sqlglot import parse_one
>>> from textwrap import dedent
>>>
>>> parse_one(
...     sql=dedent(
...         """
...         WITH
...            FUNCTION answer()
...            RETURNS BIGINT
...            RETURN 42
...            SELECT 'The answer is ' || CAST(answer() as VARCHAR);
...         -- The answer is 42
...         """
...     ),
...     dialect="trino",
... )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/johnbodley/repos/github.com/sqlglot/sqlglot/__init__.py", line 139, in parse_one
    result = dialect.parse(sql, **opts)
  File "/Users/johnbodley/repos/github.com/sqlglot/sqlglot/dialects/dialect.py", line 509, in parse
    return self.parser(**opts).parse(self.tokenize(sql), sql)
  File "/Users/johnbodley/repos/github.com/sqlglot/sqlglot/parser.py", line 1177, in parse
    return self._parse(
  File "/Users/johnbodley/repos/github.com/sqlglot/sqlglot/parser.py", line 1243, in _parse
    expressions.append(parse_method(self))
  File "/Users/johnbodley/repos/github.com/sqlglot/sqlglot/parser.py", line 1478, in _parse_statement
    expression = self._parse_set_operations(expression) if expression else self._parse_select()
  File "/Users/johnbodley/repos/github.com/sqlglot/sqlglot/parser.py", line 2502, in _parse_select
    cte = self._parse_with()
  File "/Users/johnbodley/repos/github.com/sqlglot/sqlglot/parser.py", line 2608, in _parse_with
    expressions.append(self._parse_cte())
  File "/Users/johnbodley/repos/github.com/sqlglot/sqlglot/parser.py", line 2635, in _parse_cte
    this=self._parse_wrapped(self._parse_statement),
  File "/Users/johnbodley/repos/github.com/sqlglot/sqlglot/parser.py", line 5704, in _parse_wrapped
    self.raise_error("Expecting (")
  File "/Users/johnbodley/repos/github.com/sqlglot/sqlglot/parser.py", line 1287, in raise_error
    raise error
sqlglot.errors.ParseError: Expecting (. Line 3, Col: 16.
  
WITH
   FUNCTION answer()
   RETURNS BIGINT
   RETURN 42
   SELECT 'The answer is ' || CAST(answer() as VARCHAR);
-- The an
```

**Official Documentation**
Please include links to official SQL documentation related to your issue.

**Comment by tobymao** [comment]
we have no plans to implement this, but happy to assist you in getting a PR if you need this @john-bodley

**Comment by tobymao** [comment]
here's something similar, udf creation for bigquery

https://github.com/tobymao/sqlglot/blob/30f9d30d8ab3727a43b1e6f363f28631cbfa7f92/sqlglot/parser.py#L4498

**Comment by john-bodley** [comment]
@tobymao, regarding

> we have no plans to implement this

why not? Is there a clear spec in terms of what SQLGlot can/cannot parse?

**Comment by tobymao** [comment]
@john-bodley it's not high priority for us. we prioritize implementing regular sql statements. ddl and udfs and procs are not something that we as a core team are going to prioritize, but we're more than happy to help you if you need it, provided you implement a well documented, tested, and clean pr.
