### ISSUE TITLE
Oracle materialized views WITH READ ONLY has Invalid expression / Unexpected token / required keyword format

### ISSUE THREAD

**Issue by deebify** [tobymao/sqlglot#3635]
I am trying to parse some oracle views in sqlglot, some materialized view in oracle has a keyword WITH READ ONLY at the end of the view to indicate that view can't be updated, with use it a lot for many views. The errors are vary sometimes I see `required keyword format` and for other views I encounter  `Invalid expression / Unexpected token`

https://docs.oracle.com/cd/B13789_01/server.101/b10759/statements_8004.htm

**WITH READ ONLY
Specify WITH READ ONLY to indicate that the table or view cannot be updated.**

Example: 

```
import sqlglot

res = sqlglot.transpile(
    ''' 
      select * from dual
      with read only
    ''''', read="oracle", write="oracle")[0]

print(res)
```

Traceback:
```

Traceback (most recent call last):
  File "/Users/deeb/PycharmProjects/datahub_app/parse.py", line 3, in <module>
    res = sqlglot.transpile(
          ^^^^^^^^^^^^^^^^^^
  File "/Users/deeb/anaconda3/lib/python3.11/site-packages/sqlglot/__init__.py", line 177, in transpile
    for expression in parse(sql, read, error_level=error_level)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/deeb/anaconda3/lib/python3.11/site-packages/sqlglot/__init__.py", line 102, in parse
    return Dialect.get_or_raise(read or dialect).parse(sql, **opts)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/deeb/anaconda3/lib/python3.11/site-packages/sqlglot/dialects/dialect.py", line 512, in parse
    return self.parser(**opts).parse(self.tokenize(sql), sql)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/deeb/anaconda3/lib/python3.11/site-packages/sqlglot/parser.py", line 1246, in parse
    return self._parse(
           ^^^^^^^^^^^^
  File "/Users/deeb/anaconda3/lib/python3.11/site-packages/sqlglot/parser.py", line 1318, in _parse
    self.raise_error("Invalid expression / Unexpected token")
  File "/Users/deeb/anaconda3/lib/python3.11/site-packages/sqlglot/parser.py", line 1359, in raise_error
    raise error
sqlglot.errors.ParseError: Invalid expression / Unexpected token. Line 3, Col: 4.
   
select * from dual
with read only

```

**Comment by deebify** [comment]
@VaggelisD It's allowed in Oracle you can specify to indicate table or view. 

There's another one  **WITH CHECK OPTION** which is used in subquery. 

Ref: https://docs.oracle.com/en/database/oracle/oracle-database/23/sqlrf/SELECT.html
