### ISSUE TITLE
mixing comments in sql can break parsing

### ISSUE THREAD

**Issue by deebify** [tobymao/sqlglot#3644]
We have views that has many comments inside the view itself, different comments style `--` or `/**/`

If the views contains mixing of these comments style specially if you comment inside `( )` it will break the parsing. That's why it returns error that expecting end of parentheses `)`, If I remove the comment myself it will parse the query. 

```
import sqlglot

res = sqlglot.transpile('''
SELECT  
      my_id_key,
      (NVL(a,0) + NVL(b,0) +
       /*NVL(c,0) +*/ 
       NVL(d,0) 
       /*+ NVL(e,0)*/ 
       ) sum_cols,
       --this is a comment
        NVL(z,0) last_col
FROM mytable
''', read="oracle", write="oracle")[0]

print(res)
```

the above code we have comment inside a column calculation and it breaks the parsing

Traceback:

```
Traceback (most recent call last):
  File "/Users/deeb/PycharmProjects/datahub_app/parse.py", line 3, in <module>
    res = sqlglot.transpile('''
          ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/deeb/anaconda3/lib/python3.11/site-packages/sqlglot/__init__.py", line 174, in transpile
    for expression in parse(sql, read, error_level=error_level)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/deeb/anaconda3/lib/python3.11/site-packages/sqlglot/__init__.py", line 99, in parse
    return Dialect.get_or_raise(read or dialect).parse(sql, **opts)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/deeb/anaconda3/lib/python3.11/site-packages/sqlglot/dialects/dialect.py", line 530, in parse
    return self.parser(**opts).parse(self.tokenize(sql), sql)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/deeb/anaconda3/lib/python3.11/site-packages/sqlglot/parser.py", line 1270, in parse
    return self._parse(
           ^^^^^^^^^^^^
  File "/Users/deeb/anaconda3/lib/python3.11/site-packages/sqlglot/parser.py", line 1339, in _parse
    expressions.append(parse_method(self))
                       ^^^^^^^^^^^^^^^^^^
  File "/Users/deeb/anaconda3/lib/python3.11/site-packages/sqlglot/parser.py", line 1574, in _parse_statement
    expression = self._parse_set_operations(expression) if expression else self._parse_select()
                                                                           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/deeb/anaconda3/lib/python3.11/site-packages/sqlglot/parser.py", line 2711, in _parse_select
    projections = self._parse_projections()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/deeb/anaconda3/lib/python3.11/site-packages/sqlglot/parser.py", line 2659, in _parse_projections
    return self._parse_expressions()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/deeb/anaconda3/lib/python3.11/site-packages/sqlglot/parser.py", line 6038, in _parse_expressions
    return self._parse_csv(self._parse_expression)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/deeb/anaconda3/lib/python3.11/site-packages/sqlglot/parser.py", line 5997, in _parse_csv
    parse_result = parse_method()
                   ^^^^^^^^^^^^^^
  File "/Users/deeb/anaconda3/lib/python3.11/site-packages/sqlglot/parser.py", line 3994, in _parse_expression
    return self._parse_alias(self._parse_assignment())
                             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/deeb/anaconda3/lib/python3.11/site-packages/sqlglot/parser.py", line 3997, in _parse_assignment
    this = self._parse_disjunction()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/deeb/anaconda3/lib/python3.11/site-packages/sqlglot/parser.py", line 4010, in _parse_disjunction
    return self._parse_tokens(self._parse_conjunction, self.DISJUNCTION)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/deeb/anaconda3/lib/python3.11/site-packages/sqlglot/parser.py", line 6006, in _parse_tokens
    this = parse_method()
           ^^^^^^^^^^^^^^
  File "/Users/deeb/anaconda3/lib/python3.11/site-packages/sqlglot/parser.py", line 4013, in _parse_conjunction
    return self._parse_tokens(self._parse_equality, self.CONJUNCTION)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/deeb/anaconda3/lib/python3.11/site-packages/sqlglot/parser.py", line 6006, in _parse_tokens
    this = parse_method()
           ^^^^^^^^^^^^^^
  File "/Users/deeb/anaconda3/lib/python3.11/site-packages/sqlglot/parser.py", line 4016, in _parse_equality
    return self._parse_tokens(self._parse_comparison, self.EQUALITY)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/deeb/anaconda3/lib/python3.11/site-packages/sqlglot/parser.py", line 6006, in _parse_tokens
    this = parse_method()
           ^^^^^^^^^^^^^^
  File "/Users/deeb/anaconda3/lib/python3.11/site-packages/sqlglot/parser.py", line 4019, in _parse_comparison
    return self._parse_tokens(self._parse_range, self.COMPARISON)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/deeb/anaconda3/lib/python3.11/site-packages/sqlglot/parser.py", line 6006, in _parse_tokens
    this = parse_method()
           ^^^^^^^^^^^^^^
  File "/Users/deeb/anaconda3/lib/python3.11/site-packages/sqlglot/parser.py", line 4022, in _parse_range
    this = this or self._parse_bitwise()
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/deeb/anaconda3/lib/python3.11/site-packages/sqlglot/parser.py", line 4156, in _parse_bitwise
    this = self._parse_term()
           ^^^^^^^^^^^^^^^^^^
  File "/Users/deeb/anaconda3/lib/python3.11/site-packages/sqlglot/parser.py", line 4188, in _parse_term
    return self._parse_tokens(self._parse_factor, self.TERM)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/deeb/anaconda3/lib/python3.11/site-packages/sqlglot/parser.py", line 6006, in _parse_tokens
    this = parse_method()
           ^^^^^^^^^^^^^^
  File "/Users/deeb/anaconda3/lib/python3.11/site-packages/sqlglot/parser.py", line 4192, in _parse_factor
    this = parse_method()
           ^^^^^^^^^^^^^^
  File "/Users/deeb/anaconda3/lib/python3.11/site-packages/sqlglot/parser.py", line 4217, in _parse_unary
    return self._parse_at_time_zone(self._parse_type())
                                    ^^^^^^^^^^^^^^^^^^
  File "/Users/deeb/anaconda3/lib/python3.11/site-packages/sqlglot/parser.py", line 4262, in _parse_type
    this = self._parse_column()
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/deeb/anaconda3/lib/python3.11/site-packages/sqlglot/parser.py", line 4506, in _parse_column
    this = self._parse_column_reference()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/deeb/anaconda3/lib/python3.11/site-packages/sqlglot/parser.py", line 4515, in _parse_column_reference
    this = self._parse_field()
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/deeb/anaconda3/lib/python3.11/site-packages/sqlglot/parser.py", line 4685, in _parse_field
    field = self._parse_primary() or self._parse_function(
            ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/deeb/anaconda3/lib/python3.11/site-packages/sqlglot/parser.py", line 4668, in _parse_primary
    self._match_r_paren(expression=this)
  File "/Users/deeb/anaconda3/lib/python3.11/site-packages/sqlglot/parser.py", line 6616, in _match_r_paren
    self.raise_error("Expecting )")
  File "/Users/deeb/anaconda3/lib/python3.11/site-packages/sqlglot/parser.py", line 1383, in raise_error
    raise error
sqlglot.errors.ParseError: Expecting ). Line 7, Col: 4.
  LECT  
      my_id_key,
      (NVL(a,0) + NVL(b,0) +
       /*NVL(c,0) +*/ 
       NVL(d,0) 
       /*+ NVL(e,0)*/ 
       ) sum_cols,
       --this is a comment
        NVL(z,0) last_col
FROM mytable
```

**Comment by deebify** [comment]
A more simpler example: 

```
SELECT id, ( a /*+b*/ + c) sum_cols
FROM my_table
```

the above query has a comment for `+b` only and because the comment is `/* */` the sequence `/*+` breaks the parsing.

**Comment by georgesittas** [comment]
This is out of scope for us right now. The issue is that hints are tokenized & parsed as if they were not comments:

```python
>>> import sqlglot
>>> sqlglot.parse_one("SELECT /*+ REPARTITION(100) */ x FROM tbl")
Select(
  hint=Hint(
    expressions=[
      Anonymous(
        this=REPARTITION,
        expressions=[
          Literal(this=100, is_string=False)])]),
  expressions=[
    Column(
      this=Identifier(this=x, quoted=False))],
  from=From(
    this=Table(
      this=Identifier(this=tbl, quoted=False))))
```

The alternative would be to treat hints as comments, but that's brittle because comments are attached on tokens based on heuristics and there may be edge cases where hints are lost because they're attached to the wrong token.

----

Perhaps you can do a regex substitution in order to include a space between `/*` and `+`. This will result in tokenizing this as a comment.
