### ISSUE TITLE
sqlglot.transpile from Snowflake to postgres raises error when Snowflake CONNECT BY is used in sql query

### ISSUE THREAD

**Issue by niklaslorenzatalligator** [tobymao/sqlglot#3716]
Hello everybody,

when the operator CONNECT_BY_ROOT is used in the sql query which should be parsed by sqlglot, python exits with an error. Probably because two column aliases were specified in the sql query. Example Query -> SELECT connect_by_root test AS test_column_alias"(first alias = connect_by_root test, second alias = ... AS test_column_alias)

Error Message:
Traceback (most recent call last):
  File "/Users/<user>/Projekte/qlik-dwh/test.py", line 125, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/<user>/Projekte/qlik-dwh/test.py", line 122, in main
    result = sqlglot.transpile("SELECT connect_by_root test AS test_column_alias", read="snowflake", write="postgres")[0]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/<user>/Projekte/qlik-dwh/.venv/lib/python3.11/site-packages/sqlglot/__init__.py", line 163, in transpile
    for expression in parse(sql, read, error_level=error_level)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/<user>/Projekte/qlik-dwh/.venv/lib/python3.11/site-packages/sqlglot/__init__.py", line 87, in parse
    return dialect.parse(sql, **opts)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/<user>/Projekte/qlik-dwh/.venv/lib/python3.11/site-packages/sqlglot/dialects/dialect.py", line 320, in parse
    return self.parser(**opts).parse(self.tokenize(sql), sql)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/<user>/Projekte/qlik-dwh/.venv/lib/python3.11/site-packages/sqlglot/parser.py", line 1009, in parse
    return self._parse(
           ^^^^^^^^^^^^
  File "/Users/<user>/Projekte/qlik-dwh/.venv/lib/python3.11/site-packages/sqlglot/parser.py", line 1078, in _parse
    self.raise_error("Invalid expression / Unexpected token")
  File "/Users/<user>/Projekte/qlik-dwh/.venv/lib/python3.11/site-packages/sqlglot/parser.py", line 1119, in raise_error
    raise error
sqlglot.errors.ParseError: Invalid expression / Unexpected token. Line 1, Col: 30.
  SELECT connect_by_root test AS test_column_alias

Code for reproducing error:
def main():
    result = sqlglot.transpile("SELECT connect_by_root test AS test_column_alias", read="snowflake", write="postgres")[0]

Snowflake Documentation for Connect BY:
https://docs.snowflake.com/en/sql-reference/constructs/connect-by

**Comment by georgesittas** [comment]
Hey @niklaslorenzatalligator, I can fix the Snowflake parsing, but I'm not sure how the `CONNECT_BY_ROOT` expression can be transpiled to Postgres. Any ideas?

**Comment by niklaslorenzatalligator** [comment]
Hello @georgesittas,

the expression CONNECT_BY_ROOT is actually new for me as well. I just learned about it in a project i am currently working on and I haven't used the expression myself previously.

Regarding the expression CONNECT_BY_ROOT and an possible equivalent in postgres, there seem to be table functions in postgres that need to be enabled manually. One of them is a connect_by function which appears to have similar attributes to connect_by in snowflake (relation, key, parentkey, order field, start with).
