### ISSUE TITLE
Transpile not working for postgres/duckdb

### ISSUE THREAD

**Issue by dioptre** [tobymao/sqlglot#3797]
sql = f"""
             SELECT TO_DATE(20220101, 'MM/DD/YYYY') AS order_month
        """ 
        sq = transpile(sql, read="postgres", write="duckdb")

fails to replace to_date, and won't execute on duck

**Comment by VaggelisD** [comment]
Hey @dioptre, thanks for reporting this. Does this query execute properly on Postgres? I can't get it to work locally, I had to (1) convert the date to a string literal and (2) bring it to the specified format before it finally worked:

```SQL
SELECT TO_DATE('01/01/2000', 'MM/DD/YYYY') AS order_month;
```

**Comment by chasebrignac** [comment]
Here to help explain for @dioptre 
```
import duckdb
from sqlalchemy import create_engine
import sqlparse

# Function to transpile SQL queries from Postgres to DuckDB
def transpile(sql, read, write):
    # This is a placeholder for the actual transpile logic,
    # which you may need to implement or adjust as per your needs.
    # For simplicity, we're assuming the SQL is compatible or needs minimal changes.
    # In a real scenario, you might need to parse and modify the SQL string accordingly.
    parsed_sql = sqlparse.format(sql, reindent=True)
    return parsed_sql.replace(read, write)

# Your SQL query
sql = """
SELECT TO_DATE('01/01/2000', 'MM/DD/YYYY') AS order_month;
"""
# Transpile the query from Postgres to DuckDB (for demonstration purposes)
transpiled_sql = transpile(sql, read="postgres", write="duckdb")

# Connect to DuckDB (in-memory database for demonstration)
con = duckdb.connect()

# Execute the transpiled SQL query
result = con.execute(transpiled_sql).fetchall()

# Print the result
print(result)
```
When using the correct string literal and specified format in sqlglot I get the following error:
```
(base) chase@chases-MacBook-Pro sourcetable-site % python3 test.py    
Traceback (most recent call last):
  File "/Users/chase/sourcetable-site/test.py", line 25, in <module>
    result = con.execute(transpiled_sql).fetchall()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
duckdb.duckdb.CatalogException: Catalog Error: Scalar Function with name to_date does not exist!
Did you mean "today"?
LINE 2: SELECT TO_DATE('01/01/2000', 'MM/DD/YYYY') AS...
               ^
(base) chase@chases-MacBook-Pro sourcetable-site %
```
Here is our version:
```
(base) chase@chases-MacBook-Pro sourcetable-site % duckdb --version
v0.10.2 1601d94f94
```
And here is the issue happening even in duckdb 1.0.0
```
(base) chase@chases-MacBook-Pro sourcetable-site % duckdb --version
v1.0.0 1f98600c2c
(base) chase@chases-MacBook-Pro sourcetable-site % python3 test.py    
Traceback (most recent call last):
  File "/Users/chase/sourcetable-site/test.py", line 25, in <module>
    result = con.execute(transpiled_sql).fetchall()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
duckdb.duckdb.CatalogException: Catalog Error: Scalar Function with name to_date does not exist!
Did you mean "today"?
LINE 2: SELECT TO_DATE('01/01/2000', 'MM/DD/YYYY') AS...
               ^
(base) chase@chases-MacBook-Pro sourcetable-site %
```

**Comment by chasebrignac** [comment]
Thank you for the fix @VaggelisD!
