### ISSUE TITLE
Valid SQL on clickhouse raises a keyword error due to bad naming

### ISSUE THREAD

**Issue by Barsoomx** [tobymao/sqlglot#3813]
We have a linkedin ads table with a column named 'like' in clickhouse, and sqlglot interprets this as a keyword, however the query itself is valid in clickhouse and correctly returns rows from the table
Probably also affects other keywords, haven't tested

**Full traceback:**
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/sqlglot/__init__.py", line 136, in parse_one
    result = dialect.parse(sql, **opts)
  File "/usr/local/lib/python3.10/dist-packages/sqlglot/dialects/dialect.py", line 695, in parse
    return self.parser(**opts).parse(self.tokenize(sql), sql)
  File "/usr/local/lib/python3.10/dist-packages/sqlglot/parser.py", line 1300, in parse
    return self._parse(
  File "/usr/local/lib/python3.10/dist-packages/sqlglot/parser.py", line 1369, in _parse
    expressions.append(parse_method(self))
  File "/usr/local/lib/python3.10/dist-packages/sqlglot/parser.py", line 1607, in _parse_statement
    expression = self._parse_set_operations(expression) if expression else self._parse_select()
  File "/usr/local/lib/python3.10/dist-packages/sqlglot/parser.py", line 2750, in _parse_select
    projections = self._parse_projections()
  File "/usr/local/lib/python3.10/dist-packages/sqlglot/parser.py", line 2698, in _parse_projections
    return self._parse_expressions()
  File "/usr/local/lib/python3.10/dist-packages/sqlglot/parser.py", line 6128, in _parse_expressions
    return self._parse_csv(self._parse_expression)
  File "/usr/local/lib/python3.10/dist-packages/sqlglot/parser.py", line 6082, in _parse_csv
    parse_result = parse_method()
  File "/usr/local/lib/python3.10/dist-packages/sqlglot/parser.py", line 4045, in _parse_expression
    return self._parse_alias(self._parse_assignment())
  File "/usr/local/lib/python3.10/dist-packages/sqlglot/dialects/clickhouse.py", line 431, in _parse_assignment
    this = super()._parse_assignment()
  File "/usr/local/lib/python3.10/dist-packages/sqlglot/parser.py", line 4048, in _parse_assignment
    this = self._parse_disjunction()
  File "/usr/local/lib/python3.10/dist-packages/sqlglot/parser.py", line 4061, in _parse_disjunction
    return self._parse_tokens(self._parse_conjunction, self.DISJUNCTION)
  File "/usr/local/lib/python3.10/dist-packages/sqlglot/parser.py", line 6096, in _parse_tokens
    this = parse_method()
  File "/usr/local/lib/python3.10/dist-packages/sqlglot/parser.py", line 4064, in _parse_conjunction
    return self._parse_tokens(self._parse_equality, self.CONJUNCTION)
  File "/usr/local/lib/python3.10/dist-packages/sqlglot/parser.py", line 6096, in _parse_tokens
    this = parse_method()
  File "/usr/local/lib/python3.10/dist-packages/sqlglot/parser.py", line 4067, in _parse_equality
    return self._parse_tokens(self._parse_comparison, self.EQUALITY)
  File "/usr/local/lib/python3.10/dist-packages/sqlglot/parser.py", line 6096, in _parse_tokens
    this = parse_method()
  File "/usr/local/lib/python3.10/dist-packages/sqlglot/parser.py", line 4070, in _parse_comparison
    return self._parse_tokens(self._parse_range, self.COMPARISON)
  File "/usr/local/lib/python3.10/dist-packages/sqlglot/parser.py", line 6096, in _parse_tokens
    this = parse_method()
  File "/usr/local/lib/python3.10/dist-packages/sqlglot/parser.py", line 4073, in _parse_range
    this = this or self._parse_bitwise()
  File "/usr/local/lib/python3.10/dist-packages/sqlglot/parser.py", line 4207, in _parse_bitwise
    this = self._parse_term()
  File "/usr/local/lib/python3.10/dist-packages/sqlglot/parser.py", line 4239, in _parse_term
    return self._parse_tokens(self._parse_factor, self.TERM)
  File "/usr/local/lib/python3.10/dist-packages/sqlglot/parser.py", line 6096, in _parse_tokens
    this = parse_method()
  File "/usr/local/lib/python3.10/dist-packages/sqlglot/parser.py", line 4243, in _parse_factor
    this = parse_method()
  File "/usr/local/lib/python3.10/dist-packages/sqlglot/parser.py", line 4268, in _parse_unary
    return self._parse_at_time_zone(self._parse_type())
  File "/usr/local/lib/python3.10/dist-packages/sqlglot/parser.py", line 4320, in _parse_type
    this = self._parse_column()
  File "/usr/local/lib/python3.10/dist-packages/sqlglot/parser.py", line 4585, in _parse_column
    this = self._parse_column_reference()
  File "/usr/local/lib/python3.10/dist-packages/sqlglot/parser.py", line 4594, in _parse_column_reference
    this = self._parse_field()
  File "/usr/local/lib/python3.10/dist-packages/sqlglot/parser.py", line 4770, in _parse_field
    field = self._parse_primary() or self._parse_function(
  File "/usr/local/lib/python3.10/dist-packages/sqlglot/dialects/clickhouse.py", line 543, in _parse_function
    expr = super()._parse_function(
  File "/usr/local/lib/python3.10/dist-packages/sqlglot/parser.py", line 4793, in _parse_function
    func = self._parse_function_call(
  File "/usr/local/lib/python3.10/dist-packages/sqlglot/parser.py", line 4857, in _parse_function_call
    args = self._parse_csv(lambda: self._parse_lambda(alias=alias))
  File "/usr/local/lib/python3.10/dist-packages/sqlglot/parser.py", line 6082, in _parse_csv
    parse_result = parse_method()
  File "/usr/local/lib/python3.10/dist-packages/sqlglot/parser.py", line 4857, in <lambda>
    args = self._parse_csv(lambda: self._parse_lambda(alias=alias))
  File "/usr/local/lib/python3.10/dist-packages/sqlglot/parser.py", line 4969, in _parse_lambda
    this = self._parse_select_or_expression(alias=alias)
  File "/usr/local/lib/python3.10/dist-packages/sqlglot/parser.py", line 6132, in _parse_select_or_expression
    self._parse_expression() if alias else self._parse_assignment()
  File "/usr/local/lib/python3.10/dist-packages/sqlglot/dialects/clickhouse.py", line 431, in _parse_assignment
    this = super()._parse_assignment()
  File "/usr/local/lib/python3.10/dist-packages/sqlglot/parser.py", line 4048, in _parse_assignment
    this = self._parse_disjunction()
  File "/usr/local/lib/python3.10/dist-packages/sqlglot/parser.py", line 4061, in _parse_disjunction
    return self._parse_tokens(self._parse_conjunction, self.DISJUNCTION)
  File "/usr/local/lib/python3.10/dist-packages/sqlglot/parser.py", line 6096, in _parse_tokens
    this = parse_method()
  File "/usr/local/lib/python3.10/dist-packages/sqlglot/parser.py", line 4064, in _parse_conjunction
    return self._parse_tokens(self._parse_equality, self.CONJUNCTION)
  File "/usr/local/lib/python3.10/dist-packages/sqlglot/parser.py", line 6096, in _parse_tokens
    this = parse_method()
  File "/usr/local/lib/python3.10/dist-packages/sqlglot/parser.py", line 4067, in _parse_equality
    return self._parse_tokens(self._parse_comparison, self.EQUALITY)
  File "/usr/local/lib/python3.10/dist-packages/sqlglot/parser.py", line 6096, in _parse_tokens
    this = parse_method()
  File "/usr/local/lib/python3.10/dist-packages/sqlglot/parser.py", line 4070, in _parse_comparison
    return self._parse_tokens(self._parse_range, self.COMPARISON)
  File "/usr/local/lib/python3.10/dist-packages/sqlglot/parser.py", line 6096, in _parse_tokens
    this = parse_method()
  File "/usr/local/lib/python3.10/dist-packages/sqlglot/parser.py", line 4077, in _parse_range
    expression = self.RANGE_PARSERS[self._prev.token_type](self, this)
  File "/usr/local/lib/python3.10/dist-packages/sqlglot/parser.py", line 52, in _parse_binary_range
    return self._parse_escape(self.expression(expr_type, this=this, expression=expression))
  File "/usr/local/lib/python3.10/dist-packages/sqlglot/parser.py", line 1433, in expression
    return self.validate_expression(instance)
  File "/usr/local/lib/python3.10/dist-packages/sqlglot/parser.py", line 1453, in validate_expression
    self.raise_error(error_message)
  File "/usr/local/lib/python3.10/dist-packages/sqlglot/parser.py", line 1413, in raise_error
    raise error
sqlglot.errors.ParseError: Required keyword: 'this' missing for <class 'sqlglot.expressions.Like'>. Line 1, Col: 31.
  select toFloat64OrDefault(like) AS likes from some_table
  ```

**Fully reproducible code snippet**

on [sqlglot v25.6.1](https://github.com/tobymao/sqlglot/releases/tag/v25.6.1)

```python
import sqlglot
result = sqlglot.parse_one("select toFloat64OrDefault(like) AS likes from some_table", dialect='clickhouse') # this crashes
result = sqlglot.parse_one("select toFloat64OrDefault(\"like\") as likes from some_table", dialect='clickhouse') # this works

# these are also valid but return the same error
result = sqlglot.parse_one("select like from some_table", dialect='clickhouse')
result = sqlglot.parse_one("select like as likes from some_table", dialect='clickhouse')
```

**Official Documentation**

Not applicable? I am aware that naming like this is counter-intuitive to say the least, but the query works and i think should be parsed correctly, if possible

Maybe also applicable to other dialects, but the issue i've encountered is on clickhouse

Raw SQL Query tested on two versions of CH and returned valid results
```
DBMS: ClickHouse (ver. 23.8.7.24)
DBMS: ClickHouse (ver. 24.3.5.46) 
```
Using datagrip:
```
Driver: ClickHouse JDBC Driver (ver. 0.6.0-patch5 (revision: 067ae0b), JDBC4.2)
```

**Comment by tvayi** [comment]
faced this issue too
