### ISSUE TITLE
[hive]Multi-insert will error when parse_one

### ISSUE THREAD

**Issue by hellozepp** [tobymao/sqlglot#3908]
**Before you file an issue**
- Make sure you specify the "read" dialect eg. `parse_one(sql, read="spark")`
- Make sure you specify the "write" dialect eg. `ast.sql(dialect="duckdb")`
- Check if the issue still exists on main
Hive SQL as follow:
```
-- sql 1
-- FROM tableName insert ...
FROM src
INSERT OVERWRITE TABLE dest1_n12 SELECT src.key, src.value WHERE src.key < 100 LIMIT 10
INSERT OVERWRITE TABLE dest2_n2 SELECT src.key, src.value WHERE src.key < 100 LIMIT 5

-- sql 2
-- FROM tableName ... join ...
FROM
 src a
LEFT OUTER JOIN
 srcpart b
ON (a.key = b.key AND b.ds = '2008-04-08')
SELECT a.key, a.value, b.key, b.value
WHERE a.key > 10 AND a.key < 20 AND b.key > 15 AND b.key < 25
```

When I parse the two SQL, I get the following exception:
```
sqlglot.parse_one(sql, read='hive', dialect='spark')


Traceback (most recent call last):
  File "/Users/zhanglin/PycharmProjects/sqlglot/parts/parse.py", line 22, in <module>
    raise ex
  File "/Users/zhanglin/PycharmProjects/sqlglot/parts/parse.py", line 17, in <module>
    test_parse_one(os.path.join(dir, '../' + file_name))
  File "/Users/zhanglin/PycharmProjects/sqlglot/parts/trans.py", line 49, in test_parse_one
    raise ex
  File "/Users/zhanglin/PycharmProjects/sqlglot/parts/trans.py", line 45, in test_parse_one
    parsed_sql = sqlglot.parse_one(sql, read=read, dialect=dialect)
  File "/Users/zhanglin/PycharmProjects/sqlglot/sqlglot/__init__.py", line 136, in parse_one
    result = dialect.parse(sql, **opts)
  File "/Users/zhanglin/PycharmProjects/sqlglot/sqlglot/dialects/dialect.py", line 879, in parse
    return self.parser(**opts).parse(self.tokenize(sql), sql)
  File "/Users/zhanglin/PycharmProjects/sqlglot/sqlglot/parser.py", line 1353, in parse
    return self._parse(
  File "/Users/zhanglin/PycharmProjects/sqlglot/sqlglot/parser.py", line 1425, in _parse
    self.raise_error("Invalid expression / Unexpected token")
  File "/Users/zhanglin/PycharmProjects/sqlglot/sqlglot/parser.py", line 1466, in raise_error
    raise error
sqlglot.errors.ParseError: Invalid expression / Unexpected token. Line 6, Col: 6.
  FROM
 src a
LEFT OUTER JOIN
 srcpart b
ON (a.key = b.key AND b.ds = '2008-04-08')
SELECT a.key, a.value, b.key, b.value
WHERE a.key > 10 AND a.key < 20 AND b.key > 15 AND b.key < 25
```

**Official Documentation**
[MultiTableInserts](https://cwiki.apache.org/confluence/display/Hive/LanguageManual+DML#LanguageManualDML-MultiTableInserts)

**Comment by georgesittas** [comment]
Appreciate the report, but this is out of [scope for us](https://github.com/tobymao/sqlglot/issues/2959#issuecomment-1942226933) right now. We welcome well-crafted & tested PRs.
