### ISSUE TITLE
Transpile Oracle "with core_sql as (select 1)" to ClickHouse failed to parse any statement following CTE

### ISSUE THREAD

**Issue by sleshJdev** [tobymao/sqlglot#3948]
**Fully reproducible code snippet**

```
import sqlglot
from sqlglot.dialects import Oracle, ClickHouse
sqlglot.transpile("with core_sql as (select 1)", read=Oracle, write=ClickHouse, comments=False)

Traceback (most recent call last):
    l = sqlglot.transpile(effective_sql, read=Oracle, write=ClickHouse, comments=False)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\venv\Lib\site-packages\sqlglot\__init__.py", line 174, in transpile
    for expression in parse(sql, read, error_level=error_level)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\venv\Lib\site-packages\sqlglot\__init__.py", line 99, in parse
    return Dialect.get_or_raise(read or dialect).parse(sql, **opts)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\venv\Lib\site-packages\sqlglot\dialects\dialect.py", line 894, in parse
    return self.parser(**opts).parse(self.tokenize(sql), sql)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\venv\Lib\site-packages\sqlglot\parser.py", line 1353, in parse
    return self._parse(
           ^^^^^^^^^^^^
  File "...\venv\Lib\site-packages\sqlglot\parser.py", line 1422, in _parse
    expressions.append(parse_method(self))
                       ^^^^^^^^^^^^^^^^^^
  File "...\venv\Lib\site-packages\sqlglot\parser.py", line 1660, in _parse_statement
    expression = self._parse_set_operations(expression) if expression else self._parse_select()
                                                                           ^^^^^^^^^^^^^^^^^^^^
  File "...\venv\Lib\site-packages\sqlglot\parser.py", line 2787, in _parse_select
    self.raise_error("Failed to parse any statement following CTE")
  File "...\venv\Lib\site-packages\sqlglot\parser.py", line 1466, in raise_error
    raise error
sqlglot.errors.ParseError: Failed to parse any statement following CTE. Line 1, Col: 27.
  with core_sql as (select 1) 

```

Version:
```
sqlglot==25.15.0
sqlglotrs==0.2.8
```

**Comment by georgesittas** [comment]
Is this valid Oracle SQL?

**Comment by georgesittas** [comment]
I don't think this is valid Oracle syntax, you need a query after the CTE definition. If you want the parser to be more lenient, you can set the `error_level` to `IGNORE`.
