### ISSUE TITLE
Correct ORACLE UPDATE SQL Command cause a crash in sqlglot.parse_one

### ISSUE THREAD

**Issue by fmoreira1966** [tobymao/sqlglot#404]
Hi Toby,

The following **correct ORACLE UPDATE SQL Command** causes a crash in **sqlglot.parse_one**

```
SQL_Update_Query_ = "UPDATE TABLE_TEST SET (NAME, AGE) = (SELECT NAME, Qty FROM (SELECT NAME, COUNT(*) Qty FROM TABLE_TEST2 WHERE NAME = 'MARY' GROUP BY NAME HAVING COUNT(*) >= 1 ORDER BY NAME ASC)) WHERE NAME = 'LAURA' AND AGE = '22'"

**sqlglot.parse_one(SQL_Update_Query_)**

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\femoreira\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlglot\__init__.py", line 67, in parse_one
    result = dialect.parse(sql, **opts)
  File "C:\Users\femoreira\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlglot\dialects\dialect.py", line 91, in parse
    return self.parser(**opts).parse(self.tokenizer.tokenize(sql), sql)
  File "C:\Users\femoreira\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlglot\parser.py", line 303, in parse
    return self._parse(
  File "C:\Users\femoreira\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlglot\parser.py", line 341, in _parse
    self.check_errors()
  File "C:\Users\femoreira\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlglot\parser.py", line 348, in check_errors
    raise error
sqlglot.errors.ParseError: Expecting ). Line 1, Col: 28.
  UPDATE TABLE_TEST SET (NAME[4m,[0m AGE) = (SELECT NAME, Qty FROM (SELECT NAME, COUNT(*) Qty FROM TABLE_TEST2 WHERE NAME = 'MARY' GROUP
```

Please, correct this issue so we can parse valid UPDATE SQL Commands with success.
In the following link you will find several valid UPDATE SQL Commands examples : [https://www.geeksengine.com/article/oracle-cross-table-update.html](https://www.geeksengine.com/article/oracle-cross-table-update.html)

Thanks in advance for your support.

Best Regards,
Fernando Moreira

**Comment by tobymao** [comment]
low priority as i have no use for oracle at the moment. happy to accept a pr.
