### ISSUE TITLE
Teradata COMPRESS Raises ParseError when Value Absent

### ISSUE THREAD

**Issue by thomascjohnson** [tobymao/sqlglot#4043]
Hi! I am a huge fan of this library. It's an incredible piece of work. I've found an issue with parsing Teradata and I want to make a contribution but I'm not sure what the best solution would be. Here's the issue:

**Before you file an issue**
- Make sure you specify the "read" dialect eg. `parse_one(sql, read="spark")`
Done - it's teradata
- Make sure you specify the "write" dialect eg. `ast.sql(dialect="duckdb")`
Not relevant.
- Check if the issue still exists on main
Just checked, present in main and from the pip repository.

**Fully reproducible code snippet**
```
import sqlglot

sql = """\
CREATE TABLE db.sometable,
(
    id INTEGER NOT NULL,
    valid_date DATE FORMAT 'YYYY-MM-DD',
    measurement INTEGER COMPRESS
);
"""

sqlglot.parse_one(sql, dialect='teradata')
```

Producing the error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tom/.local/lib/python3.11/site-packages/sqlglot/__init__.py", line 136, in parse_one
    result = dialect.parse(sql, **opts)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tom/.local/lib/python3.11/site-packages/sqlglot/dialects/dialect.py", line 894, in parse
    return self.parser(**opts).parse(self.tokenize(sql), sql)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tom/.local/lib/python3.11/site-packages/sqlglot/parser.py", line 1366, in parse
    return self._parse(
           ^^^^^^^^^^^^
  File "/home/tom/.local/lib/python3.11/site-packages/sqlglot/parser.py", line 1435, in _parse
    expressions.append(parse_method(self))
                       ^^^^^^^^^^^^^^^^^^
  File "/home/tom/.local/lib/python3.11/site-packages/sqlglot/parser.py", line 1667, in _parse_statement
    return self.STATEMENT_PARSERS[self._prev.token_type](self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tom/.local/lib/python3.11/site-packages/sqlglot/parser.py", line 758, in <lambda>
    TokenType.CREATE: lambda self: self._parse_create(),
                                   ^^^^^^^^^^^^^^^^^^^^
  File "/home/tom/.local/lib/python3.11/site-packages/sqlglot/parser.py", line 1820, in _parse_create
    this = self._parse_schema(this=table_parts)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tom/.local/lib/python3.11/site-packages/sqlglot/parser.py", line 5224, in _parse_schema
    args = self._parse_csv(lambda: self._parse_constraint() or self._parse_field_def())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tom/.local/lib/python3.11/site-packages/sqlglot/parser.py", line 6328, in _parse_csv
    parse_result = parse_method()
                   ^^^^^^^^^^^^^^
  File "/home/tom/.local/lib/python3.11/site-packages/sqlglot/parser.py", line 5224, in <lambda>
    args = self._parse_csv(lambda: self._parse_constraint() or self._parse_field_def())
                                                               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tom/.local/lib/python3.11/site-packages/sqlglot/parser.py", line 5229, in _parse_field_def
    return self._parse_column_def(self._parse_field(any_token=True))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tom/.local/lib/python3.11/site-packages/sqlglot/parser.py", line 5262, in _parse_column_def
    constraint = self._parse_column_constraint()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tom/.local/lib/python3.11/site-packages/sqlglot/parser.py", line 5382, in _parse_column_constraint
    kind=self.CONSTRAINT_PARSERS[self._prev.text.upper()](self),
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tom/.local/lib/python3.11/site-packages/sqlglot/parser.py", line 987, in <lambda>
    "COMPRESS": lambda self: self._parse_compress(),
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tom/.local/lib/python3.11/site-packages/sqlglot/parser.py", line 5304, in _parse_compress
    return self.expression(exp.CompressColumnConstraint, this=self._parse_bitwise())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tom/.local/lib/python3.11/site-packages/sqlglot/parser.py", line 1499, in expression
    return self.validate_expression(instance)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tom/.local/lib/python3.11/site-packages/sqlglot/parser.py", line 1519, in validate_expression
    self.raise_error(error_message)
  File "/home/tom/.local/lib/python3.11/site-packages/sqlglot/parser.py", line 1479, in raise_error
    raise error
sqlglot.errors.ParseError: Required keyword: 'this' missing for <class 'sqlglot.expressions.CompressColumnConstraint'>. Line 6, Col: 1.
  
    id INTEGER NOT NULL,
    valid_date DATE FORMAT 'YYYY-MM-DD',
    measurement INTEGER COMPRESS
);
```

**Official Documentation**
COMPRESS without an argument defaults to compressing NULL values [per the documentation here](https://docs.teradata.com/r/Enterprise_IntelliFlex_VMware/SQL-Data-Definition-Language-Syntax-and-Examples/Table-Statements/ALTER-TABLE/ALTER-TABLE-Syntax-Elements/Column-Attributes/COMPRESS):

> Use multivalue compression (MVC) for a set of distinct values in the column. You can also specify COMPRESS for a column in a volatile table. The default is to compress nulls only.

My suspicion is that I should specify a subclass of the expression class CompressColumnConstraint that does not require the `this` argument, and then add a method to the Teradata Parser class that uses this expression class. Is this correct?

**Comment by georgesittas** [comment]
Hey, appreciate the well-written report & kind words! :)

Your hunch is exactly right, but I'd suggest adding the parsing & generation logic in the base classes instead of just Teradata. Leaving this here too: https://github.com/tobymao/sqlglot/blob/main/posts/onboarding.md#onboarding.

**Comment by thomascjohnson** [comment]
Thanks! I will give that a read and then will fork and file a PR ASP.

**Comment by georgesittas** [comment]
Fixed by https://github.com/tobymao/sqlglot/pull/4045
