### ISSUE TITLE
Using singe quote as part of JSON object key leads to invalid SQL generation

### ISSUE THREAD

**Issue by jussihe-rec** [tobymao/sqlglot#4090]
**Before you file an issue**
- Make sure you specify the "read" dialect eg. `parse_one(sql, read="spark")` - ok
- Make sure you specify the "write" dialect eg. `ast.sql(dialect="duckdb")` - ok
- Check if the issue still exists on main - checked on sqlglot-25.20.2.dev5

**Overview**

When querying inside JSON object in Snowflake and referenced object's key contains `'` character the statements seems to be parsed correctly but when generating SQL the output is not valid (at least for snowflake and postgres dialects). Replacing single `'` in key name with escaped one: `''` resolves at least this case.

Object key can be referenced using `:` notation (e.g. `json_doc:"Customer's department"`) or using `get_path` function (`GET_PATH(PARSE_JSON(doc), '"Customer''s department"')`) - the result is the same.

**Fully reproducible code snippet**

```python
import sqlglot
sql_text = """select parse_json(doc):"Customer's department"::string as "dept" from json_tbl"""
print(sqlglot.parse_one(sql_text, dialect="snowflake").sql(dialect="snowflake"))
# SELECT CAST(GET_PATH(PARSE_JSON(doc), '["Customer's department"]') AS TEXT) AS "dept" FROM json_tbl

print(sqlglot.parse_one(sql_text, dialect="snowflake").sql(dialect="postgres"))
# SELECT CAST(JSON_EXTRACT_PATH(CAST(doc AS JSON), 'Customer's department') AS TEXT) AS "dept" FROM json_tbl
```
Expecting output for Snowflake to be 
```sql
SELECT CAST(GET_PATH(PARSE_JSON(doc), '["Customer''s department"]') AS TEXT) AS "dept" FROM json_tbl;
-- or
SELECT CAST(GET_PATH(PARSE_JSON(doc), '"Customer''s department"') AS TEXT) AS "dept" FROM json_tbl;
-- or, if not using GET_PATH function the original name without escaped quote can be used
SELECT CAST(PARSE_JSON(doc):"Customer's department" AS TEXT) AS "dept" FROM json_tbl;
```
And for PostgreSQL
```sql
SELECT CAST(JSON_EXTRACT_PATH(CAST(doc AS JSON), 'Customer''s department') AS TEXT) AS "dept" FROM json_tbl;
```

To test query with postgres:
```sql
create table json_tbl(doc jsonb);
insert into json_tbl values('{"Customer''s department": "Department A"}');

-- invalid query:
SELECT CAST(JSON_EXTRACT_PATH(CAST(doc AS JSON), 'Customer's department') AS TEXT) AS "dept" FROM json_tbl;
/*
ERROR:  syntax error at or near "s"
LINE 1: ...ST(JSON_EXTRACT_PATH(CAST(doc AS JSON), 'Customer's departme...
                                                             ^ 

SQL state: 42601
Character: 60
*/
-- valid query:
SELECT CAST(JSON_EXTRACT_PATH(CAST(doc AS JSON), 'Customer''s department') AS TEXT) AS "dept" FROM json_tbl;
```

**Official Documentation**
Please include links to official SQL documentation related to your issue.
- [Snowflake: Double quoted identifiers](https://docs.snowflake.com/en/sql-reference/identifiers-syntax#double-quoted-identifiers)
- [Snowflake: Single-quoted string constants](https://docs.snowflake.com/en/sql-reference/data-types-text#label-single-quoted-string-constants)

**Comment by jussihe-rec** [comment]
Thanks for the quick fix! This fixes the issue for me on Snowflake.

However, when quickly testing with postgres this still produces non-standard sql which breaks if parameter `standard_conforming_strings` is **on**, which it is by default. The resulting path identifier ('Customer\'s department') would need preceding E (as in E'Customer\'s department') or using "normal" way of doubling the quote ('Customer''s department'). Please see https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-BACKSLASH-TABLE 

But as said, not an issue for me currently.

**Comment by georgesittas** [comment]
Can you share a reproducible example @jussihe-rec?

**Comment by jussihe-rec** [comment]
Sure. Following the original example but trying to parse what transpiler produced:

```python
Python 3.12.5 (main, Aug  6 2024, 19:08:49) [Clang 15.0.0 (clang-1500.3.9.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlglot
>>> sql_text = """select parse_json(doc):"Customer's department"::string as "dept" from json_tbl"""
>>> pg_sql = sqlglot.parse_one(sql_text, dialect="snowflake").sql(dialect="postgres")
>>> print(pg_sql)
SELECT CAST(JSON_EXTRACT_PATH(CAST(doc AS JSON), 'Customer\'s department') AS TEXT) AS "dept" FROM json_tbl
>>> sqlglot.parse_one(pg_sql, dialect="postgres")
Traceback (most recent call last):
  File "[xxx]/gh/sqlglot/sqlglot/tokens.py", line 992, in tokenize
    self._scan()
  File "[xxx]/gh/sqlglot/sqlglot/tokens.py", line 1025, in _scan
    self._scan_keywords()
  File "[xxx]/gh/sqlglot/sqlglot/tokens.py", line 1156, in _scan_keywords
    if self._scan_string(word):
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "[xxx]/gh/sqlglot/sqlglot/tokens.py", line 1335, in _scan_string
    text = self._extract_string(end, raw_string=token_type == TokenType.RAW_STRING)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[xxx]/gh/sqlglot/sqlglot/tokens.py", line 1415, in _extract_string
    raise TokenError(f"Missing {delimiter} from {self._line}:{self._start}")
sqlglot.errors.TokenError: Missing ' from 1:72

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "[xxx]/gh/sqlglot/sqlglot/__init__.py", line 138, in parse_one
    result = dialect.parse(sql, **opts)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[xxx]/gh/sqlglot/sqlglot/dialects/dialect.py", line 919, in parse
    return self.parser(**opts).parse(self.tokenize(sql), sql)
                                     ^^^^^^^^^^^^^^^^^^
  File "[xxx]/gh/sqlglot/sqlglot/dialects/dialect.py", line 936, in tokenize
    return self.tokenizer.tokenize(sql)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[xxx]/gh/sqlglot/sqlglot/tokens.py", line 997, in tokenize
    raise TokenError(f"Error tokenizing '{context}'") from e
sqlglot.errors.TokenError: Error tokenizing 'r\'s department') AS TEXT) AS "dept" FROM json_tb'


# Manually fixing the query a bit (\' -> ''):

>>> fixed_pg_sql = """SELECT CAST(JSON_EXTRACT_PATH(CAST(doc AS JSON), 'Customer''s department') AS TEXT) AS "dept" FROM json_tbl"""
>>> sqlglot.parse_one(fixed_pg_sql, dialect="postgres")
Select(
  expressions=[
    Alias(
      this=Cast(
        this=JSONExtract(
          this=Cast(
            this=Column(
              this=Identifier(this=doc, quoted=False)),
            to=DataType(this=Type.JSON, nested=False)),
          expression=JSONPath(
            expressions=[
              JSONPathRoot(),
              JSONPathKey(this=Customer's department)]),
          only_json_types=False),
        to=DataType(this=Type.TEXT, nested=False)),
      alias=Identifier(this=dept, quoted=True))],
  from=From(
    this=Table(
      this=Identifier(this=json_tbl, quoted=False))))
```

And running queries on PostgreSQL 16 using pgAdmin:

```sql
create table json_tbl(doc jsonb);
insert into json_tbl values('{"Customer''s department": "Department A"}');

-- SQL produced by sqlglot:
SELECT CAST(JSON_EXTRACT_PATH(CAST(doc AS JSON), 'Customer\'s department') AS TEXT) AS "dept" FROM json_tbl;
/*
ERROR:  syntax error at or near "s"
LINE 1: ...T(JSON_EXTRACT_PATH(CAST(doc AS JSON), 'Customer\'s departme...
                                                             ^ 

SQL state: 42601
Character: 61
*/

-- Working examples:

SELECT CAST(JSON_EXTRACT_PATH(CAST(doc AS JSON), E'Customer\'s department') AS TEXT) AS "dept" FROM json_tbl;
--> "Department A"

SELECT CAST(JSON_EXTRACT_PATH(CAST(doc AS JSON), 'Customer''s department') AS TEXT) AS "dept" FROM json_tbl;
--> "Department A"

-- And when turning standard_conforming_strings off the current sqlglot query works
set standard_conforming_strings=off;
SELECT CAST(JSON_EXTRACT_PATH(CAST(doc AS JSON), 'Customer\'s department') AS TEXT) AS "dept" FROM json_tbl;

--> "Department A"
 
```

**Comment by georgesittas** [comment]
Got it, makes sense thanks. We'll take another look.
