### ISSUE TITLE
Snowflake SwapTable expression does not work with sqlglot.parse_one

### ISSUE THREAD

**Issue by WadeSeidule** [tobymao/sqlglot#4136]
```python
import sqlglot
from sqlglot.dialects import Snowflake

sql = "ALTER TABLE table1 SWAP WITH table2;"

# raises ValueError: Unsupported expression type SwapTable
print(sqlglot.parse_one(sql, dialect=Snowflake))

# does not raise
print(sqlglot.parse(sql, dialect=Snowflake))
```

Full Traceback:
```
Traceback (most recent call last):
  File "/Users/wadeseidule/dev/falcon/app/script/deleteme.py", line 31, in <module>
    main()
  File "/Users/wadeseidule/dev/falcon/app/script/deleteme.py", line 29, in main
    alter_swap_transpiler()
  File "/Users/wadeseidule/dev/falcon/app/script/deleteme.py", line 20, in alter_swap_transpiler
    print(sqlglot.parse_one(sql, dialect=Snowflake))
  File "/Users/wadeseidule/.pyenv/versions/falcon310/lib/python3.10/site-packages/sqlglot/expressions.py", line 582, in __str__
    return self.sql()
  File "/Users/wadeseidule/.pyenv/versions/falcon310/lib/python3.10/site-packages/sqlglot/expressions.py", line 607, in sql
    return Dialect.get_or_raise(dialect).generate(self, **opts)
  File "/Users/wadeseidule/.pyenv/versions/falcon310/lib/python3.10/site-packages/sqlglot/dialects/dialect.py", line 927, in generate
    return self.generator(**opts).generate(expression, copy=copy)
  File "/Users/wadeseidule/.pyenv/versions/falcon310/lib/python3.10/site-packages/sqlglot/generator.py", line 702, in generate
    sql = self.sql(expression).strip()
  File "/Users/wadeseidule/.pyenv/versions/falcon310/lib/python3.10/site-packages/sqlglot/generator.py", line 861, in sql
    sql = getattr(self, exp_handler_name)(expression)
  File "/Users/wadeseidule/.pyenv/versions/falcon310/lib/python3.10/site-packages/sqlglot/generator.py", line 3228, in alter_sql
    actions = self.expressions(expression, key="actions", flat=True)
  File "/Users/wadeseidule/.pyenv/versions/falcon310/lib/python3.10/site-packages/sqlglot/generator.py", line 3523, in expressions
    return sep.join(sql for sql in (self.sql(e) for e in expressions) if sql)
  File "/Users/wadeseidule/.pyenv/versions/falcon310/lib/python3.10/site-packages/sqlglot/generator.py", line 3523, in <genexpr>
    return sep.join(sql for sql in (self.sql(e) for e in expressions) if sql)
  File "/Users/wadeseidule/.pyenv/versions/falcon310/lib/python3.10/site-packages/sqlglot/generator.py", line 3523, in <genexpr>
    return sep.join(sql for sql in (self.sql(e) for e in expressions) if sql)
  File "/Users/wadeseidule/.pyenv/versions/falcon310/lib/python3.10/site-packages/sqlglot/generator.py", line 867, in sql
    raise ValueError(f"Unsupported expression type {expression.__class__.__name__}")
ValueError: Unsupported expression type SwapTable
```

**Official Documentation**
https://sqlglot.com/sqlglot/dialects/snowflake.html#Snowflake.Parser.ALTER_PARSERS

**Comment by VaggelisD** [comment]
Hey @WadeSeidule, thanks for reporting this. 

Generally, to get back the SQL you should call `.sql(<dialect>)` on the AST, e.g.:

```
>>> sqlglot.parse_one("ALTER TABLE t1 SWAP WITH t2;", dialect="snowflake").sql("snowflake")
'ALTER TABLE t1 SWAP WITH t2'
```

The error seems expected here because `exp.SwapTable` is Snowflake specific; Without the `.sql("snowflake")` call, SQLGlot will attempt to generate the SQL in our "base" dialect. Check out the [FAQ](https://github.com/tobymao/sqlglot?tab=readme-ov-file#faq) for more information.

It's interesting though why `parse_one` and `parse` are not behaving similarly in this case, will investigate this.

**Comment by WadeSeidule** [comment]
Thanks for looking into that @VaggelisD. Just to clarify I was not interested in getting back a sql string when calling `print` on the AST, but get the `repr` for the AST itself: (example from `print(sqlglot.parse(sql))`)
```python
[Alter(
  this=Table(
    this=Identifier(this=table1, quoted=False)),
  kind=TABLE,
  actions=[
    SwapTable(
      this=Table(
        this=Identifier(this=table2, quoted=False)))])]
```
 
Since `parse` and `parse_one` are dialect aware, to me it doesn't seem like the error should be expected. I can work around it regardless.

Thanks again for the response.

**Comment by VaggelisD** [comment]
@WadeSeidule Ah I see, you can get the `repr` directly i.e

```
ast = sqlglot.parse_one(...)
print(repr(ast))
```

The error you're getting is on the Generator module which responsible for turning the AST back to SQL, this is because `print(ast)` will attempt to stringify the AST. Since there's no direct `.sql(dialect)` call, it will attempt to use the "base" dialect which is not aware of the `SWAP TABLE` clause and that's the reason for this error:

```
  File "/Users/wadeseidule/.pyenv/versions/falcon310/lib/python3.10/site-packages/sqlglot/generator.py", line 867, in sql
    raise ValueError(f"Unsupported expression type {expression.__class__.__name__}")
ValueError: Unsupported expression type SwapTable
```

Let me know if that works.
