### ISSUE TITLE
MySQL Query failed to transpile

### ISSUE THREAD

**Issue by AhlamHani** [tobymao/sqlglot#4175]
```python
    sql = """
    CREATE TABLE IF NOT EXISTS example_table
    (
        id         SERIAL PRIMARY KEY,
        name       VARCHAR(100)        NOT NULL,
        age        INT CHECK (age > 0),
        email      VARCHAR(255) UNIQUE NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
    """
    queries = sqlglot.transpile(sql, read=sqlglot.dialects.dialect.Dialects.MYSQL)
```

## Logs:
```
/Users/ahlam.alhomaidat/workspace/venv/bin/python -X pycache_prefix=/Users/ahlam.alhomaidat/Library/Caches/JetBrains/IntelliJIdea2024.2/cpython-cache /Users/ahlam.alhomaidat/Library/Application Support/JetBrains/IntelliJIdea2024.2/plugins/python-ce/helpers/pydev/pydevd.py --module --multiprocess --qt-support=auto --client 127.0.0.1 --port 51642 --file module.main 
Connected to pydev debugger (build 242.23339.11)
2024-09-28 20:02:50,402 - root - INFO - Connection established to RDS instance: xxx
Traceback (most recent call last):
  File "/Users/xxx/Library/Application Support/JetBrains/IntelliJIdea2024.2/plugins/python-ce/helpers/pydev/pydevd.py", line 1587, in _exec
    runpy._run_module_as_main(module_name, alter_argv=False)
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/xxx/workspace/xxx/storage-shared-workflows/actions/analyzer/module/main.py", line 47, in <module>
    main()
  File "/Users/xxx/workspace/xxx/storage-shared-workflows/actions/analyzer/module/main.py", line 33, in main
    analyzer.parse()
  File "/Users/xxx/workspace/xxx/storage-shared-workflows/actions/analyzer/module/lib/sql_analyzer.py", line 20, in parse
    queries = sql.extract_queries(self.sql_content, engine=self.db.engine)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/workspace/xxx/storage-shared-workflows/actions/analyzer/module/lib/sql.py", line 37, in extract_queries
    statement = sql_format(statement, engine=engine)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/workspace/xxx/storage-shared-workflows/actions/analyzer/module/lib/sql.py", line 13, in sql_format
    queries = sqlglot.transpile(sql, **default_opts)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/workspace/venv/lib/python3.12/site-packages/sqlglot/__init__.py", line 177, in transpile
    for expression in parse(sql, read, error_level=error_level)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/workspace/venv/lib/python3.12/site-packages/sqlglot/__init__.py", line 102, in parse
    return Dialect.get_or_raise(read or dialect).parse(sql, **opts)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/workspace/venv/lib/python3.12/site-packages/sqlglot/dialects/dialect.py", line 919, in parse
    return self.parser(**opts).parse(self.tokenize(sql), sql)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/workspace/venv/lib/python3.12/site-packages/sqlglot/parser.py", line 1390, in parse
    return self._parse(
           ^^^^^^^^^^^^
  File "/Users/xxx/workspace/venv/lib/python3.12/site-packages/sqlglot/parser.py", line 1459, in _parse
    expressions.append(parse_method(self))
                       ^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/workspace/venv/lib/python3.12/site-packages/sqlglot/parser.py", line 1691, in _parse_statement
    return self.STATEMENT_PARSERS[self._prev.token_type](self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/workspace/venv/lib/python3.12/site-packages/sqlglot/parser.py", line 777, in <lambda>
    TokenType.CREATE: lambda self: self._parse_create(),
                                   ^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/workspace/venv/lib/python3.12/site-packages/sqlglot/parser.py", line 1846, in _parse_create
    this = self._parse_schema(this=table_parts)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/workspace/venv/lib/python3.12/site-packages/sqlglot/parser.py", line 5361, in _parse_schema
    self._match_r_paren()
  File "/Users/xxx/workspace/venv/lib/python3.12/site-packages/sqlglot/parser.py", line 7154, in _match_r_paren
    self.raise_error("Expecting )")
  File "/Users/xxx/workspace/venv/lib/python3.12/site-packages/sqlglot/parser.py", line 1503, in raise_error
    raise error
sqlglot.errors.ParseError: Expecting ). Line 4, Col: 18.
  -- Create an example table for PostgreSQL
CREATE TABLE IF NOT EXISTS example_table
(
    id         SERIAL PRIMARY KEY,
    name       VARCHAR(100)        NOT NULL,
    age        INT CHECK (age > 0),
    e

Process finished with exit code 1
```

**Comment by AhlamHani** [comment]
Actually the query was written for postgres not MySQL, so closing this issue
