### ISSUE TITLE
Failed to parse sql `SELECT sql_calc_found_rows wp_posts.ID FROM wp_posts`

### ISSUE THREAD

**Issue by asdfsx** [tobymao/sqlglot#4236]
I'm new to sqlglot. Now I'm using `sqlglot==25.24.5`, and trying to parse some sql from mysql, but sql with `sql_calc_found_rows` are all failed.

```
Python 3.12.4 (main, Jun  6 2024, 18:26:44) [Clang 15.0.0 (clang-1500.1.0.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from sqlglot import parse_one
>>> sql = "SELECT sql_calc_found_rows wp_posts.ID FROM wp_posts WHERE 1=1  AND ((wp_posts.post_type = 'post' AND (wp_posts.post_status = 'publish' OR wp_posts.post_status = 'private')))"
>>> parse_one(sql, read="mysql")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/sunxia/git-projects/gitlab.ipplus360.net/sunxia/research/.venv/lib/python3.12/site-packages/sqlglot/__init__.py", line 139, in parse_one
    result = dialect.parse(sql, **opts)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sunxia/git-projects/gitlab.ipplus360.net/sunxia/research/.venv/lib/python3.12/site-packages/sqlglot/dialects/dialect.py", line 919, in parse
    return self.parser(**opts).parse(self.tokenize(sql), sql)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sunxia/git-projects/gitlab.ipplus360.net/sunxia/research/.venv/lib/python3.12/site-packages/sqlglot/parser.py", line 1398, in parse
    return self._parse(
           ^^^^^^^^^^^^
  File "/Users/sunxia/git-projects/gitlab.ipplus360.net/sunxia/research/.venv/lib/python3.12/site-packages/sqlglot/parser.py", line 1470, in _parse
    self.raise_error("Invalid expression / Unexpected token")
  File "/Users/sunxia/git-projects/gitlab.ipplus360.net/sunxia/research/.venv/lib/python3.12/site-packages/sqlglot/parser.py", line 1511, in raise_error
    raise error
sqlglot.errors.ParseError: Invalid expression / Unexpected token. Line 1, Col: 36.
  SELECT sql_calc_found_rows wp_posts.ID FROM wp_posts WHERE 1=1  AND ((wp_posts.post_type = 'post' AND (wp_posts.post_status = 'publish' 
>>> 
```

Is there any suggestions?

**Comment by georgesittas** [comment]
Nvm, it's documented [here](https://dev.mysql.com/doc/refman/8.4/en/information-functions.html#function_found-rows).
