### ISSUE TITLE
Add Support for Teradata Conversion Syntax

### ISSUE THREAD

**Issue by thomascjohnson** [tobymao/sqlglot#4380]
# Teradata Conversion Syntax in sqlglot

sqlglot fails to parse [Teradata's conversion syntax](https://docs.teradata.com/r/Enterprise_IntelliFlex_VMware/SQL-Data-Types-and-Literals/Data-Type-Conversions/Character-to-Numeric-Conversion/Teradata-Character-to-Numeric-Conversion-Syntax). This is not an ANSI SQL standard compliant syntax and it has some complexities that make it challenging to implement. I have started to implement the change in [this branch](http://github.com/thomascjohnson/sqlglot/tree/teradata-conversion), but there is still work to do. 

## Overview

The conversion syntax is based on being able to convert the type of an expression, much like the `CAST` function – they are even presented side-by-side in the documentation. For example, to convert the string `'2024'` to integer, the syntax would be:

```
SELECT '2024' (INTEGER)
```

or to convert `'2024-11-11'` to date:

```
SELECT '2024-11-11' (DATE)
```

Non-literal expressions can be converted too, and they can be chained. Suppose in a table `orders` you have three character columns – `year`, `month`, `day` – corresponding to YYYY, MM, DD integer values stored as characters. The following would turn their combined values into a date:

```
SELECT (
  (year (INTEGER, FORMAT '9999')) || '-' || 
  (month (INTEGER, FORMAT '99')) || '-' || 
  (day (INTEGER, FORMAT '99'))
) (DATE)
FROM orders
```

### Details

The conversion syntax generally has this pattern across input/output type combinations:

```
input_expression (
  data_attribute,
  output_type,
  data_attribute
)
```

The `data_attribute` can be one of the following expressions:

- `FORMAT`
- `NAMED`
- `TITLE`

The leading or trailing `data_attribute` can be any of these as long as an expression is not supplied twice. The [TITLE](https://docs.teradata.com/r/Enterprise_IntelliFlex_VMware/SQL-Data-Types-and-Literals/Data-Type-Formats-and-Format-Phrases/TITLE) and [NAMED](https://docs.teradata.com/r/Enterprise_IntelliFlex_VMware/SQL-Data-Types-and-Literals/Data-Type-Formats-and-Format-Phrases/NAMED) expressions can also be used on their own.

For example, these are all valid conversions:

```
SELECT 'test' (TITLE 'test_col'); -- TITLE expressions are followed by a string
SELECT 'test' (NAMED test_col); -- NAMED expressions are followed by an identifier
SELECT '2024' (NAMED 'year', INTEGER, FORMAT '9999');
SELECT '2024' (INTEGER, FORMAT '9999', NAMED 'year');
SELECT '2024' (INTEGER, FORMAT '9999', TITLE year);
SELECT '2024' (TITLE year, INTEGER, FORMAT '9999');
SELECT '2024-11-11' (DATE, TITLE order_date);
SELECT '2024-11-11' (TITLE order_date, DATE);
SELECT '2024-11-11' (DATE);
SELECT year (INTEGER, FORMAT '9999') FROM orders;
SELECT year (NAMED 'year_int', INTEGER, FORMAT '9999') FROM orders;
```

To summarize, we can have the following cases:

First | Second | Third
-- | -- | --
TITLE | DATA TYPE | FORMAT
TITLE | DATA TYPE | NAMED
TITLE | DATA TYPE |  
TITLE | NAMED |  
TITLE |   |  
NAMED | DATA TYPE | FORMAT
NAMED | DATA TYPE | TITLE
NAMED | DATA TYPE |  
NAMED | TITLE |  
NAMED |   |  
DATA TYPE | FORMAT |  
DATA TYPE | NAMED |  
DATA TYPE | TITLE |  
DATA TYPE | |

### Complications

<details><summary>The following cases work based on the teradata-conversion branch in my sqlglot fork</summary>

```
>>> import sqlglot
>>> sqlglot.parse_one("SELECT '2024' (INTEGER, FORMAT '9999')", dialect="teradata")
Select(
  expressions=[
    Conversion(
      this=Literal(this=2024, is_string=True),
      to=DataType(this=Type.INT, nested=False),
      trailing_attribute=Literal(this=9999, is_string=True))])
>>> sqlglot.parse_one("SELECT '2024' (TITLE 'x', INTEGER, FORMAT '9999')", dialect="teradata")
Select(
  expressions=[
    Conversion(
      this=Literal(this=2024, is_string=True),
      to=DataType(this=Type.INT, nested=False),
      leading_attribute=Title(
        value=Literal(this=x, is_string=True)),
      trailing_attribute=Literal(this=9999, is_string=True))])
>>> sqlglot.parse_one("SELECT '2024' (INTEGER, FORMAT '9999') (CHAR(4))", dialect="teradata")
Select(
  expressions=[
    Conversion(
      this=Conversion(
        this=Literal(this=2024, is_string=True),
        to=DataType(this=Type.INT, nested=False),
        trailing_attribute=Literal(this=9999, is_string=True)),
      to=DataType(
        this=Type.CHAR,
        expressions=[
          DataTypeParam(
            this=Literal(this=4, is_string=False))],
        nested=False))])
>>> sqlglot.parse_one("SELECT 1 FROM x WHERE ('2024' (INTEGER, FORMAT '9999') (CHAR(4))) = '2024'", dialect="teradata")
Select(
  expressions=[
    Literal(this=1, is_string=False)],
  from=From(
    this=Table(
      this=Identifier(this=x, quoted=False))),
  where=Where(
    this=EQ(
      this=Paren(
        this=Conversion(
          this=Conversion(
            this=Literal(this=2024, is_string=True),
            to=DataType(this=Type.INT, nested=False),
            trailing_attribute=Literal(this=9999, is_string=True)),
          to=DataType(
            this=Type.CHAR,
            expressions=[
              DataTypeParam(
                this=Literal(this=4, is_string=False))],
            nested=False))),
      expression=Literal(this=2024, is_string=True))))
>>> sqlglot.parse_one("SELECT CAST(x AS INTEGER FORMAT '9999') FROM a", dialect="teradata")
Select(
  expressions=[
    Cast(
      this=Column(
        this=Identifier(this=x, quoted=False)),
      to=DataType(this=Type.INT, nested=False),
      format=Literal(this=9999, is_string=True))],
  from=From(
    this=Table(
      this=Identifier(this=a, quoted=False))))
>>> sqlglot.parse_one("SELECT CAST(x AS INTEGER FORMAT '9999') (CHAR(4)) FROM a", dialect="teradata")
Select(
  expressions=[
    Conversion(
      this=Cast(
        this=Column(
          this=Identifier(this=x, quoted=False)),
        to=DataType(this=Type.INT, nested=False),
        format=Literal(this=9999, is_string=True)),
      to=DataType(
        this=Type.CHAR,
        expressions=[
          DataTypeParam(
            this=Literal(this=4, is_string=False))],
        nested=False))],
  from=From(
    this=Table(
      this=Identifier(this=a, quoted=False))))
>>> sqlglot.parse_one("SELECT y FROM a WHERE '2024' = (CAST(x AS INTEGER FORMAT '9999') (CHAR(4)))", dialect="teradata")
Select(
  expressions=[
    Column(
      this=Identifier(this=y, quoted=False))],
  from=From(
    this=Table(
      this=Identifier(this=a, quoted=False))),
  where=Where(
    this=EQ(
      this=Literal(this=2024, is_string=True),
      expression=Paren(
        this=Conversion(
          this=Cast(
            this=Column(
              this=Identifier(this=x, quoted=False)),
            to=DataType(this=Type.INT, nested=False),
            format=Literal(this=9999, is_string=True)),
          to=DataType(
            this=Type.CHAR,
            expressions=[
              DataTypeParam(
                this=Literal(this=4, is_string=False))],
            nested=False))))))
```

</details> 

However, we can see that with an identifier expression like this:

```
SELECT x (INTEGER, FORMAT '9999') (CHAR(4))
```

<details><summary>it fails.</summary>

```
>>> sqlglot.parse_one("SELECT x (INTEGER, FORMAT '9999') (CHAR(4))", dialect="teradata")   
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Repositories/sqlglot/sqlglot/__init__.py", line 139, in parse_one
    result = dialect.parse(sql, **opts)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Repositories/sqlglot/sqlglot/dialects/dialect.py", line 921, in parse
    return self.parser(**opts).parse(self.tokenize(sql), sql)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Repositories/sqlglot/sqlglot/parser.py", line 1417, in parse
    return self._parse(
           ^^^^^^^^^^^^
  File "/Repositories/sqlglot/sqlglot/parser.py", line 1486, in _parse
    expressions.append(parse_method(self))
                       ^^^^^^^^^^^^^^^^^^
  File "/Repositories/sqlglot/sqlglot/parser.py", line 1724, in _parse_statement
    expression = self._parse_set_operations(expression) if expression else self._parse_select()
                                                                           ^^^^^^^^^^^^^^^^^^^^
  File "/Repositories/sqlglot/sqlglot/parser.py", line 2997, in _parse_select
    projections = self._parse_projections()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Repositories/sqlglot/sqlglot/parser.py", line 2937, in _parse_projections
    return self._parse_expressions()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Repositories/sqlglot/sqlglot/parser.py", line 6665, in _parse_expressions
    return self._parse_csv(self._parse_expression)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Repositories/sqlglot/sqlglot/parser.py", line 6619, in _parse_csv
    parse_result = parse_method()
                   ^^^^^^^^^^^^^^
  File "/Repositories/sqlglot/sqlglot/parser.py", line 4401, in _parse_expression
    return self._parse_alias(self._parse_assignment())
                             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Repositories/sqlglot/sqlglot/parser.py", line 4404, in _parse_assignment
    this = self._parse_disjunction()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Repositories/sqlglot/sqlglot/parser.py", line 4425, in _parse_disjunction
    return self._parse_tokens(self._parse_conjunction, self.DISJUNCTION)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Repositories/sqlglot/sqlglot/parser.py", line 6633, in _parse_tokens
    this = parse_method()
           ^^^^^^^^^^^^^^
  File "/Repositories/sqlglot/sqlglot/parser.py", line 4428, in _parse_conjunction
    return self._parse_tokens(self._parse_equality, self.CONJUNCTION)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Repositories/sqlglot/sqlglot/parser.py", line 6633, in _parse_tokens
    this = parse_method()
           ^^^^^^^^^^^^^^
  File "/Repositories/sqlglot/sqlglot/parser.py", line 4431, in _parse_equality
    return self._parse_tokens(self._parse_comparison, self.EQUALITY)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Repositories/sqlglot/sqlglot/parser.py", line 6633, in _parse_tokens
    this = parse_method()
           ^^^^^^^^^^^^^^
  File "/Repositories/sqlglot/sqlglot/parser.py", line 4434, in _parse_comparison
    return self._parse_tokens(self._parse_range, self.COMPARISON)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Repositories/sqlglot/sqlglot/parser.py", line 6633, in _parse_tokens
    this = parse_method()
           ^^^^^^^^^^^^^^
  File "/Repositories/sqlglot/sqlglot/parser.py", line 4437, in _parse_range
    this = this or self._parse_bitwise()
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Repositories/sqlglot/sqlglot/dialects/teradata.py", line 282, in _parse_bitwise
    this = self._parse_term()
           ^^^^^^^^^^^^^^^^^^
  File "/Repositories/sqlglot/sqlglot/parser.py", line 4627, in _parse_term
    this = self._parse_factor()
           ^^^^^^^^^^^^^^^^^^^^
  File "/Repositories/sqlglot/sqlglot/parser.py", line 4650, in _parse_factor
    this = parse_method()
           ^^^^^^^^^^^^^^
  File "/Repositories/sqlglot/sqlglot/parser.py", line 4670, in _parse_exponent
    return self._parse_tokens(self._parse_unary, self.EXPONENT)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Repositories/sqlglot/sqlglot/parser.py", line 6633, in _parse_tokens
    this = parse_method()
           ^^^^^^^^^^^^^^
  File "/Repositories/sqlglot/sqlglot/parser.py", line 4675, in _parse_unary
    return self._parse_at_time_zone(self._parse_type())
                                    ^^^^^^^^^^^^^^^^^^
  File "/Repositories/sqlglot/sqlglot/parser.py", line 4727, in _parse_type
    this = self._parse_column()
           ^^^^^^^^^^^^^^^^^^^^
  File "/Repositories/sqlglot/sqlglot/parser.py", line 5010, in _parse_column
    this = self._parse_column_reference()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Repositories/sqlglot/sqlglot/parser.py", line 5019, in _parse_column_reference
    this = self._parse_field()
           ^^^^^^^^^^^^^^^^^^^
  File "/Repositories/sqlglot/sqlglot/parser.py", line 5210, in _parse_field
    field = self._parse_primary() or self._parse_function(
                                     ^^^^^^^^^^^^^^^^^^^^^
    File "/Repositories/sqlglot/sqlglot/parser.py", line 5233, in _parse_function
    func = self._parse_function_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Repositories/sqlglot/sqlglot/parser.py", line 5323, in _parse_function_call
    self._match_r_paren(this)
  File "/Repositories/sqlglot/sqlglot/parser.py", line 7255, in _match_r_paren
    self.raise_error("Expecting )")
  File "/Repositories/sqlglot/sqlglot/parser.py", line 1530, in raise_error
    raise error
sqlglot.errors.ParseError: Expecting ). Line 1, Col: 32.
  SELECT x (INTEGER, FORMAT '9999') (CHAR(4))
```

</details>

`x` is `TokenType.VAR`, so `_parse_field` calls `_parse_function` after returns None `_parse_primary` (sqlglot.parser line 5210):

```
            field = self._parse_primary() or self._parse_function(
                anonymous=anonymous_func, any_token=any_token
            )
```

and that calls `_parse_function_call`, which sees the next token being `TokenType.L_PAREN` and proceeds to try to parse the function arguments, failing on the  `'9999'` string after `FORMAT`. This means that removing '9999' causes it to parse the conversion incorrectly as an anonymous function named `x`:

```
>>> sqlglot.parse_one("SELECT x (INTEGER, FORMAT) (CHAR(4))", dialect="teradata")
Select(
  expressions=[
    Conversion(
      this=Anonymous(
        this=x,
        expressions=[
          Column(
            this=Identifier(this=INTEGER, quoted=False)),
          Column(
            this=Identifier(this=FORMAT, quoted=False))]),
      to=DataType(
        this=Type.CHAR,
        expressions=[
          DataTypeParam(
            this=Literal(this=4, is_string=False))],
        nested=False))])
```

## Implementation

So far I have taken a few shortcuts to get this working:

- Quick and dirty `Conversion`, `Named` and `Title` expressions within the Teradata dialect
- `NAMED` and `TITLE` tokens added to the `TokenType` class
- Overridden `_parse_bitwise` method added to the Teradata Parser class

### Where to Parse

While this conversion syntax is basically filling the same function as `CAST`, it does not have a function name to identify it. For that reason, I think of it more like an operator. For that reason I put it in `_parse_bitwise`, although perhaps `_parse_unary` would have worked as well. **Is this the right place for this?**

### Expressions

The `Conversion` expression I created allows for the specification of leading and trailing attributes. I think this is a bit messy and can be improved. There isn't any handling of the `FORMAT` values right now other than adding the literal as an attribute. **Perhaps `FORMAT` could have an expression of its own?**

### Overriding Parser Methods

Beware, quick and dirty code ahead. To get this to work, I created `_parse_bitwise` in the `Teradata.Parser` class along with some custom ones:

```
        def _parse_format(self) -> t.Optional[exp.Expression]:
            fmt_string = self._parse_string()
            return self._parse_at_time_zone(fmt_string)

        def _parse_attribute(self) -> t.Optional[exp.Expression]:
            if self._match_set(self.ATTRIBUTE_PARSERS):
                return self.ATTRIBUTE_PARSERS[self._prev.token_type](self)
            elif self._match(TokenType.FORMAT):
                return self._parse_format()
            return None

        def _parse_conversion(self, term: exp.Expression) -> t.Optional[exp.Expression]:
            to = None
            leading_attribute = self._parse_attribute()
            if not leading_attribute or self._match(TokenType.COMMA):
                to = self._parse_types()
            trailing_attribute = self._match(TokenType.COMMA) and self._parse_attribute()
            this = self.expression(
                Conversion,
                this=term,
                to=to,
                leading_attribute=leading_attribute,
                trailing_attribute=trailing_attribute
            )
            self._match_r_paren()
            return this

        def _parse_bitwise(self) -> t.Optional[exp.Expression]:
            this = super()._parse_bitwise()

            if this:
                while True:
                    if self._match(TokenType.L_PAREN):
                        this = self._parse_conversion(this)
                    else:
                        break

            return this
```

I'm concerned about maintenance issues with this and I'm also wondering about how other methods will need to be overridden to handle identifiers as terms to this conversion operator. 

**How should I minimise future maintenance burden while overriding `Parser` methods?** 

**Are there any examples of `Parser` method overrides that have or haven't worked well in other dialects?**

### Tests

I have a set of statements I'm using for testing but they are not complete for the range of possibilities in Teradata. I will add more and check them into my branch.

**Comment by georgesittas** [comment]
> How should I minimise future maintenance burden while overriding Parser methods?

I think keeping the logic within Teradata itself should suffice, no? If you *must* touch base code in an intrusive way, I'd parameterize that using a dialect flag or something.

> Are there any examples of Parser method overrides that have or haven't worked well in other dialects?

Yeah, look into `_parse_table_parts` in BigQuery. We needed that because they have some weird syntactical rules around table names and it was too intrusive to include in the base class.

**Comment by georgesittas** [comment]
Let's keep all expressions within `expressions.py`. If they're too Teradata-specific and there's no trivial way to map them to some other, more standard concept, then you can perhaps prefix them with `Teradata[...]` so it's clear we don't have them for transpilation purposes. Even though we don't do this for other concepts / expressions today, IIRC, it should be fine.

**Comment by thomascjohnson** [comment]
Ok, I've found some time to put together an implementation of this here: https://github.com/thomascjohnson/sqlglot/tree/teradata-conversion

I've added tests that cover different cases. The parsing code in the Teradata file can definitely be improved to be more consistent with the rest of the code, but I have some questions about error handling that I will ask you about on Slack.
