### ISSUE TITLE
Decimal numbers with leading decimal point can't be parsed

### ISSUE THREAD

**Issue by alieh-rymasheuski** [tobymao/sqlglot#491]
Example:
```python
print(sqlglot.parse_one("select .1"))
```
Expected result:
```python
(SELECT expressions: 
  (LITERAL this: .1, is_string: False))
```
Actual result:
```python
Traceback (most recent call last):
  File "/tmp/foo.py", line 3, in <module>
    print(sqlglot.parse_one("SELECT .1"))
  File ".../sqlglot/sqlglot/__init__.py", line 67, in parse_one
    result = dialect.parse(sql, **opts)
  File ".../sqlglot/sqlglot/dialects/dialect.py", line 129, in parse
    return self.parser(**opts).parse(self.tokenizer.tokenize(sql), sql)
  File ".../sqlglot/sqlglot/parser.py", line 479, in parse
    return self._parse(parse_method=self.__class__._parse_statement, raw_tokens=raw_tokens, sql=sql)
  File ".../sqlglot/sqlglot/parser.py", line 515, in _parse
    self.check_errors()
  File ".../sqlglot/sqlglot/parser.py", line 524, in check_errors
    raise ParseError(concat_errors(self.errors, self.max_errors))
sqlglot.errors.ParseError: Invalid expression / Unexpected token. Line 1, Col: 8.
  SELECT .1
         ^ underlined
```

I tried updating the tokenizer to recognize `"."` followed with a digit as a number, but a test for reference of items of a tuple started failing.
```diff
diff --git a/sqlglot/tokens.py b/sqlglot/tokens.py
index 7a50fc3..017193b 100644
--- a/sqlglot/tokens.py
+++ b/sqlglot/tokens.py
@@ -660,7 +660,7 @@ class Tokenizer(metaclass=_Tokenizer):
                 if white_space == TokenType.BREAK:
                     self._col = 1
                     self._line += 1
-            elif self._char.isdigit():
+            elif self._char.isdigit() or self._char == "." and self._peek.isdigit():
                 self._scan_number()
             elif identifier_end:
                 self._scan_identifier(identifier_end)
```
Failing test:
```python
======================================================================
ERROR: test_identity (tests.test_transpile.TestTranspile) [X((y AS z)).1]
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".../sqlglot/tests/test_transpile.py", line 286, in test_identity
    self.assertEqual(transpile(sql)[0], sql.strip())
  File ".../sqlglot/sqlglot/__init__.py", line 95, in transpile
    for expression in parse(sql, read, error_level=error_level)
  File ".../sqlglot/sqlglot/__init__.py", line 43, in parse
    return dialect.parse(sql, **opts)
  File ".../sqlglot/sqlglot/dialects/dialect.py", line 129, in parse
    return self.parser(**opts).parse(self.tokenizer.tokenize(sql), sql)
  File ".../sqlglot/sqlglot/parser.py", line 479, in parse
    return self._parse(parse_method=self.__class__._parse_statement, raw_tokens=raw_tokens, sql=sql)
  File ".../sqlglot/sqlglot/parser.py", line 515, in _parse
    self.check_errors()
  File ".../sqlglot/sqlglot/parser.py", line 524, in check_errors
    raise ParseError(concat_errors(self.errors, self.max_errors))
sqlglot.errors.ParseError: Invalid expression / Unexpected token. Line 1, Col: 12.
  X((y AS z)).1
```

While I'm struggling with making this work, maybe @tobymao can point me in the right direction?

**Comment by tobymao** [comment]
this is already in main

**Comment by alieh-rymasheuski** [comment]
Thank you - I didn't realize I wasn't testing against `main`.
