### ISSUE TITLE
sqlglot fails to parse `bqutil.fn.int(...)`

### ISSUE THREAD

**Issue by jli** [tobymao/sqlglot#509]
This fails to parse with sqlglot 6.2.5:
```
$ python -c 'import sqlglot; sqlglot.transpile("SELECT bqutil.fn.int(1.234)", read="bigquery")'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "env/lib/python3.8/site-packages/sqlglot/__init__.py", line 95, in transpile
    for expression in parse(sql, read, error_level=error_level)
  File "env/lib/python3.8/site-packages/sqlglot/__init__.py", line 43, in parse
    return dialect.parse(sql, **opts)
  File "env/lib/python3.8/site-packages/sqlglot/dialects/dialect.py", line 129, in parse
    return self.parser(**opts).parse(self.tokenizer.tokenize(sql), sql)
  File "env/lib/python3.8/site-packages/sqlglot/parser.py", line 488, in parse
    return self._parse(parse_method=self.__class__._parse_statement, raw_tokens=raw_tokens, sql=sql)
  File "env/lib/python3.8/site-packages/sqlglot/parser.py", line 524, in _parse
    self.check_errors()
  File "env/lib/python3.8/site-packages/sqlglot/parser.py", line 533, in check_errors
    raise ParseError(concat_errors(self.errors, self.max_errors))
sqlglot.errors.ParseError: Required keyword: 'expressions' missing for <class 'sqlglot.expressions.Aliases'>. Line 1, Col: 22.
  SELECT bqutil.fn.int(1.234)

Expecting ). Line 1, Col: 22.
  SELECT bqutil.fn.int(1.234)

Invalid expression / Unexpected token. Line 1, Col: 22.
  SELECT bqutil.fn.int(1.234)
```

This is a valid BigQuery query though:
![image](https://user-images.githubusercontent.com/133466/193150222-fb7692f2-152f-4b83-b7d6-50c5176f3fc7.png)

This is referencing function `int` in the `fn` dataset, in the `bqutil` GCP project. Here's docs on these functions:
https://github.com/GoogleCloudPlatform/bigquery-utils/blob/master/udfs/community/README.md

**Comment by tobymao** [comment]
thanks for the report, fixed in main
