### ISSUE TITLE
mysql parser chokes on numeric literal

### ISSUE THREAD

**Issue by hut8** [tobymao/sqlglot#658]
```
Traceback (most recent call last):
  File "/home/liam/.local/share/virtualenvs/sdow-6xvVatrD/lib/python3.10/site-packages/sqlglot/tokens.py", line 943, in _scan_formatted_string
    self._add(token_type, f"{int(text, base)}")
ValueError: invalid literal for int() with base 2: ',0,0,0.678463935699,'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/liam/sdow/./scripts/parse_page_data.py", line 26, in <module>
    stmt = sqlglot.parse_one(line, read="mysql")
  File "/home/liam/.local/share/virtualenvs/sdow-6xvVatrD/lib/python3.10/site-packages/sqlglot/__init__.py", line 75, in parse_one
    result = dialect.parse(sql, **opts)
  File "/home/liam/.local/share/virtualenvs/sdow-6xvVatrD/lib/python3.10/site-packages/sqlglot/dialects/dialect.py", line 135, in parse
    return self.parser(**opts).parse(self.tokenizer.tokenize(sql), sql)
  File "/home/liam/.local/share/virtualenvs/sdow-6xvVatrD/lib/python3.10/site-packages/sqlglot/tokens.py", line 727, in tokenize
    self._scan_keywords()
  File "/home/liam/.local/share/virtualenvs/sdow-6xvVatrD/lib/python3.10/site-packages/sqlglot/tokens.py", line 811, in _scan_keywords
    if self._scan_formatted_string(word):
  File "/home/liam/.local/share/virtualenvs/sdow-6xvVatrD/lib/python3.10/site-packages/sqlglot/tokens.py", line 945, in _scan_formatted_string
    raise RuntimeError(f"Numeric string contains invalid characters from {self._line}:{self._start}")
RuntimeError: Numeric string contains invalid characters from 1:700661
```

Input: https://gist.github.com/hut8/2929beb0813558942be0c8d95f564b5a

This is directly from a wikimedia dump (huge file, but this is just one line). The full dump is at https://dumps.wikimedia.org/enwiki/20221001/enwiki-20221001-page.sql.gz -- I mostly link to that to demonstrate that this is how `mysqldump` dumps the data, and therefore I believe it should be considered valid.

**Comment by tobymao** [comment]
this is due to mysql allowing \ as an escape for single quotes. i'm now able to parse the sample file

**Comment by hut8** [comment]
Thanks for such a quick fix. You're a great open source maintainer! Do you have a GitHub Sponsors account or another way for me to give you money?

**Comment by tobymao** [comment]
thanks for the high praise. i’m not accepting donations.
