### ISSUE TITLE
Parser doesn't recognize dash as part of number value in column def default clause 

### ISSUE THREAD

**Issue by andrewdoss-bit** [tobymao/sqlglot#728]
When parsing a column definition default clause with a negative value, the parser sees a preceding `DASH` as an unexpected token rather than as part of the value.

Minimal reproduction:
```python
create_table_sql = "CREATE TABLE foo (bar INTEGER DEFAULT -1);"
sqlglot.parse_one(create_table_sql, read="sqlite")
```

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/sqlglot/sqlglot/__init__.py", line 82, in parse_one
    result = dialect.parse(sql, **opts)
  File "/sqlglot/sqlglot/dialects/dialect.py", line 150, in parse
    return self.parser(**opts).parse(self.tokenizer.tokenize(sql), sql)
  File "/sqlglot/sqlglot/parser.py", line 604, in parse
    return self._parse(
  File "/sqlglot/sqlglot/parser.py", line 637, in _parse
    expressions.append(parse_method(self))
  File "/sqlglot/sqlglot/parser.py", line 728, in _parse_statement
    return self.STATEMENT_PARSERS[self._prev.token_type](self)
  File "/sqlglot/sqlglot/parser.py", line 391, in <lambda>
    TokenType.CREATE: lambda self: self._parse_create(),
  File "/sqlglot/sqlglot/parser.py", line 801, in _parse_create
    this = self._parse_table(schema=True)
  File "/sqlglot/sqlglot/parser.py", line 1417, in _parse_table
    return self._parse_schema(this=this)
  File "/sqlglot/sqlglot/parser.py", line 2138, in _parse_schema
    args = self._parse_csv(
  File "/sqlglot/sqlglot/parser.py", line 2614, in _parse_csv
    items = [parse_result] if parse_result is not None else []
  File "/sqlglot/sqlglot/parser.py", line 2139, in <lambda>
    lambda: self._parse_constraint() or self._parse_column_def(self._parse_field(True))
  File "/sqlglot/sqlglot/parser.py", line 2152, in _parse_column_def
    constraint = self._parse_column_constraint()
  File "/sqlglot/sqlglot/parser.py", line 2175, in _parse_column_constraint
    elif self._match_pair(TokenType.NOT, TokenType.NULL):
  File "/sqlglot/sqlglot/parser.py", line 673, in expression
    self.validate_expression(instance)
  File "/sqlglot/sqlglot/parser.py", line 686, in validate_expression
    self.raise_error(f"Required keyword: '{k}' missing for {expression.__class__}")
  File "/sqlglot/sqlglot/parser.py", line 665, in raise_error
    raise error
sqlglot.errors.ParseError: Required keyword: 'this' missing for <class 'sqlglot.expressions.DefaultColumnConstraint'>. Line 1, Col: 39.
  CREATE TABLE foo (bar INTEGER DEFAULT -1);
```

**Comment by andrewdoss-bit** [comment]
Thank you!
