### ISSUE TITLE
Parser doesn't recognize a foreign-key-clause within a column definition

### ISSUE THREAD

**Issue by andrewdoss-bit** [tobymao/sqlglot#729]
When parsing a column definition with a foreign-key-clause, the parser does not expect the key word `REFERENCES`.

Minimal reproduction:
```python
create_table_sql = "CREATE TABLE bar (id INTEGER PRIMARY KEY, foo_id INTEGER REFERENCES foo (id));"
sqlglot.parse_one(create_table_sql, read="sqlite")
```

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/sqlglot/sqlglot/__init__.py", line 82, in parse_one
    result = dialect.parse(sql, **opts)
  File "/sqlglot/sqlglot/dialects/dialect.py", line 150, in parse
    return self.parser(**opts).parse(self.tokenizer.tokenize(sql), sql)
  File "/sqlglot/sqlglot/parser.py", line 604, in parse
    return self._parse(
  File "/sqlglot/sqlglot/parser.py", line 637, in _parse
    expressions.append(parse_method(self))
  File "/sqlglot/sqlglot/parser.py", line 728, in _parse_statement
    return self.STATEMENT_PARSERS[self._prev.token_type](self)
  File "/sqlglot/sqlglot/parser.py", line 391, in <lambda>
    TokenType.CREATE: lambda self: self._parse_create(),
  File "/sqlglot/sqlglot/parser.py", line 801, in _parse_create
    this = self._parse_table(schema=True)
  File "/sqlglot/sqlglot/parser.py", line 1417, in _parse_table
    return self._parse_schema(this=this)
  File "/sqlglot/sqlglot/parser.py", line 2140, in _parse_schema
    self._match_r_paren()
  File "/sqlglot/sqlglot/parser.py", line 2758, in _match_r_paren
    self.raise_error("Expecting )")
  File "/sqlglot/sqlglot/parser.py", line 665, in raise_error
    raise error
sqlglot.errors.ParseError: Expecting ). Line 1, Col: 58.
  CREATE TABLE bar (id INTEGER PRIMARY KEY, foo_id INTEGER REFERENCES foo (id));
```

**Comment by andrewdoss-bit** [comment]
Thank you!

**Comment by tobymao** [comment]
@andrewdoss-bit no problem. thanks for filing issues
