### ISSUE TITLE
[sqlite dialect] Parser doesn't recognize optional order parameter for PKEY column-constraint

### ISSUE THREAD

**Issue by andrewdoss-bit** [tobymao/sqlglot#742]
sqlite's `CREATE TABLE` statement accepts an optional order parameter for `PRIMARY KEY` column-constraints. `sqlglot` does not yet handle this parameter:

```python
create_table_sql = "CREATE TABLE foo (id INTEGER PRIMARY KEY ASC);"
sqlglot.parse_one(create_table_sql, read="sqlite")
```

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/sqlglot/sqlglot/__init__.py", line 82, in parse_one
    result = dialect.parse(sql, **opts)
  File "/sqlglot/sqlglot/dialects/dialect.py", line 150, in parse
    return self.parser(**opts).parse(self.tokenizer.tokenize(sql), sql)
  File "/sqlglot/sqlglot/parser.py", line 604, in parse
    return self._parse(
  File "/sqlglot/sqlglot/parser.py", line 637, in _parse
    expressions.append(parse_method(self))
  File "/sqlglot/sqlglot/parser.py", line 728, in _parse_statement
    return self.STATEMENT_PARSERS[self._prev.token_type](self)
  File "/sqlglot/sqlglot/parser.py", line 391, in <lambda>
    TokenType.CREATE: lambda self: self._parse_create(),
  File "/sqlglot/sqlglot/parser.py", line 801, in _parse_create
    this = self._parse_table(schema=True)
  File "/sqlglot/sqlglot/parser.py", line 1417, in _parse_table
    return self._parse_schema(this=this)
  File "/sqlglot/sqlglot/parser.py", line 2140, in _parse_schema
    self._match_r_paren()
  File "/sqlglot/sqlglot/parser.py", line 2759, in _match_r_paren
    self.raise_error("Expecting )")
  File "/sqlglot/sqlglot/parser.py", line 665, in raise_error
    raise error
sqlglot.errors.ParseError: Expecting ). Line 1, Col: 42.
  CREATE TABLE foo (id INTEGER PRIMARY KEY ASC);
```

**Comment by andrewdoss-bit** [comment]
Awesome, thanks.
