### ISSUE TITLE
Failure to parse nested SELECT in ARRAY [Dialect: BigQuery]

### ISSUE THREAD

**Issue by badboy** [tobymao/sqlglot#797]
sqlglot 10.1.3 fails to parse this query:

```sql
SELECT ARRAY(SELECT x * 2 FROM UNNEST([0, 1]) AS x)
```

The inner `SELECT` makes it fail.
(My actual query is of course more complex than this, but I trimmed it down to the essentials)

Full code:

```python
from sqlglot import parse_one
content = "SELECT ARRAY(SELECT x FROM UNNEST([0, 1]) AS x)"
print(repr(parse_one(content, read="bigquery")))
```

Error:

```
sqlglot.errors.ParseError: Expecting ). Line 1, Col: 14.
  SELECT ARRAY(_SELECT_ x FROM UNNEST([0, 1]) AS x)
```

(Underscores used to highlight the part highlighted in the terminal)

Full error:

<details>

```
Traceback (most recent call last):
  File "/home/jer/py-sql-extract/bug.py", line 6, in <module>
    print(repr(parse_one(content, read="bigquery")))
  File "/home/jer/py-sql-extract/.venv/lib/python3.10/site-packages/sqlglot/__init__.py", line 82, in parse_one
    result = dialect.parse(sql, **opts)
  File "/home/jer/py-sql-extract/.venv/lib/python3.10/site-packages/sqlglot/dialects/dialect.py", line 150, in parse
    return self.parser(**opts).parse(self.tokenizer.tokenize(sql), sql)
  File "/home/jer/py-sql-extract/.venv/lib/python3.10/site-packages/sqlglot/parser.py", line 622, in parse
    return self._parse(
  File "/home/jer/py-sql-extract/.venv/lib/python3.10/site-packages/sqlglot/parser.py", line 660, in _parse
    expressions.append(parse_method(self))
  File "/home/jer/py-sql-extract/.venv/lib/python3.10/site-packages/sqlglot/parser.py", line 772, in _parse_statement
    expression = self._parse_set_operations(expression) if expression else self._parse_select()
  File "/home/jer/py-sql-extract/.venv/lib/python3.10/site-packages/sqlglot/parser.py", line 1119, in _parse_select
    expressions = self._parse_csv(self._parse_expression)
  File "/home/jer/py-sql-extract/.venv/lib/python3.10/site-packages/sqlglot/parser.py", line 2541, in _parse_csv
    parse_result = parse_method()
  File "/home/jer/py-sql-extract/.venv/lib/python3.10/site-packages/sqlglot/parser.py", line 1642, in _parse_expression
    return self._parse_alias(self._parse_conjunction())
  File "/home/jer/py-sql-extract/.venv/lib/python3.10/site-packages/sqlglot/parser.py", line 1645, in _parse_conjunction
    return self._parse_tokens(self._parse_equality, self.CONJUNCTION)
  File "/home/jer/py-sql-extract/.venv/lib/python3.10/site-packages/sqlglot/parser.py", line 2555, in _parse_tokens
    this = parse_method()
  File "/home/jer/py-sql-extract/.venv/lib/python3.10/site-packages/sqlglot/parser.py", line 1648, in _parse_equality
    return self._parse_tokens(self._parse_comparison, self.EQUALITY)
  File "/home/jer/py-sql-extract/.venv/lib/python3.10/site-packages/sqlglot/parser.py", line 2555, in _parse_tokens
    this = parse_method()
  File "/home/jer/py-sql-extract/.venv/lib/python3.10/site-packages/sqlglot/parser.py", line 1651, in _parse_comparison
    return self._parse_tokens(self._parse_range, self.COMPARISON)
  File "/home/jer/py-sql-extract/.venv/lib/python3.10/site-packages/sqlglot/parser.py", line 2555, in _parse_tokens
    this = parse_method()
  File "/home/jer/py-sql-extract/.venv/lib/python3.10/site-packages/sqlglot/parser.py", line 1654, in _parse_range
    this = self._parse_bitwise()
  File "/home/jer/py-sql-extract/.venv/lib/python3.10/site-packages/sqlglot/parser.py", line 1716, in _parse_bitwise
    this = self._parse_term()
  File "/home/jer/py-sql-extract/.venv/lib/python3.10/site-packages/sqlglot/parser.py", line 1739, in _parse_term
    return self._parse_tokens(self._parse_factor, self.TERM)
  File "/home/jer/py-sql-extract/.venv/lib/python3.10/site-packages/sqlglot/parser.py", line 2555, in _parse_tokens
    this = parse_method()
  File "/home/jer/py-sql-extract/.venv/lib/python3.10/site-packages/sqlglot/parser.py", line 1742, in _parse_factor
    return self._parse_tokens(self._parse_unary, self.FACTOR)
  File "/home/jer/py-sql-extract/.venv/lib/python3.10/site-packages/sqlglot/parser.py", line 2555, in _parse_tokens
    this = parse_method()
  File "/home/jer/py-sql-extract/.venv/lib/python3.10/site-packages/sqlglot/parser.py", line 1747, in _parse_unary
    return self._parse_at_time_zone(self._parse_type())
  File "/home/jer/py-sql-extract/.venv/lib/python3.10/site-packages/sqlglot/parser.py", line 1755, in _parse_type
    this = self._parse_column()
  File "/home/jer/py-sql-extract/.venv/lib/python3.10/site-packages/sqlglot/parser.py", line 1864, in _parse_column
    this = self._parse_field()
  File "/home/jer/py-sql-extract/.venv/lib/python3.10/site-packages/sqlglot/parser.py", line 1935, in _parse_field
    return self._parse_primary() or self._parse_function() or self._parse_id_var(any_token)
  File "/home/jer/py-sql-extract/.venv/lib/python3.10/site-packages/sqlglot/parser.py", line 1982, in _parse_function
    self._match_r_paren(this)
  File "/home/jer/py-sql-extract/.venv/lib/python3.10/site-packages/sqlglot/parser.py", line 2698, in _match_r_paren
    self.raise_error("Expecting )")
  File "/home/jer/py-sql-extract/.venv/lib/python3.10/site-packages/sqlglot/parser.py", line 697, in raise_error
    raise error
sqlglot.errors.ParseError: Expecting ). Line 1, Col: 14.
  SELECT ARRAY([4mSELECT[0m x FROM UNNEST([0, 1]) AS x)
```

</details>

**Comment by badboy** [comment]
Wow, this was fast! Thank you!

**Comment by GeorgeSittas** [comment]
You're welcome, thanks for the great report!
