### ISSUE TITLE
exists clause does not support

### ISSUE THREAD

**Issue by sasano8** [tobymao/sqlglot#87]
I get the following error:

```
# version: sqlglot 1.26.1

from sqlglot import parse_one
parse_one("SELECT * FROM demo where exists (select * from demo)")
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sasano8/projects/sqlsuper/.venv/lib/python3.8/site-packages/sqlglot/__init__.py", line 44, in parse_one
    return parse(code, read=read, **opts)[0]
  File "/home/sasano8/projects/sqlsuper/.venv/lib/python3.8/site-packages/sqlglot/__init__.py", line 27, in parse
    return dialect.parse(code, **opts)
  File "/home/sasano8/projects/sqlsuper/.venv/lib/python3.8/site-packages/sqlglot/dialects.py", line 62, in parse
    return self.parser(**opts).parse(self.tokenizer().tokenize(code), code)
  File "/home/sasano8/projects/sqlsuper/.venv/lib/python3.8/site-packages/sqlglot/parser.py", line 255, in parse
    self.check_errors()
  File "/home/sasano8/projects/sqlsuper/.venv/lib/python3.8/site-packages/sqlglot/parser.py", line 263, in check_errors
    raise error
sqlglot.errors.ParseError: Expecting ). Line 1, Col: 34.
  SELECT * FROM demo where exists (select * from demo)
```

**Comment by tobymao** [comment]
what dialect is exist? i'm not familiar with it

**Comment by sasano8** [comment]
In my understanding, 'exists ' is a common operator in SQL.
Defined with at least SQL: 2011.


The following page is unofficial, but you can see the SQL specifications that comply with SQL: 2011.

https://en.wikibooks.org/wiki/Structured_Query_Language


The 'exists' clause takes a subquery as an argument.

https://en.wikibooks.org/wiki/Structured_Query_Language/Quantified_Comparison

**Comment by tobymao** [comment]
this is now in v1.27.0

**Comment by sasano8** [comment]
Thank you. It worked.

I'm trying out some SQL parsers.(sqlparse, moz_sql_parser) Among them, sqlglot feels great.

**Comment by tobymao** [comment]
great!
