### ISSUE TITLE
[sqlite dialect] Parser doesn't handle `DOUBLE PRECISION` column type

### ISSUE THREAD

**Issue by andrewdoss-bit** [tobymao/sqlglot#904]
Reproduction:

```python
create_table_sql = "CREATE TABLE foo (bar DOUBLE PRECISION);"
sqlglot.parse_one(create_table_sql, read="sqlite")
```

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/sqlglot/sqlglot/__init__.py", line 84, in parse_one
    result = dialect.parse(sql, **opts)
  File "/sqlglot/sqlglot/dialects/dialect.py", line 150, in parse
    return self.parser(**opts).parse(self.tokenizer.tokenize(sql), sql)
  File "/sqlglot/sqlglot/parser.py", line 664, in parse
    return self._parse(
  File "/sqlglot/sqlglot/parser.py", line 702, in _parse
    expressions.append(parse_method(self))
  File "/sqlglot/sqlglot/parser.py", line 804, in _parse_statement
    return self.STATEMENT_PARSERS[self._prev.token_type](self)
  File "/sqlglot/sqlglot/parser.py", line 429, in <lambda>
    TokenType.CREATE: lambda self: self._parse_create(),
  File "/sqlglot/sqlglot/parser.py", line 882, in _parse_create
    this = self._parse_table(schema=True)
  File "/sqlglot/sqlglot/parser.py", line 1464, in _parse_table
    return self._parse_schema(this=this)
  File "/sqlglot/sqlglot/parser.py", line 2191, in _parse_schema
    self._match_r_paren()
  File "/sqlglot/sqlglot/parser.py", line 2953, in _match_r_paren
    self.raise_error("Expecting )")
  File "/sqlglot/sqlglot/parser.py", line 739, in raise_error
    raise error
sqlglot.errors.ParseError: Expecting ). Line 1, Col: 27.
  CREATE TABLE foo(x double precision)
```

I'm not sure if this is actually considered a bug — `DOUBLE PRECISION` is not ["strict"](https://www.sqlite.org/stricttables.html) sqlite. However, [`DOUBLE PRECISION`  matches `sqlite`'s rules as a `REAL` "type-affinity"](https://www.sqlite.org/datatype3.html) and `sqlglot` currently parses `DOUBLE` from sqlite column definitions, which is also not a "strict" sqlite data type.

**Comment by andrewdoss-bit** [comment]
Thanks!
