### ISSUE TITLE
[spark dialect] Parser doesn't work when column name starts with digits and used with alias

### ISSUE THREAD

**Issue by XhivaW** [tobymao/sqlglot#916]
reproduction:

```python
from sqlglot import parse_one
sql = "select A.1a as b from test_a A"
parse_one(sql, read='spark')
```

error:
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.8/site-packages/sqlglot/__init__.py", line 84, in parse_one
    result = dialect.parse(sql, **opts)
  File "/opt/homebrew/lib/python3.8/site-packages/sqlglot/dialects/dialect.py", line 150, in parse
    return self.parser(**opts).parse(self.tokenizer.tokenize(sql), sql)
  File "/opt/homebrew/lib/python3.8/site-packages/sqlglot/parser.py", line 666, in parse
    return self._parse(
  File "/opt/homebrew/lib/python3.8/site-packages/sqlglot/parser.py", line 730, in _parse
    self.raise_error("Invalid expression / Unexpected token")
  File "/opt/homebrew/lib/python3.8/site-packages/sqlglot/parser.py", line 773, in raise_error
    raise error
sqlglot.errors.ParseError: Invalid expression / Unexpected token. Line 1, Col: 13.
  SELECT A.1a as b from test_a A
```

BTW when column name starts with digits but without alias, the parser works, but incorrectly,  the digits are recognized as table name 
```python
from sqlglot import parse_one
sql="""SELECT A.1a from test_a A"""
parse_one(sql, read='spark')
>>> (SELECT expressions: 
  (ALIAS this: 
    (COLUMN this: 
      (IDENTIFIER this: 1, quoted: False), table: 
      (IDENTIFIER this: A, quoted: False)), alias: 
    (IDENTIFIER this: a, quoted: False)), from: 
  (FROM expressions: 
    (TABLE this: 
      (IDENTIFIER this: test_a, quoted: False), alias: 
      (TABLEALIAS this: 
        (IDENTIFIER this: A, quoted: False)))))
```

**Comment by tobymao** [comment]
this doesn't seem to be a standard, looks like it works in spark but not postgres

for now, you can get around this by quoting your columns a.`1a`

**Comment by XhivaW** [comment]
thx for reply 
Since it works in spark, and lots people write like this, I believe it would be great if the parser support such format in spark dialect option`read='spark'`?

**Comment by XhivaW** [comment]
@GeorgeSittas hi thx for the fix but I found the parser still doesn't work with underscore as below:

reproduction:
```python
from sqlglot import parse_one
sql = "select 1_a as a from test_table"
parse_one(sql, read='spark')
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.8/site-packages/sqlglot/__init__.py", line 84, in parse_one
    result = dialect.parse(sql, **opts)
  File "/opt/homebrew/lib/python3.8/site-packages/sqlglot/dialects/dialect.py", line 150, in parse
    return self.parser(**opts).parse(self.tokenizer.tokenize(sql), sql)
  File "/opt/homebrew/lib/python3.8/site-packages/sqlglot/parser.py", line 667, in parse
    return self._parse(
  File "/opt/homebrew/lib/python3.8/site-packages/sqlglot/parser.py", line 731, in _parse
    self.raise_error("Invalid expression / Unexpected token")
  File "/opt/homebrew/lib/python3.8/site-packages/sqlglot/parser.py", line 774, in raise_error
    raise error
sqlglot.errors.ParseError: Invalid expression / Unexpected token. Line 1, Col: 12.
  select 1_a as a from test_table
```
