### ISSUE TITLE
[spark dialect] Parser doesn't work with msck repair 

### ISSUE THREAD

**Issue by XhivaW** [tobymao/sqlglot#928]
reproduction:

```python
from sqlglot import parse_one
sql = "msck repair table test_a"
parse_one(sql, read='spark')
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.8/site-packages/sqlglot/__init__.py", line 84, in parse_one
    result = dialect.parse(sql, **opts)
  File "/opt/homebrew/lib/python3.8/site-packages/sqlglot/dialects/dialect.py", line 150, in parse
    return self.parser(**opts).parse(self.tokenizer.tokenize(sql), sql)
  File "/opt/homebrew/lib/python3.8/site-packages/sqlglot/parser.py", line 667, in parse
    return self._parse(
  File "/opt/homebrew/lib/python3.8/site-packages/sqlglot/parser.py", line 731, in _parse
    self.raise_error("Invalid expression / Unexpected token")
  File "/opt/homebrew/lib/python3.8/site-packages/sqlglot/parser.py", line 774, in raise_error
    raise error
sqlglot.errors.ParseError: Invalid expression / Unexpected token. Line 1, Col: 13.
  msck repair table test_a
```

`msck repair` is used in hive/spark to check and fix metastore change

**Comment by tobymao** [comment]
out of curiosity what is your use case for parsing this?
