### ISSUE TITLE
ParseError thrown with whitespace in column name

### ISSUE THREAD

**Issue by mharrisb1** [tobymao/sqlglot#943]
Exception:

```
Traceback (most recent call last):
File "foo/bar/.venv/lib/python3.10/site-packages/sqlglot/parser.py", line 695, in parse_into
return self._parse(parser, raw_tokens, sql)
File "foo/bar/.venv/lib/python3.10/site-packages/sqlglot/parser.py", line 730, in _parse
self.raise_error("Invalid expression / Unexpected token")
File "foo/bar/.venv/lib/python3.10/site-packages/sqlglot/parser.py", line 773, in raise_error
raise error
sqlglot.errors.ParseError: Invalid expression / Unexpected token. Line 1, Col: 5.
zip code
```

Schema:

```python
{
    'postgres': {
        'pagila': {
            'address': 'text',
            'city': 'text',
            'country': 'text',
            'id': 'integer',
            'name': 'text',
            'notes': 'text',
            'phone': 'text',
            'sid': 'integer',
            'zip code': 'text'
        }
    }
}
```

Dialect: `Postgres`

Query:

```sql
SELECT 
    t1."actor_id" AS "actor_id",
    t1."first_name" AS "first_name",
    t1."last_name" AS "last_name",
    COUNT(*) AS "film_count"
FROM
    "postgres"."pagila"."actor" AS t1
    INNER JOIN "postgres"."pagila"."film_actor" AS t2 ON t1."actor_id" = t2."actor_id"
GROUP BY
    t1."actor_id",
    t1."first_name",
    t1."last_name"
ORDER BY
    "film_count" DESC
LIMIT
    1
```

Enabled rules:
- eliminate_ctes
- eliminate_joins
- eliminate_subqueries
- merge_subqueries
- normalize
- optimize_joins
- pushdown_predicates
- pushdown_projections
- unnest_subqueries

**Comment by mharrisb1** [comment]
@tobymao blown away by the response time. Thanks!
